#!/bin/sh
n=$(ls -1 full/ | wc -l)
i=1

while [ $i -le $n ]
do
	echo -ne "\t($i of $n domains)\r"
	domain=$(ls -1 full/ | sed "${i}q;d")
	cat full/$domain | grep NOERROR | awk '{print $2}' > knownhosts/$domain
	i=$((++i))
done
