#!/bin/sh
# Need to pull the domains from the domains file
# that are repeats

mkdir results

n=$(wc -l domains | awk '{print $1}')
i=1
while [ $i -le $n ]
do
	echo -ne "\t\t$i\tof\t$n\t\t\r"
	domain=$(sed "${i}q;d" domains)
	multi=$(grep $domain audit/multi.csv)

	cp probing/servers/$domain results/

	if [ -z "$multi" ]; then
		echo "Not in multi"
	else
		d2=$(grep $domain audit/multi.csv | awk -F "," '{print $5}')
		d3=$(grep $domain audit/multi.csv | awk -F "," '{print $6}')
		if [ "$d3" = 'NA' ]; then
			cat probing/servers/$d2 >> results/$domain
			rm probing/servers/$d2
			n=$(wc -l domains | awk '{print $1}')
		else
			cat probing/servers/{$d2,$d3} >> results/$domain
			rm probing/servers/{$d2,$d3}
			n=$(wc -l domains | awk '{print $1}')
		fi
	fi
	i=$((++i))
done
