#!/bin/sh
# Need to pull the domains from the domains file
# that are repeats

mkdir results

n=$(ls -1 probing/servers/ | wc -l)
i=1
while [ $i -le $n ]
do
	echo -ne "\t\t$i\tof\t$n\t\t\r"
	domain=$(ls -1 probing/servers/ | sed "${i}q;d")
	multi=$(grep $domain audit/multi.csv)

	cp probing/servers/$domain results/

	if [ -z "$multi" ]; then
		echo "Not in multi"
	else
		echo "\t***\t***\t***\tIN MULTI\t***\t***\t***\t\n"
		d2=$(grep $domain audit/multi.csv | awk -F "," '{print $5}')
		d3=$(grep $domain audit/multi.csv | awk -F "," '{print $6}')
		if [ "$d3" = 'NA' ]; then
			cat probing/servers/$d2 >> results/$domain
		else
			cat probing/servers/{$d2,$d3} >> results/$domain
		fi
	fi
	i=$((++i))
done
cat audit/removemulti.csv | xargs rm
