#!/bin/sh
./concat > concat.output
ls -1 results/ > domains
Rscript proportions.R > props.output
Rscript calculate.R
# Maybe add a script to make the new graphs for the report - plots.R

# Run concat, to concatinate all the psus into the results folder
# Then run proportions.R to calculate the proportions per psu
# Run calc.R to calculate the estimates
