Microsoft-IIS/8.5
NA
NA
NA
NA
NA
Apache
Apache/2.4.43 (Win64) OpenSSL/1.1.1g PHP/7.4.7
nginx/1.18.0 (Ubuntu)
NA
NA
NA
NA
Apache
Apache
Apache
NA
NA
Apache
Apache
Apache
Microsoft-IIS/8.5
Microsoft-IIS/8.5
NA
NA
NA
NA
NA
Apache
NA
Apache
NA
HTTP/1.1 500 Internal Server Error Apache/2.2.12 (Linux/SUSE)
NA
NA
Apache
Microsoft-IIS/8.5
Apache/2.4.43 (Win64) OpenSSL/1.1.1g PHP/7.4.7
NA
Apache
Apache
Apache
Apache/2.4.18 (Ubuntu)
NA
NA
NA
NA
Apache/2.2.22 (Ubuntu)
Apache
NA
Apache
Microsoft-IIS/8.5
NA
NA
Apache/2.2.12 (Linux/SUSE)
NA
Microsoft-IIS/8.5
Apache
NA
Apache-Coyote/1.1
NA
NA
NA
NA
Apache/2.2.21 (Win32) PHP/5.2.17
NA
Apache
NA
Apache/2.4.43 (Win64) OpenSSL/1.1.1g PHP/7.4.7
Apache
Apache
Apache
Apache
NA
Apache
Apache
NA
Microsoft-IIS/8.5
Apache/2.4.18 (Ubuntu)
Apache/2.4.18 (Ubuntu)
Apache-Coyote/1.1
Apache
Apache
NA
Apache
NA
Apache
nginx/1.18.0 (Ubuntu)
NA
Apache/2.4.18 (Ubuntu)
Microsoft-IIS/8.5
Apache
Apache/2.2.12 (Linux/SUSE)
Apache/2.2.12 (Linux/SUSE)
Apache/2.4.41 (Win64) OpenSSL/1.1.1c
Apache
NA
HTTP/1.1 500 Internal Server Error Apache/2.2.12 (Linux/SUSE)
NA
NA
NA
Apache
NA
NA
Apache/2.4.18 (Ubuntu)
Apache/2.4.41 (Ubuntu)
NA
Apache/2.4.18 (Ubuntu)
NA
NA
nginx
nginx/1.18.0 (Ubuntu)
NA
Apache
Apache/2.4.43 (Win64) OpenSSL/1.1.1g PHP/7.4.7
Apache
NA
Apache/2.4.41 (Ubuntu)
Microsoft-IIS/8.5
NA
NA
Apache
NA
NA
Apache
NA
NA
NA
NA
Apache
Apache
NA
Apache
Apache/2.4.29 (Ubuntu)
Apache
NA
NA
Apache
Apache
Apache
NA
NA
NA
NA
NA
Apache
Apache/2.2.21 (Win32) PHP/5.2.17
Apache/2.4.18 (Ubuntu)
Apache
NA
Apache
Apache
