NOERROR	dhcp213.mel.ar.wroc.pl
NOERROR	dhcp91.mel.ar.wroc.pl
NOERROR	imr152.mech.ar.wroc.pl
NOERROR	komp47.hod.ar.wroc.pl
NOERROR	ksz187.ar.wroc.pl
NXDOMAIN	dziekan.ar.wroc.pl
NOERROR	ekono-86.ar.wroc.pl
NXDOMAIN	klin87.ar.wroc.pl
NOERROR	imr74.mech.ar.wroc.pl
NOERROR	imr160.mech.ar.wroc.pl
NXDOMAIN	klin74.ar.wroc.pl
NOERROR	dhcp146.mel.ar.wroc.pl
NXDOMAIN	cental2.ar.wroc.pl
NOERROR	imr227.mech.ar.wroc.pl
NOERROR	budg252.ar.wroc.pl
NOERROR	wyd10.ar.wroc.pl
NOERROR	imr172.mech.ar.wroc.pl
NOERROR	dz-tech.ar.wroc.pl
NOERROR	komp176.hod.ar.wroc.pl
NOERROR	imr219.mech.ar.wroc.pl
NOERROR	komp17.cadlab.ar.wroc.pl
NOERROR	budg143.ar.wroc.pl
NOERROR	budg228.ar.wroc.pl
NOERROR	dhcp160.mel.ar.wroc.pl
NOERROR	wk-g.hod.ar.wroc.pl
NOERROR	ksz211.ar.wroc.pl
NXDOMAIN	kptw.ar.wroc.pl
NOERROR	ksz204.ar.wroc.pl
NOERROR	dhcp103.mel.ar.wroc.pl
NOERROR	buch214.ar.wroc.pl
NOERROR	imr196.mech.ar.wroc.pl
NOERROR	imr61.mech.ar.wroc.pl
NOERROR	budg247.ar.wroc.pl
NOERROR	wyd29.ar.wroc.pl
NOERROR	dhcp97.mel.ar.wroc.pl
NOERROR	wyd22.ar.wroc.pl
NOERROR	imr127.mech.ar.wroc.pl
NOERROR	komp219.hod.ar.wroc.pl
NOERROR	imr44.mech.ar.wroc.pl
NOERROR	ksz199.ar.wroc.pl
NOERROR	imr210.mech.ar.wroc.pl
NOERROR	srv2h.hod.ar.wroc.pl
NXDOMAIN	sopocka2.ar.wroc.pl
NOERROR	dhcp195.mel.ar.wroc.pl
NOERROR	imr151.mech.ar.wroc.pl
NOERROR	komp186.hod.ar.wroc.pl
NOERROR	imr140.mech.ar.wroc.pl
NOERROR	ksz200.ar.wroc.pl
NOERROR	ekono-70.ar.wroc.pl
NOERROR	dhcp192.mel.ar.wroc.pl
NOERROR	budg158.ar.wroc.pl
NOERROR	imr142.mech.ar.wroc.pl
NOERROR	imr214.mech.ar.wroc.pl
NOERROR	wyd35.ar.wroc.pl
NOERROR	dhcp193.mel.ar.wroc.pl
NOERROR	ksz203.ar.wroc.pl
NXDOMAIN	klin68.ar.wroc.pl
NOERROR	wyd28.ar.wroc.pl
NOERROR	komp51.hod.ar.wroc.pl
NOERROR	komp197.hod.ar.wroc.pl
NOERROR	komp232.hod.ar.wroc.pl
NOERROR	komp235.hod.ar.wroc.pl
NOERROR	komp233.hod.ar.wroc.pl
NOERROR	budg161.ar.wroc.pl
NOERROR	buch220.ar.wroc.pl
NOERROR	buch201.ar.wroc.pl
NOERROR	dhcp189.mel.ar.wroc.pl
NOERROR	imr62.mech.ar.wroc.pl
NOERROR	apar235.ar.wroc.pl
NXDOMAIN	klin93.ar.wroc.pl
NOERROR	ksz166.ar.wroc.pl
NXDOMAIN	klin82.ar.wroc.pl
NOERROR	komp12.cadlab.ar.wroc.pl
NXDOMAIN	lomot2.atlans.ar.wroc.pl
NOERROR	gen150.hod.ar.wroc.pl
NOERROR	ksz145.ar.wroc.pl
NOERROR	buch208.ar.wroc.pl
NOERROR	sw1.mel.ar.wroc.pl
NOERROR	komp198.hod.ar.wroc.pl
NXDOMAIN	klin112.ar.wroc.pl
NOERROR	dhcp119.mel.ar.wroc.pl
NOERROR	komp205.hod.ar.wroc.pl
NOERROR	sw8.mel.ar.wroc.pl
NOERROR	ada26.ar.wroc.pl
NOERROR	dhcp180.mel.ar.wroc.pl
NOERROR	imr153.mech.ar.wroc.pl
NOERROR	imr161.mech.ar.wroc.pl
NOERROR	ada7.ar.wroc.pl
NOERROR	komp195.hod.ar.wroc.pl
NOERROR	imr32.mech.ar.wroc.pl
NOERROR	gen66.hod.ar.wroc.pl
NXDOMAIN	aqua.ar.wroc.pl
NOERROR	budg251.ar.wroc.pl
NOERROR	ekono-124.ar.wroc.pl
NOERROR	gen143.hod.ar.wroc.pl
NOERROR	buch212.ar.wroc.pl
NOERROR	komp232.mel.ar.wroc.pl
NOERROR	imr66.mech.ar.wroc.pl
NOERROR	gen138.hod.ar.wroc.pl
NOERROR	ekono-93.ar.wroc.pl
NOERROR	ekono-81.ar.wroc.pl
NOERROR	ada13.ar.wroc.pl
NOERROR	gen75.hod.ar.wroc.pl
NOERROR	imr16.mech.ar.wroc.pl
NOERROR	ksz161.ar.wroc.pl
NOERROR	sw2.mel.ar.wroc.pl
NOERROR	ksz182.ar.wroc.pl
NOERROR	komp28.cadlab.ar.wroc.pl
NOERROR	komp30.cadlab.ar.wroc.pl
NOERROR	komp240.hod.ar.wroc.pl
NOERROR	dhcp104.mel.ar.wroc.pl
NOERROR	komp166.hod.ar.wroc.pl
NOERROR	komp200.hod.ar.wroc.pl
NXDOMAIN	klin92.ar.wroc.pl
NOERROR	apar241.ar.wroc.pl
NOERROR	apar238.ar.wroc.pl
NOERROR	komp208.hod.ar.wroc.pl
NOERROR	ksz207.ar.wroc.pl
NOERROR	ekono-67.ar.wroc.pl
NXDOMAIN	klin114.ar.wroc.pl
NXDOMAIN	geo1.ar.wroc.pl
NXDOMAIN	klin98.ar.wroc.pl
NOERROR	imr215.mech.ar.wroc.pl
NOERROR	budg236.ar.wroc.pl
NXDOMAIN	www.gislab.ar.wroc.pl
NOERROR	ksz160.ar.wroc.pl
NOERROR	imr96.mech.ar.wroc.pl
NOERROR	imr222.mech.ar.wroc.pl
NOERROR	komp06.cadlab.ar.wroc.pl
NXDOMAIN	www.azs.ar.wroc.pl
NOERROR	imr15.mech.ar.wroc.pl
NOERROR	dhcp124.mel.ar.wroc.pl
NOERROR	komp228.hod.ar.wroc.pl
NOERROR	imr83.mech.ar.wroc.pl
NOERROR	imr17.mech.ar.wroc.pl
NOERROR	ksz151.ar.wroc.pl
NOERROR	wyd31.ar.wroc.pl
NXDOMAIN	ksz165.ar.wroc.pl
NOERROR	budg229.ar.wroc.pl
NOERROR	komp46.hod.ar.wroc.pl
NOERROR	ekono-82.ar.wroc.pl
NOERROR	buch216.ar.wroc.pl
NXDOMAIN	klin124.ar.wroc.pl
NOERROR	budg250.ar.wroc.pl
NOERROR	gen89.hod.ar.wroc.pl
NOERROR	komp249.hod.ar.wroc.pl
NOERROR	kiis.ar.wroc.pl
NOERROR	imr130.mech.ar.wroc.pl
NOERROR	ekono-110.ar.wroc.pl
NOERROR	budg133.ar.wroc.pl
NOERROR	imr68.mech.ar.wroc.pl
NOERROR	ksz147.ar.wroc.pl
NOERROR	imr71.mech.ar.wroc.pl
NOERROR	imr181.mech.ar.wroc.pl
NOERROR	wyd45.ar.wroc.pl
NOERROR	budg174.ar.wroc.pl
NOERROR	komp178.hod.ar.wroc.pl
NOERROR	dhcp88.mel.ar.wroc.pl
NXDOMAIN	wydawnictwo.ar.wroc.pl
NOERROR	mat.ar.wroc.pl
NOERROR	imr38.mech.ar.wroc.pl
NOERROR	imr111.mech.ar.wroc.pl
NOERROR	imr5.mech.ar.wroc.pl
NOERROR	dhcp161.mel.ar.wroc.pl
NOERROR	komp180.hod.ar.wroc.pl
NOERROR	ada2.ar.wroc.pl
NOERROR	imr50.mech.ar.wroc.pl
NOERROR	ksz141.ar.wroc.pl
NOERROR	komp42.hod.ar.wroc.pl
NOERROR	dhcp173.mel.ar.wroc.pl
NOERROR	komp41.hod.ar.wroc.pl
NOERROR	imr148.mech.ar.wroc.pl
NOERROR	ekono-77.ar.wroc.pl
NOERROR	imr136.mech.ar.wroc.pl
NOERROR	sw3h.hod.ar.wroc.pl
NOERROR	dorota.hod.ar.wroc.pl
NXDOMAIN	klin104.ar.wroc.pl
NOERROR	dhcp158.mel.ar.wroc.pl
NOERROR	imr105.mech.ar.wroc.pl
NOERROR	ekono-96.ar.wroc.pl
NOERROR	gen132.hod.ar.wroc.pl
NXDOMAIN	c0.aqua.ar.wroc.pl
NOERROR	ksz135.ar.wroc.pl
NOERROR	dhcp206.mel.ar.wroc.pl
NOERROR	komp04.cadlab.ar.wroc.pl
NOERROR	imr19.mech.ar.wroc.pl
NOERROR	dhcp140.mel.ar.wroc.pl
NOERROR	imr143.mech.ar.wroc.pl
NOERROR	komp221.hod.ar.wroc.pl
NOERROR	ksz215.ar.wroc.pl
NOERROR	ada40.ar.wroc.pl
NOERROR	comcad.ar.wroc.pl
NOERROR	budg199.ar.wroc.pl
NOERROR	imr89.mech.ar.wroc.pl
NOERROR	gen87.hod.ar.wroc.pl
NOERROR	apar236.ar.wroc.pl
NOERROR	gen149.hod.ar.wroc.pl
NOERROR	komp203.hod.ar.wroc.pl
NOERROR	dhcp171.mel.ar.wroc.pl
NOERROR	dhcp209.mel.ar.wroc.pl
NXDOMAIN	klin122.ar.wroc.pl
NOERROR	ada50.ar.wroc.pl
NOERROR	buch210.ar.wroc.pl
NOERROR	wyd41.ar.wroc.pl
NOERROR	komp204.hod.ar.wroc.pl
NOERROR	komp185.hod.ar.wroc.pl
NXDOMAIN	sheep.ar.wroc.pl
NXDOMAIN	krych.ar.wroc.pl
NOERROR	dhcp168.mel.ar.wroc.pl
NOERROR	sw2.mech.ar.wroc.pl
NOERROR	imr37.mech.ar.wroc.pl
NOERROR	gen145.hod.ar.wroc.pl
NOERROR	sw3.mel.ar.wroc.pl
NOERROR	dhcp130.mel.ar.wroc.pl
NOERROR	bos122.hod.ar.wroc.pl
NOERROR	dhcp207.mel.ar.wroc.pl
NOERROR	komp226.hod.ar.wroc.pl
NOERROR	dhcp117.mel.ar.wroc.pl
NOERROR	dhcp108.mel.ar.wroc.pl
NXDOMAIN	klin110.ar.wroc.pl
NOERROR	bos121.hod.ar.wroc.pl
NOERROR	komp241.hod.ar.wroc.pl
NOERROR	ada5.ar.wroc.pl
NOERROR	dhcp226.mel.ar.wroc.pl
NXDOMAIN	klin125.ar.wroc.pl
NOERROR	imr201.mech.ar.wroc.pl
NOERROR	budg173.ar.wroc.pl
NOERROR	dhcp203.mel.ar.wroc.pl
NOERROR	bos124.hod.ar.wroc.pl
NOERROR	dhcp152.mel.ar.wroc.pl
NOERROR	ada1.ar.wroc.pl
NOERROR	budg155.ar.wroc.pl
NOERROR	budg139.ar.wroc.pl
NOERROR	komp229.hod.ar.wroc.pl
NOERROR	komp38.hod.ar.wroc.pl
NOERROR	budg135.ar.wroc.pl
NOERROR	imr25.mech.ar.wroc.pl
NOERROR	ada10.ar.wroc.pl
NXDOMAIN	ozi.ar.wroc.pl
NOERROR	imel.mel.ar.wroc.pl
NOERROR	imr202.mech.ar.wroc.pl
NOERROR	budg190.ar.wroc.pl
NOERROR	ada42.ar.wroc.pl
NOERROR	dhcp125.mel.ar.wroc.pl
NXDOMAIN	www.bibl.ar.wroc.pl
NOERROR	dhcp225.mel.ar.wroc.pl
NXDOMAIN	c1.aqua.ar.wroc.pl
NXDOMAIN	www.geo.ar.wroc.pl
NOERROR	dhcp98.mel.ar.wroc.pl
NOERROR	komp210.hod.ar.wroc.pl
NOERROR	wyd36.ar.wroc.pl
NOERROR	wyd58.ar.wroc.pl
NOERROR	komp163.hod.ar.wroc.pl
NOERROR	budg194.ar.wroc.pl
NOERROR	gen80.hod.ar.wroc.pl
NOERROR	imr217.mech.ar.wroc.pl
NOERROR	wyd17.ar.wroc.pl
NOERROR	komp05.cadlab.ar.wroc.pl
NOERROR	dhcp128.mel.ar.wroc.pl
NOERROR	apar233.ar.wroc.pl
NOERROR	budg242.ar.wroc.pl
NOERROR	imr98.mech.ar.wroc.pl
NOERROR	budg148.ar.wroc.pl
NOERROR	ksz183.ar.wroc.pl
NOERROR	budg230.ar.wroc.pl
NOERROR	dhcp123.mel.ar.wroc.pl
NOERROR	apar243.ar.wroc.pl
NOERROR	wyd40.ar.wroc.pl
NOERROR	buch200.ar.wroc.pl
NOERROR	wyd59.ar.wroc.pl
NOERROR	budg179.ar.wroc.pl
NOERROR	komp173.hod.ar.wroc.pl
NOERROR	dhcp179.mel.ar.wroc.pl
NOERROR	dhcp174.mel.ar.wroc.pl
NXDOMAIN	klin81.ar.wroc.pl
NOERROR	ksz175.ar.wroc.pl
NOERROR	apar249.ar.wroc.pl
NOERROR	imr154.mech.ar.wroc.pl
NOERROR	imr24.mech.ar.wroc.pl
NOERROR	bos119.hod.ar.wroc.pl
NOERROR	imr95.mech.ar.wroc.pl
NOERROR	imr117.mech.ar.wroc.pl
NOERROR	ksz171.ar.wroc.pl
NOERROR	imr112.mech.ar.wroc.pl
NOERROR	dhcp154.mel.ar.wroc.pl
NOERROR	ksz194.ar.wroc.pl
NOERROR	budg164.ar.wroc.pl
NOERROR	komp249.mel.ar.wroc.pl
NOERROR	wyd38.ar.wroc.pl
NOERROR	ekono-69.ar.wroc.pl
NOERROR	dhcp102.mel.ar.wroc.pl
NXDOMAIN	aquarius.aqua.ar.wroc.pl
NOERROR	dhcp133.mel.ar.wroc.pl
NOERROR	imr106.mech.ar.wroc.pl
NOERROR	wyd55.ar.wroc.pl
NOERROR	bos123.hod.ar.wroc.pl
NOERROR	imr159.mech.ar.wroc.pl
NOERROR	jurek.hod.ar.wroc.pl
NOERROR	imr31.mech.ar.wroc.pl
NOERROR	komp222.hod.ar.wroc.pl
NOERROR	budg203.ar.wroc.pl
NXDOMAIN	c2.aqua.ar.wroc.pl
NOERROR	apar239.ar.wroc.pl
NOERROR	komp225.hod.ar.wroc.pl
NOERROR	imr41.mech.ar.wroc.pl
NOERROR	budg151.ar.wroc.pl
NXDOMAIN	bgar.ar.wroc.pl
NOERROR	komp254.hod.ar.wroc.pl
NOERROR	ada4.ar.wroc.pl
NOERROR	sw4.mel.ar.wroc.pl
NOERROR	budg149.ar.wroc.pl
NOERROR	imr128.mech.ar.wroc.pl
NOERROR	gen153.hod.ar.wroc.pl
NOERROR	imr129.mech.ar.wroc.pl
NOERROR	budg163.ar.wroc.pl
NOERROR	imr59.mech.ar.wroc.pl
NOERROR	ksz143.ar.wroc.pl
NOERROR	imr134.mech.ar.wroc.pl
NOERROR	komp26.cadlab.ar.wroc.pl
NOERROR	komp171.hod.ar.wroc.pl
NOERROR	ekono-87.ar.wroc.pl
NOERROR	imr211.mech.ar.wroc.pl
NOERROR	imr69.mech.ar.wroc.pl
NOERROR	ksz137.ar.wroc.pl
NOERROR	komp24.cadlab.ar.wroc.pl
NOERROR	budg245.ar.wroc.pl
NOERROR	komp23.cadlab.ar.wroc.pl
NOERROR	imr43.mech.ar.wroc.pl
NOERROR	budg241.ar.wroc.pl
NOERROR	gen148.hod.ar.wroc.pl
NOERROR	ada27.ar.wroc.pl
NOERROR	budg185.ar.wroc.pl
NOERROR	gen136.hod.ar.wroc.pl
NOERROR	imr221.mech.ar.wroc.pl
NOERROR	budg214.ar.wroc.pl
NOERROR	dhcp178.mel.ar.wroc.pl
NOERROR	dhcp110.mel.ar.wroc.pl
NOERROR	dhcp199.mel.ar.wroc.pl
NOERROR	gen71.hod.ar.wroc.pl
NXDOMAIN	klin113.ar.wroc.pl
NOERROR	ada6.ar.wroc.pl
NXDOMAIN	klin71.ar.wroc.pl
NXDOMAIN	bib6.bibl.ar.wroc.pl
NOERROR	gen144.hod.ar.wroc.pl
NOERROR	budg211.ar.wroc.pl
NOERROR	ekono-105.ar.wroc.pl
NOERROR	imr102.mech.ar.wroc.pl
NOERROR	ksz197.ar.wroc.pl
NOERROR	budg168.ar.wroc.pl
NOERROR	ada31.ar.wroc.pl
NXDOMAIN	klin100.ar.wroc.pl
NOERROR	goska.hod.ar.wroc.pl
NOERROR	ada24.ar.wroc.pl
NOERROR	imr100.mech.ar.wroc.pl
NOERROR	imr70.mech.ar.wroc.pl
NOERROR	imr149.mech.ar.wroc.pl
NOERROR	budg156.ar.wroc.pl
NOERROR	imr84.mech.ar.wroc.pl
NOERROR	imr39.mech.ar.wroc.pl
NOERROR	woj-prac.hod.ar.wroc.pl
NOERROR	imr48.mech.ar.wroc.pl
NXDOMAIN	cab.bibl.ar.wroc.pl
NOERROR	ksz154.ar.wroc.pl
NOERROR	imr114.mech.ar.wroc.pl
NOERROR	imr49.mech.ar.wroc.pl
NOERROR	dhcp194.mel.ar.wroc.pl
NOERROR	gen133.hod.ar.wroc.pl
NOERROR	dhcp220.mel.ar.wroc.pl
NOERROR	komp187.hod.ar.wroc.pl
NOERROR	gen72.hod.ar.wroc.pl
NOERROR	budg225.ar.wroc.pl
NOERROR	komp14.cadlab.ar.wroc.pl
NOERROR	budg197.ar.wroc.pl
NOERROR	scx4720.mel.ar.wroc.pl
NOERROR	dhcp90.mel.ar.wroc.pl
NOERROR	ksz179.ar.wroc.pl
NOERROR	dhcp201.mel.ar.wroc.pl
NOERROR	komp217.hod.ar.wroc.pl
NOERROR	ekono-91.ar.wroc.pl
NXDOMAIN	aleph.bibl.ar.wroc.pl
NOERROR	ekono-68.ar.wroc.pl
NOERROR	wyd60.ar.wroc.pl
NOERROR	ksz159.ar.wroc.pl
NOERROR	geringer.hod.ar.wroc.pl
NOERROR	komp239.hod.ar.wroc.pl
NOERROR	dhcp132.mel.ar.wroc.pl
NOERROR	budg172.ar.wroc.pl
NOERROR	budg206.ar.wroc.pl
NOERROR	budg147.ar.wroc.pl
NOERROR	imr119.mech.ar.wroc.pl
NOERROR	dhcp135.mel.ar.wroc.pl
NOERROR	imr6.mech.ar.wroc.pl
NOERROR	ekono-95.ar.wroc.pl
NOERROR	dhcp118.mel.ar.wroc.pl
NOERROR	imr87.mech.ar.wroc.pl
NOERROR	imr203.mech.ar.wroc.pl
NOERROR	dhcp198.mel.ar.wroc.pl
NOERROR	komp167.hod.ar.wroc.pl
NOERROR	ksz178.ar.wroc.pl
NOERROR	komp227.hod.ar.wroc.pl
NOERROR	ekono-119.ar.wroc.pl
NOERROR	komp52.hod.ar.wroc.pl
NOERROR	sw6.mel.ar.wroc.pl
NOERROR	komp231.mel.ar.wroc.pl
NXDOMAIN	www.iaeste.ar.wroc.pl
NOERROR	kompb5.hod.ar.wroc.pl
NOERROR	budg180.ar.wroc.pl
NOERROR	ksz186.ar.wroc.pl
NXDOMAIN	klin78.ar.wroc.pl
NXDOMAIN	cwik.ar.wroc.pl
NOERROR	komp10.cadlab.ar.wroc.pl
NOERROR	ksz218.ar.wroc.pl
NOERROR	imr156.mech.ar.wroc.pl
NOERROR	budg170.ar.wroc.pl
NOERROR	bos118.hod.ar.wroc.pl
NOERROR	gen151.hod.ar.wroc.pl
NOERROR	imr47.mech.ar.wroc.pl
NXDOMAIN	klin83.ar.wroc.pl
NOERROR	komp168.hod.ar.wroc.pl
NXDOMAIN	klin116.ar.wroc.pl
NOERROR	komp20.cadlab.ar.wroc.pl
NOERROR	ekono-97.ar.wroc.pl
NOERROR	komp245.hod.ar.wroc.pl
NOERROR	komp08.cadlab.ar.wroc.pl
NXDOMAIN	www.jedliniok.ar.wroc.pl
NOERROR	ada3.ar.wroc.pl
NOERROR	ekono-74.ar.wroc.pl
NOERROR	ksz155.ar.wroc.pl
NOERROR	dhcp139.mel.ar.wroc.pl
NOERROR	budg191.ar.wroc.pl
NOERROR	komp235.mel.ar.wroc.pl
NOERROR	budg217.ar.wroc.pl
NOERROR	wyd50.ar.wroc.pl
NOERROR	budg157.ar.wroc.pl
NOERROR	dhcp187.mel.ar.wroc.pl
NOERROR	miks.ar.wroc.pl
NOERROR	wyd18.ar.wroc.pl
NOERROR	imr35.mech.ar.wroc.pl
NOERROR	komp25.cadlab.ar.wroc.pl
NOERROR	budg218.ar.wroc.pl
NOERROR	dhcp156.mel.ar.wroc.pl
NOERROR	komp02.cadlab.ar.wroc.pl
NOERROR	dhcp224.mel.ar.wroc.pl
NOERROR	imr57.mech.ar.wroc.pl
NOERROR	imr51.mech.ar.wroc.pl
NOERROR	imr2.mech.ar.wroc.pl
NOERROR	dhcp116.mel.ar.wroc.pl
NOERROR	komp177.hod.ar.wroc.pl
NOERROR	dhcp215.mel.ar.wroc.pl
NOERROR	komp16.cadlab.ar.wroc.pl
NOERROR	dhcp181.mel.ar.wroc.pl
NOERROR	komp181.hod.ar.wroc.pl
NOERROR	imr21.mech.ar.wroc.pl
NOERROR	komp01.cadlab.ar.wroc.pl
NOERROR	imr36.mech.ar.wroc.pl
NOERROR	ksz152.ar.wroc.pl
NOERROR	wyd51.ar.wroc.pl
NOERROR	buch215.ar.wroc.pl
NOERROR	komp236.hod.ar.wroc.pl
NXDOMAIN	klin94.ar.wroc.pl
NOERROR	imr229.mech.ar.wroc.pl
NXDOMAIN	klin117.ar.wroc.pl
NOERROR	apar254.ar.wroc.pl
NOERROR	ada38.ar.wroc.pl
NOERROR	router.mel.ar.wroc.pl
NOERROR	sw4.mech.ar.wroc.pl
NOERROR	imr180.mech.ar.wroc.pl
NOERROR	komp07.cadlab.ar.wroc.pl
NOERROR	imr224.mech.ar.wroc.pl
NOERROR	wyd53.ar.wroc.pl
NOERROR	budg237.ar.wroc.pl
NOERROR	ada30.ar.wroc.pl
NOERROR	komp165.hod.ar.wroc.pl
NOERROR	dhcp120.mel.ar.wroc.pl
NOERROR	apar247.ar.wroc.pl
NOERROR	imr88.mech.ar.wroc.pl
NOERROR	wyd39.ar.wroc.pl
NOERROR	imr228.mech.ar.wroc.pl
NOERROR	dhcp155.mel.ar.wroc.pl
NOERROR	ekono-118.ar.wroc.pl
NXDOMAIN	karnet.ar.wroc.pl
NOERROR	ekono-117.ar.wroc.pl
NOERROR	wyd34.ar.wroc.pl
NOERROR	komp183.hod.ar.wroc.pl
NOERROR	komp189.hod.ar.wroc.pl
NOERROR	komp162.hod.ar.wroc.pl
NOERROR	dhcp214.mel.ar.wroc.pl
NOERROR	budg227.ar.wroc.pl
NOERROR	budg240.ar.wroc.pl
NOERROR	dhcp111.mel.ar.wroc.pl
NOERROR	gen69.hod.ar.wroc.pl
NOERROR	imr9.mech.ar.wroc.pl
NOERROR	komp44.hod.ar.wroc.pl
NOERROR	dhcp165.mel.ar.wroc.pl
NOERROR	ksz133.ar.wroc.pl
NOERROR	imr73.mech.ar.wroc.pl
NOERROR	komp03.cadlab.ar.wroc.pl
NOERROR	imr23.mech.ar.wroc.pl
NOERROR	ekono-111.ar.wroc.pl
NOERROR	ekono-88.ar.wroc.pl
NOERROR	komp39.hod.ar.wroc.pl
NOERROR	imr198.mech.ar.wroc.pl
NOERROR	budg223.ar.wroc.pl
NOERROR	imr205.mech.ar.wroc.pl
NOERROR	komp199.hod.ar.wroc.pl
NOERROR	buch206.ar.wroc.pl
NOERROR	ksz162.ar.wroc.pl
NOERROR	imr123.mech.ar.wroc.pl
NXDOMAIN	www.ar.wroc.pl
NOERROR	dhcp175.mel.ar.wroc.pl
NOERROR	dhcp176.mel.ar.wroc.pl
NXDOMAIN	bip.ar.wroc.pl
NXDOMAIN	klin90.ar.wroc.pl
NOERROR	komp234.mel.ar.wroc.pl
NXDOMAIN	wyd54.ar.wroc.pl
NOERROR	wyd12.ar.wroc.pl
NOERROR	imr78.mech.ar.wroc.pl
NOERROR	imr150.mech.ar.wroc.pl
NOERROR	hydra.ar.wroc.pl
NXDOMAIN	klin89.ar.wroc.pl
NOERROR	imr103.mech.ar.wroc.pl
NOERROR	apar237.ar.wroc.pl
NOERROR	dhcp126.mel.ar.wroc.pl
NOERROR	ksz176.ar.wroc.pl
NOERROR	dhcp162.mel.ar.wroc.pl
NXDOMAIN	smok.ar.wroc.pl
NOERROR	ksz173.ar.wroc.pl
NOERROR	ada25.ar.wroc.pl
NOERROR	komp33.hod.ar.wroc.pl
NOERROR	apar253.ar.wroc.pl
NOERROR	budg239.ar.wroc.pl
NOERROR	ekono-115.ar.wroc.pl
NXDOMAIN	www.aqua.ar.wroc.pl
NOERROR	ksz180.ar.wroc.pl
NOERROR	ekono-90.ar.wroc.pl
NOERROR	budg145.ar.wroc.pl
NOERROR	imr213.mech.ar.wroc.pl
NOERROR	gen65.hod.ar.wroc.pl
NOERROR	imr188.mech.ar.wroc.pl
NOERROR	ksz181.ar.wroc.pl
NOERROR	komp247.hod.ar.wroc.pl
NOERROR	ada28.ar.wroc.pl
NOERROR	imr191.mech.ar.wroc.pl
NOERROR	imr173.mech.ar.wroc.pl
NOERROR	budg176.ar.wroc.pl
NOERROR	imr226.mech.ar.wroc.pl
NOERROR	komp193.hod.ar.wroc.pl
NOERROR	ksz185.ar.wroc.pl
NOERROR	imr109.mech.ar.wroc.pl
NOERROR	komp224.hod.ar.wroc.pl
NOERROR	ksz170.ar.wroc.pl
NOERROR	komp246.hod.ar.wroc.pl
NOERROR	komp175.hod.ar.wroc.pl
NOERROR	dhcp100.mel.ar.wroc.pl
NXDOMAIN	kgf.ar.wroc.pl
NOERROR	imr184.mech.ar.wroc.pl
NOERROR	imr3.mech.ar.wroc.pl
NOERROR	dhcp86.mel.ar.wroc.pl
NXDOMAIN	cental.ar.wroc.pl
NOERROR	komp231.hod.ar.wroc.pl
NOERROR	imr91.mech.ar.wroc.pl
NOERROR	ksz201.ar.wroc.pl
NOERROR	ksz172.ar.wroc.pl
NXDOMAIN	klin72.ar.wroc.pl
NOERROR	komp214.hod.ar.wroc.pl
NXDOMAIN	klin69.ar.wroc.pl
NOERROR	imr178.mech.ar.wroc.pl
NOERROR	ksz221.ar.wroc.pl
NXDOMAIN	sopocka.ar.wroc.pl
NOERROR	wyd15.ar.wroc.pl
NOERROR	imr1.mech.ar.wroc.pl
NOERROR	imr186.mech.ar.wroc.pl
NOERROR	komp243.hod.ar.wroc.pl
NXDOMAIN	microscopy.ar.wroc.pl
NOERROR	bz.hod.ar.wroc.pl
NOERROR	imr133.mech.ar.wroc.pl
NOERROR	imr126.mech.ar.wroc.pl
NOERROR	ekono-80.ar.wroc.pl
NOERROR	ksz210.ar.wroc.pl
NOERROR	gen137.hod.ar.wroc.pl
NOERROR	budg219.ar.wroc.pl
NOERROR	komp194.hod.ar.wroc.pl
NOERROR	gen90.hod.ar.wroc.pl
NOERROR	dhcp172.mel.ar.wroc.pl
NOERROR	ekono-75.ar.wroc.pl
NOERROR	gen73.hod.ar.wroc.pl
NOERROR	dz-biol.hod.ar.wroc.pl
NOERROR	dhcp136.mel.ar.wroc.pl
NOERROR	gen134.hod.ar.wroc.pl
NOERROR	gen129.hod.ar.wroc.pl
NOERROR	imr34.mech.ar.wroc.pl
NOERROR	imr193.mech.ar.wroc.pl
NOERROR	komp233.mel.ar.wroc.pl
NOERROR	imr94.mech.ar.wroc.pl
NOERROR	dhcp190.mel.ar.wroc.pl
NOERROR	komp244.hod.ar.wroc.pl
NOERROR	imr7.mech.ar.wroc.pl
NOERROR	imr26.mech.ar.wroc.pl
NOERROR	ekono-98.ar.wroc.pl
NOERROR	ksz167.ar.wroc.pl
NOERROR	komp230.hod.ar.wroc.pl
NOERROR	dhcp105.mel.ar.wroc.pl
NOERROR	budg253.ar.wroc.pl
NOERROR	dhcp148.mel.ar.wroc.pl
NOERROR	dhcp170.mel.ar.wroc.pl
NXDOMAIN	klin86.ar.wroc.pl
NOERROR	imr46.mech.ar.wroc.pl
NOERROR	ksz144.ar.wroc.pl
NOERROR	dhcp96.mel.ar.wroc.pl
NOERROR	ekono-109.ar.wroc.pl
NOERROR	imr206.mech.ar.wroc.pl
NOERROR	budg186.ar.wroc.pl
NOERROR	komp184.hod.ar.wroc.pl
NOERROR	budg231.ar.wroc.pl
NOERROR	gen78.hod.ar.wroc.pl
NOERROR	sw1h.hod.ar.wroc.pl
NXDOMAIN	c6.aqua.ar.wroc.pl
NOERROR	budg207.ar.wroc.pl
NOERROR	dhcp115.mel.ar.wroc.pl
NOERROR	ekono-123.ar.wroc.pl
NOERROR	budg131.ar.wroc.pl
NOERROR	dhcp164.mel.ar.wroc.pl
NOERROR	imr138.mech.ar.wroc.pl
NXDOMAIN	klin75.ar.wroc.pl
NOERROR	apar242.ar.wroc.pl
NXDOMAIN	komp212.hod.ar.wroc.pl
NOERROR	ekono-83.ar.wroc.pl
NOERROR	gen79.hod.ar.wroc.pl
NOERROR	www.agro.ar.wroc.pl
NOERROR	imr113.mech.ar.wroc.pl
NOERROR	imr54.mech.ar.wroc.pl
NOERROR	ada12.ar.wroc.pl
NOERROR	budg181.ar.wroc.pl
NOERROR	budg248.ar.wroc.pl
NOERROR	wyd48.ar.wroc.pl
NOERROR	budg178.ar.wroc.pl
NOERROR	komp188.hod.ar.wroc.pl
NOERROR	komp34.hod.ar.wroc.pl
NOERROR	komp201.hod.ar.wroc.pl
NOERROR	ksz213.ar.wroc.pl
NOERROR	imr141.mech.ar.wroc.pl
NOERROR	imr165.mech.ar.wroc.pl
NOERROR	imr183.mech.ar.wroc.pl
NOERROR	dhcp227.mel.ar.wroc.pl
NOERROR	ada56.ar.wroc.pl
NOERROR	gen131.hod.ar.wroc.pl
NOERROR	ekono-76.ar.wroc.pl
NOERROR	gen84.hod.ar.wroc.pl
NOERROR	imr42.mech.ar.wroc.pl
NOERROR	komp11.cadlab.ar.wroc.pl
NXDOMAIN	chmurka.ar.wroc.pl
NOERROR	ekono-121.ar.wroc.pl
NOERROR	komp202.hod.ar.wroc.pl
NOERROR	dhcp113.mel.ar.wroc.pl
NOERROR	ada16.ar.wroc.pl
NOERROR	gen147.hod.ar.wroc.pl
NXDOMAIN	klin95.ar.wroc.pl
NOERROR	dhcp142.mel.ar.wroc.pl
NOERROR	imr212.mech.ar.wroc.pl
NOERROR	budg162.ar.wroc.pl
NXDOMAIN	klin123.ar.wroc.pl
NOERROR	imr146.mech.ar.wroc.pl
NOERROR	wyd47.ar.wroc.pl
NOERROR	ekono-78.ar.wroc.pl
NOERROR	ksz220.ar.wroc.pl
NOERROR	komp207.hod.ar.wroc.pl
NOERROR	ekono-72.ar.wroc.pl
NOERROR	dhcp127.mel.ar.wroc.pl
NXDOMAIN	klin118.ar.wroc.pl
NOERROR	imr166.mech.ar.wroc.pl
NOERROR	budg209.ar.wroc.pl
NOERROR	ksz158.ar.wroc.pl
NOERROR	gen140.hod.ar.wroc.pl
NOERROR	dhcp217.mel.ar.wroc.pl
NOERROR	ekono-116.ar.wroc.pl
NOERROR	imr177.mech.ar.wroc.pl
NOERROR	budg166.ar.wroc.pl
NOERROR	budg212.ar.wroc.pl
NOERROR	wyd42.ar.wroc.pl
NOERROR	ksz153.ar.wroc.pl
NOERROR	ekono-99.ar.wroc.pl
NOERROR	ksz202.ar.wroc.pl
NOERROR	imr97.mech.ar.wroc.pl
NOERROR	apar228.ar.wroc.pl
NOERROR	imr197.mech.ar.wroc.pl
NOERROR	buch196.ar.wroc.pl
NOERROR	ada18.ar.wroc.pl
NOERROR	ekono-125.ar.wroc.pl
NOERROR	budg169.ar.wroc.pl
NOERROR	wyd16.ar.wroc.pl
NOERROR	komp172.hod.ar.wroc.pl
NOERROR	komp18.cadlab.ar.wroc.pl
NOERROR	imr199.mech.ar.wroc.pl
NOERROR	ksz163.ar.wroc.pl
NOERROR	ksz136.ar.wroc.pl
NOERROR	ada58.ar.wroc.pl
NOERROR	imr56.mech.ar.wroc.pl
NOERROR	imr139.mech.ar.wroc.pl
NOERROR	ekono-114.ar.wroc.pl
NOERROR	gen146.hod.ar.wroc.pl
NOERROR	komp237.hod.ar.wroc.pl
NOERROR	dhcp182.mel.ar.wroc.pl
NOERROR	komp196.hod.ar.wroc.pl
NOERROR	ekono-65.ar.wroc.pl
NOERROR	imr190.mech.ar.wroc.pl
NOERROR	ada45.ar.wroc.pl
NOERROR	wyd11.ar.wroc.pl
NOERROR	ada15.ar.wroc.pl
NOERROR	ada29.ar.wroc.pl
NOERROR	dhcp147.mel.ar.wroc.pl
NOERROR	ada43.ar.wroc.pl
NXDOMAIN	klin102.ar.wroc.pl
NOERROR	komp253.hod.ar.wroc.pl
NOERROR	bos101.hod.ar.wroc.pl
NOERROR	wyd37.ar.wroc.pl
NOERROR	budg238.ar.wroc.pl
NOERROR	ada22.ar.wroc.pl
NOERROR	komp213.hod.ar.wroc.pl
NOERROR	dhcp197.mel.ar.wroc.pl
NOERROR	dhcp219.mel.ar.wroc.pl
NOERROR	imr163.mech.ar.wroc.pl
NOERROR	imr174.mech.ar.wroc.pl
NOERROR	budg244.ar.wroc.pl
NOERROR	ksz219.ar.wroc.pl
NOERROR	komp15.cadlab.ar.wroc.pl
NOERROR	imr14.mech.ar.wroc.pl
NXDOMAIN	klin85.ar.wroc.pl
NOERROR	wyd9.ar.wroc.pl
NOERROR	dhcp184.mel.ar.wroc.pl
NOERROR	wyd32.ar.wroc.pl
NOERROR	ada11.ar.wroc.pl
NOERROR	dhcp94.mel.ar.wroc.pl
NOERROR	komp182.hod.ar.wroc.pl
NOERROR	budg193.ar.wroc.pl
NOERROR	ekono-100.ar.wroc.pl
NOERROR	imr175.mech.ar.wroc.pl
NOERROR	dhcp200.mel.ar.wroc.pl
NOERROR	imr90.mech.ar.wroc.pl
NOERROR	imr158.mech.ar.wroc.pl
NOERROR	imr67.mech.ar.wroc.pl
NOERROR	ada32.ar.wroc.pl
NOERROR	bg.ar.wroc.pl
NOERROR	gen130.hod.ar.wroc.pl
NOERROR	budg232.ar.wroc.pl
NOERROR	apar244.ar.wroc.pl
NOERROR	gen88.hod.ar.wroc.pl
NOERROR	ksz157.ar.wroc.pl
NOERROR	ksz222.ar.wroc.pl
NXDOMAIN	vetina.ar.wroc.pl
NOERROR	budg205.ar.wroc.pl
NOERROR	apar232.ar.wroc.pl
NOERROR	imr137.mech.ar.wroc.pl
NOERROR	ada60.ar.wroc.pl
NOERROR	dhcp210.mel.ar.wroc.pl
NOERROR	dragan.hod.ar.wroc.pl
NOERROR	wyd23.ar.wroc.pl
NOERROR	ada37.ar.wroc.pl
NOERROR	ekono-85.ar.wroc.pl
NOERROR	gen83.hod.ar.wroc.pl
NOERROR	sw5h.hod.ar.wroc.pl
NOERROR	imr13.mech.ar.wroc.pl
NOERROR	dhcp112.mel.ar.wroc.pl
NOERROR	wyd33.ar.wroc.pl
NOERROR	ada17.ar.wroc.pl
NOERROR	buch207.ar.wroc.pl
NXDOMAIN	x2.aqua.ar.wroc.pl
NOERROR	imr120.mech.ar.wroc.pl
NOERROR	ib.hod.ar.wroc.pl
NOERROR	komp161.hod.ar.wroc.pl
NOERROR	dhcp202.mel.ar.wroc.pl
NOERROR	budg129.ar.wroc.pl
NXDOMAIN	pluton.ar.wroc.pl
NXDOMAIN	klin101.ar.wroc.pl
NOERROR	imr223.mech.ar.wroc.pl
NOERROR	ekono-122.ar.wroc.pl
NOERROR	buch198.ar.wroc.pl
NOERROR	imr40.mech.ar.wroc.pl
NXDOMAIN	x3.aqua.ar.wroc.pl
NOERROR	gen85.hod.ar.wroc.pl
NOERROR	gen70.hod.ar.wroc.pl
NOERROR	komp206.hod.ar.wroc.pl
NOERROR	wyd7.ar.wroc.pl
NOERROR	apar229.ar.wroc.pl
NOERROR	imr108.mech.ar.wroc.pl
NOERROR	ekono-73.ar.wroc.pl
NOERROR	imr18.mech.ar.wroc.pl
NOERROR	budg213.ar.wroc.pl
NXDOMAIN	klin79.ar.wroc.pl
NOERROR	komp179.hod.ar.wroc.pl
NOERROR	budg130.ar.wroc.pl
NOERROR	dhcp204.mel.ar.wroc.pl
NOERROR	budg210.ar.wroc.pl
NOERROR	apar227.ar.wroc.pl
NOERROR	budg202.ar.wroc.pl
NOERROR	ksz168.ar.wroc.pl
NOERROR	ksz184.ar.wroc.pl
NOERROR	imr187.mech.ar.wroc.pl
NOERROR	ksz214.ar.wroc.pl
NOERROR	imr164.mech.ar.wroc.pl
NOERROR	imr92.mech.ar.wroc.pl
NOERROR	wyd14.ar.wroc.pl
NOERROR	ada52.ar.wroc.pl
NOERROR	gen135.hod.ar.wroc.pl
NOERROR	imr20.mech.ar.wroc.pl
NOERROR	imr144.mech.ar.wroc.pl
NOERROR	ada55.ar.wroc.pl
NOERROR	wyd44.ar.wroc.pl
NOERROR	budg195.ar.wroc.pl
NOERROR	dhcp221.mel.ar.wroc.pl
NXDOMAIN	klin115.ar.wroc.pl
NXDOMAIN	ekono-126.ar.wroc.pl
NOERROR	imr131.mech.ar.wroc.pl
NOERROR	imr107.mech.ar.wroc.pl
NOERROR	wyd19.ar.wroc.pl
NOERROR	budg136.ar.wroc.pl
NOERROR	budg138.ar.wroc.pl
NOERROR	imr230.mech.ar.wroc.pl
NXDOMAIN	klin106.ar.wroc.pl
NOERROR	komp32.cadlab.ar.wroc.pl
NOERROR	ada35.ar.wroc.pl
NOERROR	ekono-113.ar.wroc.pl
NOERROR	dhcp92.mel.ar.wroc.pl
NOERROR	dhcp109.mel.ar.wroc.pl
NOERROR	ksz148.ar.wroc.pl
NOERROR	komp53.hod.ar.wroc.pl
NOERROR	sw5.mech.ar.wroc.pl
NXDOMAIN	zoology.ar.wroc.pl
NOERROR	imr125.mech.ar.wroc.pl
NOERROR	imr209.mech.ar.wroc.pl
NOERROR	apar250.ar.wroc.pl
NOERROR	buch217.ar.wroc.pl
NXDOMAIN	twardon.ar.wroc.pl
NOERROR	ada49.ar.wroc.pl
NOERROR	imr204.mech.ar.wroc.pl
NOERROR	ksz209.ar.wroc.pl
NOERROR	budg160.ar.wroc.pl
NOERROR	imr77.mech.ar.wroc.pl
NOERROR	apar230.ar.wroc.pl
NOERROR	imr72.mech.ar.wroc.pl
NXDOMAIN	komp190.hod.ar.wroc.pl
NOERROR	imr121.mech.ar.wroc.pl
NOERROR	ada36.ar.wroc.pl
NOERROR	ekono-102.ar.wroc.pl
NOERROR	ksz205.ar.wroc.pl
NOERROR	budg254.ar.wroc.pl
NOERROR	imr208.mech.ar.wroc.pl
NOERROR	sw6.mech.ar.wroc.pl
NOERROR	apar251.ar.wroc.pl
NOERROR	ksz149.ar.wroc.pl
NOERROR	apar234.ar.wroc.pl
NOERROR	dhcp159.mel.ar.wroc.pl
NOERROR	imr147.mech.ar.wroc.pl
NOERROR	bos110.hod.ar.wroc.pl
NOERROR	imr132.mech.ar.wroc.pl
NOERROR	budg220.ar.wroc.pl
NOERROR	ksz140.ar.wroc.pl
NOERROR	komp216.hod.ar.wroc.pl
NOERROR	ada53.ar.wroc.pl
NOERROR	gen74.hod.ar.wroc.pl
NOERROR	ada14.ar.wroc.pl
NOERROR	sw3.mech.ar.wroc.pl
NOERROR	wyd24.ar.wroc.pl
NOERROR	imr104.mech.ar.wroc.pl
NOERROR	komp09.cadlab.ar.wroc.pl
NOERROR	gen67.hod.ar.wroc.pl
NOERROR	wyd52.ar.wroc.pl
NOERROR	komp209.hod.ar.wroc.pl
NOERROR	imr8.mech.ar.wroc.pl
NOERROR	imr28.mech.ar.wroc.pl
NOERROR	dhcp163.mel.ar.wroc.pl
NXDOMAIN	klin77.ar.wroc.pl
NOERROR	apar248.ar.wroc.pl
NOERROR	imr169.mech.ar.wroc.pl
NOERROR	sw7.mel.ar.wroc.pl
NOERROR	budg208.ar.wroc.pl
NOERROR	buch222.ar.wroc.pl
NOERROR	budg137.ar.wroc.pl
NOERROR	dhcp129.mel.ar.wroc.pl
NOERROR	dhcp205.mel.ar.wroc.pl
NOERROR	dhcp177.mel.ar.wroc.pl
NOERROR	komp238.hod.ar.wroc.pl
NOERROR	imr93.mech.ar.wroc.pl
NOERROR	gen77.hod.ar.wroc.pl
NOERROR	imr189.mech.ar.wroc.pl
NOERROR	budg215.ar.wroc.pl
NOERROR	imr110.mech.ar.wroc.pl
NOERROR	wyd43.ar.wroc.pl
NOERROR	sw2h.hod.ar.wroc.pl
NXDOMAIN	wnoz.ar.wroc.pl
NOERROR	dhcp145.mel.ar.wroc.pl
NOERROR	imr99.mech.ar.wroc.pl
NOERROR	budg175.ar.wroc.pl
NOERROR	budg146.ar.wroc.pl
NOERROR	dhcp169.mel.ar.wroc.pl
NOERROR	ada51.ar.wroc.pl
NOERROR	komp220.hod.ar.wroc.pl
NOERROR	wyd26.ar.wroc.pl
NOERROR	ksz189.ar.wroc.pl
NXDOMAIN	zoo.ar.wroc.pl
NOERROR	imr12.mech.ar.wroc.pl
NOERROR	budg152.ar.wroc.pl
NOERROR	budg216.ar.wroc.pl
NOERROR	imr80.mech.ar.wroc.pl
NOERROR	budg167.ar.wroc.pl
NOERROR	dhcp222.mel.ar.wroc.pl
NOERROR	budg134.ar.wroc.pl
NXDOMAIN	klin84.ar.wroc.pl
NOERROR	dhcp149.mel.ar.wroc.pl
NOERROR	dhcp218.mel.ar.wroc.pl
NOERROR	wyd13.ar.wroc.pl
NOERROR	budg192.ar.wroc.pl
NOERROR	ksz169.ar.wroc.pl
NOERROR	imr11.mech.ar.wroc.pl
NOERROR	ksz177.ar.wroc.pl
NOERROR	budg189.ar.wroc.pl
NOERROR	dhcp89.mel.ar.wroc.pl
NOERROR	ksz174.ar.wroc.pl
NOERROR	dhcp138.mel.ar.wroc.pl
NOERROR	komp45.hod.ar.wroc.pl
NOERROR	imr124.mech.ar.wroc.pl
NOERROR	ekono-103.ar.wroc.pl
NOERROR	ada62.ar.wroc.pl
NOERROR	ada61.ar.wroc.pl
NXDOMAIN	www.iis.ar.wroc.pl
NOERROR	budg200.ar.wroc.pl
NOERROR	wyd57.ar.wroc.pl
NOERROR	dhcp106.mel.ar.wroc.pl
NOERROR	komp33.cadlab.ar.wroc.pl
NOERROR	gen82.hod.ar.wroc.pl
NOERROR	buch219.ar.wroc.pl
NOERROR	bos114.hod.ar.wroc.pl
NOERROR	budg150.ar.wroc.pl
NOERROR	imr76.mech.ar.wroc.pl
NOERROR	imr122.mech.ar.wroc.pl
NOERROR	imr85.mech.ar.wroc.pl
NOERROR	komp40.hod.ar.wroc.pl
NOERROR	buch203.ar.wroc.pl
NOERROR	imr200.mech.ar.wroc.pl
NOERROR	dhcp208.mel.ar.wroc.pl
NOERROR	bos115.hod.ar.wroc.pl
NXDOMAIN	x4.aqua.ar.wroc.pl
NXDOMAIN	klin80.ar.wroc.pl
NOERROR	komp31.cadlab.ar.wroc.pl
NOERROR	budg177.ar.wroc.pl
NOERROR	genova.hod.ar.wroc.pl
NOERROR	dhcp157.mel.ar.wroc.pl
NOERROR	budg243.ar.wroc.pl
NOERROR	buch209.ar.wroc.pl
NOERROR	komp164.hod.ar.wroc.pl
NOERROR	dhcp188.mel.ar.wroc.pl
NOERROR	buch202.ar.wroc.pl
NOERROR	imr101.mech.ar.wroc.pl
NOERROR	imr75.mech.ar.wroc.pl
NOERROR	ksz190.ar.wroc.pl
NOERROR	komp54.hod.ar.wroc.pl
NOERROR	wyd25.ar.wroc.pl
NOERROR	komp113.hod.ar.wroc.pl
NOERROR	ada9.ar.wroc.pl
NXDOMAIN	bib37.bibl.ar.wroc.pl
NOERROR	ekono-94.ar.wroc.pl
NOERROR	imr116.mech.ar.wroc.pl
NOERROR	imr168.mech.ar.wroc.pl
NOERROR	buch197.ar.wroc.pl
NOERROR	dhcp99.mel.ar.wroc.pl
NXDOMAIN	wnoz2.ar.wroc.pl
NOERROR	buch195.ar.wroc.pl
NOERROR	ekono-79.ar.wroc.pl
NOERROR	ada48.ar.wroc.pl
NXDOMAIN	klin97.ar.wroc.pl
NOERROR	ksz134.ar.wroc.pl
NOERROR	gen76.hod.ar.wroc.pl
NOERROR	dhcp87.mel.ar.wroc.pl
NOERROR	dhcp144.mel.ar.wroc.pl
NOERROR	dragan95.hod.ar.wroc.pl
NXDOMAIN	budg184.ar.wroc.pl
NOERROR	imr167.mech.ar.wroc.pl
NOERROR	ksz198.ar.wroc.pl
NOERROR	dhcp228.mel.ar.wroc.pl
NOERROR	komp170.hod.ar.wroc.pl
NOERROR	imr63.mech.ar.wroc.pl
NOERROR	imr60.mech.ar.wroc.pl
NOERROR	budg183.ar.wroc.pl
NXDOMAIN	klin103.ar.wroc.pl
NOERROR	sw1.mech.ar.wroc.pl
NOERROR	ekono-108.ar.wroc.pl
NXDOMAIN	komp246.mel.ar.wroc.pl
NOERROR	ada47.ar.wroc.pl
NOERROR	komp236.mel.ar.wroc.pl
NOERROR	imr10.mech.ar.wroc.pl
NOERROR	ksz195.ar.wroc.pl
NOERROR	ekono-120.ar.wroc.pl
NOERROR	imr185.mech.ar.wroc.pl
NOERROR	budg246.ar.wroc.pl
NOERROR	dhcp191.mel.ar.wroc.pl
NOERROR	imr45.mech.ar.wroc.pl
NOERROR	komp43.hod.ar.wroc.pl
NOERROR	komp251.hod.ar.wroc.pl
NOERROR	buch211.ar.wroc.pl
NOERROR	wyd46.ar.wroc.pl
NOERROR	ksz196.ar.wroc.pl
NOERROR	imr225.mech.ar.wroc.pl
NOERROR	budg222.ar.wroc.pl
NOERROR	wyd49.ar.wroc.pl
NOERROR	ksz164.ar.wroc.pl
NOERROR	budg159.ar.wroc.pl
NOERROR	helios.hod.ar.wroc.pl
NXDOMAIN	klin105.ar.wroc.pl
NXDOMAIN	klin120.ar.wroc.pl
NOERROR	imr55.mech.ar.wroc.pl
NOERROR	komp252.hod.ar.wroc.pl
NOERROR	budg233.ar.wroc.pl
NOERROR	apar240.ar.wroc.pl
NOERROR	komp234.hod.ar.wroc.pl
NOERROR	imr192.mech.ar.wroc.pl
NOERROR	gen86.hod.ar.wroc.pl
NOERROR	ada57.ar.wroc.pl
NOERROR	komp169.hod.ar.wroc.pl
NOERROR	ada21.ar.wroc.pl
NOERROR	drob.hod.ar.wroc.pl
NOERROR	ksz146.ar.wroc.pl
NOERROR	budg235.ar.wroc.pl
NOERROR	budg226.ar.wroc.pl
NOERROR	srv1h.hod.ar.wroc.pl
NOERROR	ekono-84.ar.wroc.pl
NOERROR	komp218.hod.ar.wroc.pl
NXDOMAIN	klin70.ar.wroc.pl
NOERROR	wyd20.ar.wroc.pl
NOERROR	ada8.ar.wroc.pl
NXDOMAIN	klin99.ar.wroc.pl
NOERROR	buch205.ar.wroc.pl
NOERROR	apar226.ar.wroc.pl
NOERROR	imr64.mech.ar.wroc.pl
NOERROR	imr207.mech.ar.wroc.pl
NOERROR	budg165.ar.wroc.pl
NOERROR	komp237.mel.ar.wroc.pl
NOERROR	komp13.cadlab.ar.wroc.pl
NOERROR	imr29.mech.ar.wroc.pl
NOERROR	ada39.ar.wroc.pl
NOERROR	buch218.ar.wroc.pl
NOERROR	imr145.mech.ar.wroc.pl
NOERROR	buch194.ar.wroc.pl
NOERROR	wyd8.ar.wroc.pl
NOERROR	komp22.cadlab.ar.wroc.pl
NOERROR	dhcp153.mel.ar.wroc.pl
NOERROR	imr157.mech.ar.wroc.pl
NOERROR	komp48.hod.ar.wroc.pl
NOERROR	dhcp196.mel.ar.wroc.pl
NXDOMAIN	klin119.ar.wroc.pl
NXDOMAIN	klin96.ar.wroc.pl
NOERROR	apar252.ar.wroc.pl
NOERROR	komp27.cadlab.ar.wroc.pl
NOERROR	budg221.ar.wroc.pl
NOERROR	dhcp167.mel.ar.wroc.pl
NOERROR	dhcp114.mel.ar.wroc.pl
NOERROR	ada20.ar.wroc.pl
NOERROR	dhcp122.mel.ar.wroc.pl
NOERROR	dhcp95.mel.ar.wroc.pl
NOERROR	dhcp185.mel.ar.wroc.pl
NOERROR	ekono-101.ar.wroc.pl
NOERROR	bos116.hod.ar.wroc.pl
NOERROR	budg201.ar.wroc.pl
NOERROR	imr79.mech.ar.wroc.pl
NOERROR	imr171.mech.ar.wroc.pl
NXDOMAIN	klin121.ar.wroc.pl
NOERROR	imr195.mech.ar.wroc.pl
NOERROR	komp21.cadlab.ar.wroc.pl
NOERROR	dhcp143.mel.ar.wroc.pl
NOERROR	ksz150.ar.wroc.pl
NOERROR	imr52.mech.ar.wroc.pl
NOERROR	gen68.hod.ar.wroc.pl
NXDOMAIN	406c.atlans.ar.wroc.pl
NOERROR	wyd6.ar.wroc.pl
NOERROR	budg171.ar.wroc.pl
NOERROR	imr58.mech.ar.wroc.pl
NOERROR	komp35.hod.ar.wroc.pl
NOERROR	budg188.ar.wroc.pl
NOERROR	ada46.ar.wroc.pl
NOERROR	k1.hod.ar.wroc.pl
NOERROR	wyd21.ar.wroc.pl
NOERROR	wyd56.ar.wroc.pl
NOERROR	dhcp131.mel.ar.wroc.pl
NOERROR	sw4h.hod.ar.wroc.pl
NOERROR	budg224.ar.wroc.pl
NOERROR	imr155.mech.ar.wroc.pl
NOERROR	ksz217.ar.wroc.pl
NOERROR	komp174.hod.ar.wroc.pl
NOERROR	ksz212.ar.wroc.pl
NOERROR	imr218.mech.ar.wroc.pl
NOERROR	buch213.ar.wroc.pl
NOERROR	ksz142.ar.wroc.pl
NXDOMAIN	nbm.bibl.ar.wroc.pl
NOERROR	komp50.hod.ar.wroc.pl
NOERROR	ksz216.ar.wroc.pl
NOERROR	apar231.ar.wroc.pl
NOERROR	gen141.hod.ar.wroc.pl
NOERROR	imr33.mech.ar.wroc.pl
NOERROR	dhcp223.mel.ar.wroc.pl
NOERROR	buch199.ar.wroc.pl
NOERROR	imr86.mech.ar.wroc.pl
NOERROR	imr53.mech.ar.wroc.pl
NOERROR	imr176.mech.ar.wroc.pl
NOERROR	gen142.hod.ar.wroc.pl
NOERROR	budg196.ar.wroc.pl
NOERROR	komp250.hod.ar.wroc.pl
NOERROR	dhcp107.mel.ar.wroc.pl
NXDOMAIN	klin109.ar.wroc.pl
NOERROR	dhcp93.mel.ar.wroc.pl
NOERROR	gen92.hod.ar.wroc.pl
NOERROR	szyda2.hod.ar.wroc.pl
NOERROR	gen152.hod.ar.wroc.pl
NOERROR	ekono-71.ar.wroc.pl
NOERROR	budg154.ar.wroc.pl
NOERROR	apar245.ar.wroc.pl
NOERROR	dhcp211.mel.ar.wroc.pl
NOERROR	budg153.ar.wroc.pl
NOERROR	ksz206.ar.wroc.pl
NOERROR	ekono-92.ar.wroc.pl
NOERROR	imr30.mech.ar.wroc.pl
NOERROR	budg234.ar.wroc.pl
NOERROR	imr115.mech.ar.wroc.pl
NOERROR	dhcp121.mel.ar.wroc.pl
NOERROR	imr81.mech.ar.wroc.pl
NXDOMAIN	klin76.ar.wroc.pl
NOERROR	budg249.ar.wroc.pl
NOERROR	apar246.ar.wroc.pl
NOERROR	imr220.mech.ar.wroc.pl
NOERROR	ksz156.ar.wroc.pl
NOERROR	ekono-66.ar.wroc.pl
NOERROR	wyd30.ar.wroc.pl
NOERROR	komp215.hod.ar.wroc.pl
NOERROR	dhcp150.mel.ar.wroc.pl
NOERROR	sw5.mel.ar.wroc.pl
NOERROR	imr4.mech.ar.wroc.pl
NOERROR	komp36.hod.ar.wroc.pl
NOERROR	imr162.mech.ar.wroc.pl
NOERROR	dhcp141.mel.ar.wroc.pl
NOERROR	komp29.cadlab.ar.wroc.pl
NOERROR	dhcp186.mel.ar.wroc.pl
NOERROR	ada34.ar.wroc.pl
NOERROR	ada33.ar.wroc.pl
NOERROR	buch204.ar.wroc.pl
NOERROR	budg182.ar.wroc.pl
NOERROR	ekono-89.ar.wroc.pl
NOERROR	wyd27.ar.wroc.pl
NOERROR	ada41.ar.wroc.pl
NOERROR	ada19.ar.wroc.pl
NXDOMAIN	gen.ar.wroc.pl
NXDOMAIN	klin107.ar.wroc.pl
NXDOMAIN	klin111.ar.wroc.pl
NOERROR	ada59.ar.wroc.pl
NOERROR	dhcp101.mel.ar.wroc.pl
NOERROR	dhcp166.mel.ar.wroc.pl
NOERROR	gen91.hod.ar.wroc.pl
NOERROR	dhcp137.mel.ar.wroc.pl
NOERROR	komp37.hod.ar.wroc.pl
NOERROR	komp49.hod.ar.wroc.pl
NOERROR	ksz208.ar.wroc.pl
NOERROR	imr65.mech.ar.wroc.pl
NOERROR	imr194.mech.ar.wroc.pl
NOERROR	dhcp183.mel.ar.wroc.pl
NOERROR	budg187.ar.wroc.pl
NOERROR	imr118.mech.ar.wroc.pl
NOERROR	komp242.hod.ar.wroc.pl
NXDOMAIN	klin73.ar.wroc.pl
NOERROR	ekono-107.ar.wroc.pl
NXDOMAIN	klin88.ar.wroc.pl
NXDOMAIN	klin91.ar.wroc.pl
NOERROR	budg144.ar.wroc.pl
NOERROR	imr27.mech.ar.wroc.pl
NXDOMAIN	klin108.ar.wroc.pl
NOERROR	budg198.ar.wroc.pl
NOERROR	dhcp212.mel.ar.wroc.pl
NOERROR	ekono-106.ar.wroc.pl
NOERROR	hala.hod.ar.wroc.pl
NOERROR	ada23.ar.wroc.pl
NOERROR	imr135.mech.ar.wroc.pl
NOERROR	komp248.hod.ar.wroc.pl
NOERROR	imr22.mech.ar.wroc.pl
NOERROR	imr182.mech.ar.wroc.pl
NOERROR	dhcp216.mel.ar.wroc.pl
NOERROR	budg132.ar.wroc.pl
NOERROR	gen81.hod.ar.wroc.pl
NOERROR	komp19.cadlab.ar.wroc.pl
NOERROR	gen139.hod.ar.wroc.pl
NOERROR	ekono-104.ar.wroc.pl
NOERROR	imr170.mech.ar.wroc.pl
NOERROR	dhcp151.mel.ar.wroc.pl
NOERROR	imr82.mech.ar.wroc.pl
NOERROR	budg204.ar.wroc.pl
NOERROR	imr179.mech.ar.wroc.pl
NOERROR	imr216.mech.ar.wroc.pl
NOERROR	ekono-112.ar.wroc.pl
NOERROR	buch221.ar.wroc.pl
NOERROR	dhcp134.mel.ar.wroc.pl
NOERROR	komp223.hod.ar.wroc.pl
