NOERROR	pizarro.fll.urv.es
NOERROR	qa-19.urv.es
NOERROR	qa-3.urv.es
NOERROR	taz.etse.urv.es
NOERROR	wtmp201.urv.es
NOERROR	ftp.etse.urv.es
NOERROR	pec-dpedago.urv.es
NOERROR	vsph2-sc2.urv.es
NOERROR	www.ice.urv.es
NOERROR	secdbioq.fq.urv.es
NOERROR	sysdb.urv.es
NOERROR	carboni.fq.urv.es
NOERROR	zeta.fll.urv.es
NOERROR	pometa.urv.es
NOERROR	planck.urv.es
NOERROR	hostjoan05.urv.es
NOERROR	ninsus.fll.urv.es
NOERROR	climatic.fll.urv.es
NOERROR	wtmp207.urv.es
NXDOMAIN	lw-qf.urv.es
NOERROR	glorieta.fcep.urv.es
NXDOMAIN	cs.urv.es
NOERROR	qa-30.fq.urv.es
NOERROR	wwwa.urv.es
NOERROR	dns4.urv.es
NXDOMAIN	xterm-a4.urv.es
NXDOMAIN	auleslliureacces.urv.es
NOERROR	jocapqua.urv.es
NOERROR	urv-gw.urv.es
NOERROR	dns.urv.es
NOERROR	hostjoan13.urv.es
NOERROR	wtmp243.urv.es
NXDOMAIN	www.ework.urv.es
NOERROR	srect.urv.es
NOERROR	wis.urv.es
NOERROR	dafits.urv.es
NOERROR	vsph3.urv.es
NOERROR	mta04.urv.es
NOERROR	poma2.urv.es
NOERROR	qo-5.urv.es
NOERROR	adfcat.fll.urv.es
NOERROR	wtmp200.urv.es
NOERROR	cinz.fll.urv.es
NOERROR	qa-20.urv.es
NOERROR	aaform.urv.es
NOERROR	sesport.urv.es
NOERROR	vsph5-vmk.urv.es
NOERROR	ftp.urv.es
NOERROR	macatala03.urv.es
NOERROR	gwa.urv.es
NOERROR	bohr.urv.es
NOERROR	webgrec.urv.es
NOERROR	gate-sc.urv.es
NOERROR	develop.urv.es
NOERROR	ast-deim.urv.es
NOERROR	neptu3.urv.es
NOERROR	secdfag.fll.urv.es
NOERROR	hostjoan08.urv.es
NOERROR	pixie.etse.urv.es
NOERROR	sauron.etse.urv.es
NOERROR	hostjoan14.urv.es
NOERROR	mercuri6.urv.es
NOERROR	dwhmicro.urv.es
NOERROR	medcat.urv.es
NOERROR	wc.urv.es
NOERROR	seleni.urv.es
NOERROR	dixie1.urv.es
NOERROR	etse.urv.es
NOERROR	neptu4.urv.es
NOERROR	accremot02.urv.es
NOERROR	agora-ice.urv.es
NOERROR	qa-14.urv.es
NOERROR	buski.urv.es
NXDOMAIN	www.sred01.serveis.intranet.urv.es
NOERROR	romario.fll.urv.es
NOERROR	folk.fll.urv.es
NXDOMAIN	www.iochem-bd.urv.es
NOERROR	www.fcee.urv.es
NOERROR	urv.es
NXDOMAIN	arxiu.fll.urv.es
NOERROR	gwb.urv.es
NOERROR	mta02.urv.es
NOERROR	genomes.urv.es
NOERROR	pedagogia.fcep.urv.es
NOERROR	rdeeea50.etse.urv.es
NOERROR	cris22.urv.es
NOERROR	chiki.urv.es
NOERROR	calag.fll.urv.es
NOERROR	sim2.urv.es
NOERROR	get.fcep.urv.es
NOERROR	hostjoan17.urv.es
NOERROR	poma3.urv.es
NXDOMAIN	win32hd.urv.es
NOERROR	neptu5.urv.es
NOERROR	crises.etse.urv.es
NOERROR	pupitre.urv.es
NXDOMAIN	apqua.astor.urv.es
NXDOMAIN	sred10.serveis.intranet.urv.es
NOERROR	wtmp199.urv.es
NOERROR	iochem-bd.urv.es
NOERROR	secret.src.urv.es
NOERROR	etseq.urv.es
NOERROR	hostjoan10.urv.es
NOERROR	webgrecdev.urv.es
NXDOMAIN	bioserver.urv.es
NOERROR	romani.iua.urv.es
NOERROR	fundacio.urv.es
NOERROR	quimic01.fq.urv.es
NOERROR	www.etseq.urv.es
NOERROR	sdgh.fll.urv.es
NOERROR	hostjoan19.urv.es
NXDOMAIN	xterm-a3.urv.es
NOERROR	estudiants.urv.es
NOERROR	pcasoc.urv.es
NOERROR	qa-13.urv.es
NOERROR	lan-sic.urv.es
NOERROR	fa-1.urv.es
NOERROR	qo-1.urv.es
NOERROR	qo-3.urv.es
NOERROR	www.eui.urv.es
NOERROR	ast2-deim.urv.es
NOERROR	mta.urv.es
NOERROR	gmao.urv.es
NOERROR	accremot01.urv.es
NOERROR	deeea.urv.es
NOERROR	filo.fll.urv.es
NOERROR	qa-4.urv.es
NOERROR	grusma2.etse.urv.es
NXDOMAIN	imperial-gw.urv.es
NOERROR	vsph4-vmk.urv.es
NOERROR	wis.si.urv.es
NOERROR	isg.urv.es
NOERROR	rodi.urv.es
NOERROR	www.fundacio.urv.es
NXDOMAIN	sred01.serveis.intranet.urv.es
NOERROR	vsph3-sc2.urv.es
NOERROR	argo.urv.es
NOERROR	lletre04.fll.urv.es
NOERROR	macblanc.urv.es
NXDOMAIN	xterm-a5.urv.es
NOERROR	polymers.urv.es
NOERROR	mercuri2.urv.es
NOERROR	qi-1.urv.es
NOERROR	hostjoan01.urv.es
NOERROR	www.quimica.urv.es
NOERROR	hostjoan18.urv.es
NOERROR	dbs3.urv.es
NOERROR	qa-16.urv.es
NOERROR	fenix.urv.es
NOERROR	ateum.fll.urv.es
NOERROR	www.sgr.urv.es
NOERROR	gamma.fll.urv.es
NOERROR	www.fmcs.urv.es
NOERROR	docencia.urv.es
NOERROR	www.crever.urv.es
NOERROR	vsph1-sc2.urv.es
NOERROR	sgew.urv.es
NOERROR	vsph3-vmk.urv.es
NOERROR	qo-4.urv.es
NXDOMAIN	neo.urv.es
NOERROR	crever.urv.es
NOERROR	macnegre3.urv.es
NOERROR	vsph2.urv.es
NOERROR	qa-7.urv.es
NOERROR	ws.urv.es
NXDOMAIN	switchcen.fq.urv.es
NOERROR	prehistoria.urv.es
NOERROR	hostjoan20.urv.es
NOERROR	cicely.etseq.urv.es
NOERROR	hostjoan03.urv.es
NOERROR	simulacio.urv.es
NOERROR	planet.urv.es
NOERROR	qi-4.urv.es
NOERROR	mercuri0.urv.es
NOERROR	vsph5.urv.es
NOERROR	qa-18.urv.es
NOERROR	hostjoan04.urv.es
NOERROR	semhisp2.fll.urv.es
NOERROR	wtmp245.urv.es
NXDOMAIN	vcfsre.urv.es
NOERROR	hostjoan02.urv.es
NOERROR	sun2.fcep.urv.es
NOERROR	www.linguistic.urv.es
NOERROR	accremot.urv.es
NOERROR	tronk.urv.es
NOERROR	rectorat.urv.es
NXDOMAIN	campus.urv.es
NOERROR	vcenter0.urv.es
NOERROR	qa-2.urv.es
NXDOMAIN	sred33.serveis.intranet.urv.es
NOERROR	www.srct.urv.es
NOERROR	sysdbdmz1.urv.es
NOERROR	www.etse.urv.es
NXDOMAIN	win32app.urv.es
NOERROR	narnal.urv.es
NXDOMAIN	electro.fq.urv.es
NOERROR	wtmp203.urv.es
NOERROR	vsph4.urv.es
NOERROR	bibsescelades.urv.es
NOERROR	qa-28.fq.urv.es
NOERROR	poma1.urv.es
NOERROR	grusma.etse.urv.es
NOERROR	vsph0.urv.es
NOERROR	qa-8.urv.es
NOERROR	cabibses.urv.es
NOERROR	www.fcj.urv.es
NOERROR	correu.urv.es
NXDOMAIN	bioquimica.urv.es
NOERROR	banzai.etse.urv.es
NOERROR	poma0.urv.es
NOERROR	vsph0-sc2.urv.es
NOERROR	qi-3.urv.es
NOERROR	riutord.fll.urv.es
NOERROR	laue.urv.es
NOERROR	neptu2.urv.es
NOERROR	ldap0.urv.es
NOERROR	qi-2.urv.es
NOERROR	hostjoan12.urv.es
NOERROR	mercuri1.urv.es
NOERROR	mjo.fll.urv.es
NOERROR	secdfr.fll.urv.es
NOERROR	mta01.urv.es
NOERROR	rocom.fll.urv.es
NOERROR	picentral.urv.es
NOERROR	www.dge.urv.es
NOERROR	wtmp204.urv.es
NOERROR	backup1.urv.es
NOERROR	vsph1-vmk.urv.es
NOERROR	vsph2-vmk.urv.es
NOERROR	simpple01.urv.es
NOERROR	vneumann.etse.urv.es
NOERROR	qa-6.urv.es
NOERROR	wtmp202.urv.es
NOERROR	mercuri3.urv.es
NOERROR	cris27.urv.es
NOERROR	hostjoan11.urv.es
NOERROR	semhisp.fll.urv.es
NOERROR	lletre02.urv.es
NOERROR	mercuri5.urv.es
NOERROR	redotri.urv.es
NOERROR	sim1.urv.es
NOERROR	www.fee.urv.es
NOERROR	pixie.etseq.urv.es
NXDOMAIN	astor.urv.es
NOERROR	vsph5-sc2.urv.es
NOERROR	vsph1.urv.es
NXDOMAIN	seeslab-deq.urv.es
NOERROR	www.fcep.urv.es
NXDOMAIN	appserv.urv.es
NOERROR	sim0.urv.es
NOERROR	late-dpedago.urv.es
NXDOMAIN	xterm-a2.urv.es
NOERROR	ecommfit.urv.es
NOERROR	hostjoan15.urv.es
NOERROR	galileo.urv.es
NOERROR	qa-12.urv.es
NOERROR	www.sre.urv.es
NOERROR	beta.fll.urv.es
NOERROR	cde05.etse.urv.es
NOERROR	qa-11.urv.es
NOERROR	qa-29.fq.urv.es
NOERROR	vsph0-vmk.urv.es
NOERROR	sic.urv.es
NOERROR	qa-21.urv.es
NOERROR	nougrec.urv.es
NOERROR	www.urv.es
NOERROR	alfa.fll.urv.es
NXDOMAIN	assjur.urv.es
NXDOMAIN	laplaciana.urv.es
NOERROR	hostjoan09.urv.es
NOERROR	qa-9.urv.es
NOERROR	dwh.urv.es
NOERROR	deasrv04.urv.es
NOERROR	neptu1.urv.es
NOERROR	macsl.fll.urv.es
NOERROR	banzai-deim.urv.es
NOERROR	secdpantro.fll.urv.es
NOERROR	fa25.urv.es
NOERROR	maccapbib.urv.es
NOERROR	antropologia.urv.es
NOERROR	wtmp205.urv.es
NOERROR	deim.urv.es
NOERROR	reloj.urv.es
NXDOMAIN	heli.urv.es
NOERROR	deasrv03.urv.es
NOERROR	gw0.urv.es
NOERROR	qo-2.urv.es
NOERROR	japon.fll.urv.es
NOERROR	hostjoan07.urv.es
NOERROR	ants.etse.urv.es
NOERROR	matrix.etseq.urv.es
NOERROR	cvp.urv.es
NOERROR	jcast.src.urv.es
NOERROR	aliga.urv.es
NOERROR	www0.urv.es
NOERROR	gandalf.fcee.urv.es
NXDOMAIN	lavoisier.urv.es
NOERROR	vsph4-sc2.urv.es
NOERROR	www.antropologia.urv.es
NOERROR	qa-1.urv.es
NOERROR	cliesab.urv.es
NOERROR	hostjoan16.urv.es
NOERROR	dbs5.urv.es
NOERROR	qa-15.urv.es
NOERROR	edustance.urv.es
NOERROR	noguera.fcep.urv.es
NOERROR	qa-17.urv.es
NOERROR	ebre.fcep.urv.es
NOERROR	deasrv02.urv.es
NXDOMAIN	bib.urv.es
NOERROR	cris26.urv.es
NOERROR	wtmp244.urv.es
NOERROR	pcpi.urv.es
NOERROR	secdq.urv.es
NOERROR	teledoc.urv.es
NOERROR	power0.urv.es
NOERROR	biblq.urv.es
NOERROR	ra.etse.urv.es
NOERROR	psico.fcep.urv.es
NOERROR	hostjoan21.urv.es
NOERROR	gaseus.fll.urv.es
NOERROR	lagta.fll.urv.es
NOERROR	qa-10.urv.es
NOERROR	hostjoan06.urv.es
NOERROR	ework.urv.es
NOERROR	wtmp206.urv.es
NOERROR	lvs1.urv.es
NOERROR	lvs0.urv.es
NOERROR	qa-5.urv.es
NOERROR	wtmp242.urv.es
NOERROR	mta03.urv.es
NOERROR	www.fll.urv.es
NXDOMAIN	brom.urv.es
NOERROR	crackir.fll.urv.es
NXDOMAIN	pcqf-3.urv.es
NOERROR	ldap1.urv.es
NOERROR	biblioteca.urv.es
NOERROR	macnegre1.urv.es
