#!/bin/sh

n=$(ls -1 jdomains/ | wc | awk '{print $1}')
i=1

while [ $i -le $n ]
do
	domain=$(ls -1 jdomains/ | sed "${i}q;d")
	Mi=$(wc jdomains/$domain | awk '{print $1}')
	j=1

	while [ $j -le $Mi ]
	do
		echo -ne "$j of $Mi in $domain ($i of $n domains)\n"
		server=$(curl -I -s --connect-timeout 2 "$(sed "${j}q;d" jdomains/$domain)" | grep Server | sed "s/Server:\s//g")
		if [ -z "$server" ]; then
			server=$(curl -I -s --connect-timeout 2 "https://$(sed "${j}q;d" jdomains/$domain)" | grep Server | sed "s/Server:\s//g")
			if [ -z "$server" ]; then
				server=$(curl -I -s --connect-timeout 2 "http://$(sed "${j}q;d" jdomains/$domain)" | grep Server | sed "s/Server:\s//g")
				if [ -z "$server" ]; then
					echo "NA" >> servers/$domain
				else
					echo $server >> servers/$domain
				fi
			else
				echo $server >> servers/$domain
			fi
		else
			echo $server >> servers/$domain
		fi
		j=$((++j))
	done

	i=$((++i))
done
