#!/bin/sh

n=$(ls -1 existing-hosts/ | wc | awk '{print $1}')

i=1

while [ $i -le $n ]
do
	domain=$(ls -1 existing-hosts/ | sed "${i}q;d")
	Mi=$(wc existing-hosts/$domain | awk '{print $1}')
	j=1

	while [ $j -le $Mi ]
	do
		echo -ne "$j of $Mi in $domain ($i of $n domains)\r"
		server=$(curl -I -s --connect-timeout 5 "$(sed "${j}q;d" existing-hosts/$domain)" | grep Server | sed "s/Server:\s//g")
		if [ -z "$server" ]; then
			echo "NA" >> servers/$domain
		else
			echo $server >> servers/$domain
		fi
		j=$((++j))
	done

	i=$((++i))
done
