#!/bin/sh

n=$(ls -1 subdomains/ | wc | awk '{print $1}')

i=1

while [ $i -le $n ]
do

	domain=$(ls -1 subdomains/ | sed "${i}q;d")
	Mi=$(wc subdomains/$domain | awk '{print $1}')
	j=1

	while [ $j -le $Mi ]
	do
		echo -ne "$j of $Mi in $domain ($i of $n domains)\r"
		if host $(sed "${j}q;d" subdomains/$domain) >/dev/null; then
			echo $(sed "${j}q;d" subdomains/$domain) >> existing-hosts/$domain
		fi
		j=$((++j))
	done

	i=$((++i))
done
