#!/bin/sh

n=$(ls -1 subdomains/ | wc | awk '{print $1}')

i=1

while [ $i -le $n ]
do
	domain=$(ls -1 subdomains/ | sed "${i}q;d")
	dig -f subdomains/$domain -r | grep HEADER | awk '{print $6}' | sed 's/,//g' > probe-with-dig/$domain
	i=$((++i))
done
