NOERROR	www.barwa.pjwstk.edu.pl
NXDOMAIN	epg.pjwstk.edu.pl
NOERROR	www.bytom.pjwstk.edu.pl
NOERROR	utrust.pjwstk.edu.pl
NOERROR	www.eide2.pjwstk.edu.pl
NOERROR	odraforum.pjwstk.edu.pl
NXDOMAIN	ucsc04.pjwstk.edu.pl
NXDOMAIN	sjo.pjwstk.edu.pl
NOERROR	lan10k4.pjwstk.edu.pl
NOERROR	www.edu.pjwstk.edu.pl
NOERROR	www.e-s.pjwstk.edu.pl
NOERROR	lab233.pjwstk.edu.pl
NOERROR	acs.pjwstk.edu.pl
NOERROR	realizacjadzwieku.pjwstk.edu.pl
NOERROR	www.samorzad.pjwstk.edu.pl
NOERROR	gdansk.pjwstk.edu.pl
NXDOMAIN	roundbox.pjwstk.edu.pl
NOERROR	www.iccvg2008.pjwstk.edu.pl
NOERROR	poczta.pjwstk.edu.pl
NXDOMAIN	www.epg.pjwstk.edu.pl
NXDOMAIN	rss.pjwstk.edu.pl
NOERROR	acs-cisco.pjwstk.edu.pl
NOERROR	lab015.pjwstk.edu.pl
NXDOMAIN	vmtb-hp10.pjwstk.edu.pl
NOERROR	lab119.pjwstk.edu.pl
NOERROR	gda-kariera.pjwstk.edu.pl
NXDOMAIN	www.tfulab-hcs01.pjwstk.edu.pl
NXDOMAIN	zapisobrazu.pjwstk.edu.pl
NOERROR	targipracy.pjwstk.edu.pl
NOERROR	www.edux.pjwstk.edu.pl
NXDOMAIN	tomcat.pjwstk.edu.pl
NOERROR	lab223.pjwstk.edu.pl
NOERROR	www.ssl.pjwstk.edu.pl
NXDOMAIN	yasgot.pjwstk.edu.pl
NXDOMAIN	www.ai.pjwstk.edu.pl
NXDOMAIN	www.umbra.pjwstk.edu.pl
NOERROR	poszukiwacze.pjwstk.edu.pl
NXDOMAIN	www.kadry.pjwstk.edu.pl
NOERROR	scena3d.pjwstk.edu.pl
NXDOMAIN	www.vmtb-vc7.pjwstk.edu.pl
NOERROR	www.biblioteka.pjwstk.edu.pl
NXDOMAIN	www.caic.pjwstk.edu.pl
NOERROR	phpmyadmin.pjwstk.edu.pl
NXDOMAIN	www.31337.pjwstk.edu.pl
NXDOMAIN	wiki.pjwstk.edu.pl
NOERROR	prezesa.pjwstk.edu.pl
NXDOMAIN	blaster.pjwstk.edu.pl
NOERROR	www.system.biblioteka.pjwstk.edu.pl
NOERROR	yoshimune.pjwstk.edu.pl
NOERROR	grafika.pjwstk.edu.pl
NOERROR	flyspray.pjwstk.edu.pl
NXDOMAIN	www.kmkt.pjwstk.edu.pl
NXDOMAIN	matstos.pjwstk.edu.pl
NOERROR	si.pjwstk.edu.pl
NOERROR	liceumplastyczne.pjwstk.edu.pl
NOERROR	adm.pjwstk.edu.pl
NOERROR	motyf.pjwstk.edu.pl
NOERROR	www.liceum.pjwstk.edu.pl
NXDOMAIN	www.matstos.pjwstk.edu.pl
NOERROR	wzi.pjwstk.edu.pl
NOERROR	ftp.pjwstk.edu.pl
NOERROR	eduroam.pjwstk.edu.pl
NOERROR	l2quantification.pjwstk.edu.pl
NOERROR	kgj.pjwstk.edu.pl
NOERROR	nomadstage.pjwstk.edu.pl
NXDOMAIN	sko2.pjwstk.edu.pl
NXDOMAIN	bbb.pjwstk.edu.pl
NXDOMAIN	umbra.pjwstk.edu.pl
NOERROR	katedra.pjwstk.edu.pl
NOERROR	hm.pjwstk.edu.pl
NXDOMAIN	dotnet.pjwstk.edu.pl
NOERROR	www.sieci.pjwstk.edu.pl
NOERROR	www.mayaclub.pjwstk.edu.pl
NXDOMAIN	vu2009.pjwstk.edu.pl
NOERROR	www.gakko.pjwstk.edu.pl
NOERROR	lab001.pjwstk.edu.pl
NOERROR	makro.pjwstk.edu.pl
NOERROR	kansei.pjwstk.edu.pl
NOERROR	db-day.pjwstk.edu.pl
NOERROR	www2.pjwstk.edu.pl
NXDOMAIN	bf2142.pjwstk.edu.pl
NXDOMAIN	kuchnia.pjwstk.edu.pl
NXDOMAIN	wap.pjwstk.edu.pl
NOERROR	start.pjwstk.edu.pl
NOERROR	kurp.pjwstk.edu.pl
NOERROR	www.db-day.pjwstk.edu.pl
NOERROR	ora.pjwstk.edu.pl
NXDOMAIN	icinga.pjwstk.edu.pl
NXDOMAIN	six.pjwstk.edu.pl
NOERROR	cisco.bytom.pjwstk.edu.pl
NOERROR	cbr.pjwstk.edu.pl
NOERROR	lab017.pjwstk.edu.pl
NOERROR	www.dreamproject.pjwstk.edu.pl
NOERROR	fin.pjwstk.edu.pl
NOERROR	podanie.pjwstk.edu.pl
NOERROR	www.rekrutacja.pjwstk.edu.pl
NOERROR	www.gdansk.pjwstk.edu.pl
NOERROR	system-biblioteka.pjwstk.edu.pl
NOERROR	db-appz2.pjwstk.edu.pl
NOERROR	tfulab-hcs01.pjwstk.edu.pl
NOERROR	www.speech.pjwstk.edu.pl
NXDOMAIN	vfreenas01.pjwstk.edu.pl
NOERROR	xn--haso-21a.pjwstk.edu.pl
NXDOMAIN	moonsite.pjwstk.edu.pl
NXDOMAIN	tokyolectures.pjwstk.edu.pl
NOERROR	grom.pjwstk.edu.pl
NOERROR	error501.pjwstk.edu.pl
NXDOMAIN	lug.pjwstk.edu.pl
NOERROR	kis.pjwstk.edu.pl
NOERROR	lab132.pjwstk.edu.pl
NOERROR	edux.pjwstk.edu.pl
NOERROR	tomaszew.pjwstk.edu.pl
NOERROR	dreamproject.pjwstk.edu.pl
NXDOMAIN	broadcast.pjwstk.edu.pl
NOERROR	binarny.pjwstk.edu.pl
NXDOMAIN	www.ucsc04.pjwstk.edu.pl
NOERROR	bss.pjwstk.edu.pl
NOERROR	live.pjwstk.edu.pl
NOERROR	www.dziekanat.pjwstk.edu.pl
NXDOMAIN	codelords.pjwstk.edu.pl
NOERROR	speech.pjwstk.edu.pl
NOERROR	ns2.pjwstk.edu.pl
NOERROR	tayio.pjwstk.edu.pl
NOERROR	www.aip.bytom.pjwstk.edu.pl
NXDOMAIN	www.inkubator.pjwstk.edu.pl
NOERROR	www.realizacjadzwieku.pjwstk.edu.pl
NXDOMAIN	absynth.pjwstk.edu.pl
NOERROR	www.grafika3d.pjwstk.edu.pl
NOERROR	pjwstk.edu.pl
NOERROR	www.targipracy.pjwstk.edu.pl
NOERROR	kariera.pjwstk.edu.pl
NXDOMAIN	gizmo.pjwstk.edu.pl
NOERROR	www.szkolenia.pjwstk.edu.pl
NOERROR	res.pjwstk.edu.pl
NXDOMAIN	www.bike.pjwstk.edu.pl
NOERROR	www.poczta.pjwstk.edu.pl
NOERROR	lab113.pjwstk.edu.pl
NOERROR	s9api.pjwstk.edu.pl
NOERROR	www.webmail.pjwstk.edu.pl
NXDOMAIN	forum.pjwstk.edu.pl
NOERROR	dba.pjwstk.edu.pl
NOERROR	lab214.pjwstk.edu.pl
NOERROR	v21.pjwstk.edu.pl
NOERROR	wifi.pjwstk.edu.pl
NOERROR	kensei.pjwstk.edu.pl
NOERROR	www.poszukiwacze.pjwstk.edu.pl
NOERROR	rekrutacja2.pjwstk.edu.pl
NOERROR	www.system-biblioteka.pjwstk.edu.pl
NOERROR	www.ects-dss.pjwstk.edu.pl
NOERROR	win-www.pjwstk.edu.pl
NOERROR	bytom.pjwstk.edu.pl
NOERROR	webmining.pjwstk.edu.pl
NOERROR	azs.pjwstk.edu.pl
NOERROR	planzajec.pjwstk.edu.pl
NOERROR	cp.vlab.pjwstk.edu.pl
NXDOMAIN	itad.pjwstk.edu.pl
NOERROR	lab133.pjwstk.edu.pl
NOERROR	kaizen.pjwstk.edu.pl
NXDOMAIN	dzik.pjwstk.edu.pl
NOERROR	ovirt.pjwstk.edu.pl
NOERROR	system.biblioteka.pjwstk.edu.pl
NOERROR	win-appz.pjwstk.edu.pl
NOERROR	macek.pjwstk.edu.pl
NOERROR	ns3.pjwstk.edu.pl
NOERROR	www.imu.pjwstk.edu.pl
NXDOMAIN	bd.pjwstk.edu.pl
NXDOMAIN	www.tokyolectures.pjwstk.edu.pl
NOERROR	lab234.pjwstk.edu.pl
NXDOMAIN	stypendia.pjwstk.edu.pl
NXDOMAIN	www.sko.pjwstk.edu.pl
NXDOMAIN	www.zapisobrazu.pjwstk.edu.pl
NOERROR	vu.pjwstk.edu.pl
NOERROR	lab204.pjwstk.edu.pl
NOERROR	noname.pjwstk.edu.pl
NOERROR	kaizentestkompetencji.pjwstk.edu.pl
NOERROR	www.kgj.pjwstk.edu.pl
NOERROR	barwa.pjwstk.edu.pl
NXDOMAIN	www.jira.pjwstk.edu.pl
NOERROR	pimp.pjwstk.edu.pl
NXDOMAIN	www.wiki.pjwstk.edu.pl
NOERROR	sdkp.pjwstk.edu.pl
NOERROR	elms.pjwstk.edu.pl
NOERROR	www.iccvg.pjwstk.edu.pl
NOERROR	ssl.pjwstk.edu.pl
NOERROR	expe.cbr.pjwstk.edu.pl
NXDOMAIN	www.klub.pjwstk.edu.pl
NOERROR	grafika.bytom.pjwstk.edu.pl
NXDOMAIN	www.robotics.pjwstk.edu.pl
NOERROR	aikido.pjwstk.edu.pl
NXDOMAIN	mh4000.pjwstk.edu.pl
NOERROR	sop-screen.pjwstk.edu.pl
NOERROR	aict.pjwstk.edu.pl
NOERROR	gakko.pjwstk.edu.pl
NOERROR	iccvg2010.pjwstk.edu.pl
NOERROR	www.planzajec.pjwstk.edu.pl
NXDOMAIN	forum.31337.pjwstk.edu.pl
NOERROR	www.jaap.pjwstk.edu.pl
NOERROR	lab230.pjwstk.edu.pl
NOERROR	www.juwenalia.pjwstk.edu.pl
NXDOMAIN	crossfire.pjwstk.edu.pl
NXDOMAIN	oi.pjwstk.edu.pl
NOERROR	www.3d.pjwstk.edu.pl
NOERROR	lab134.pjwstk.edu.pl
NOERROR	www.liceumplastyczne.pjwstk.edu.pl
NOERROR	win-vpn.pjwstk.edu.pl
NXDOMAIN	lilo.pjwstk.edu.pl
NOERROR	lab099c.pjwstk.edu.pl
NOERROR	www.bss.pjwstk.edu.pl
NOERROR	spec.pjwstk.edu.pl
NOERROR	ankieta.pjwstk.edu.pl
NXDOMAIN	31337.pjwstk.edu.pl
NXDOMAIN	www.elektrotechnika.pjwstk.edu.pl
NXDOMAIN	ipv6.pjwstk.edu.pl
NOERROR	gcode.pjwstk.edu.pl
NOERROR	lab019.pjwstk.edu.pl
NOERROR	www.absolwenci.pjwstk.edu.pl
NXDOMAIN	stypendia-test.pjwstk.edu.pl
NOERROR	ruch.bytom.pjwstk.edu.pl
NXDOMAIN	www.dotcore.pjwstk.edu.pl
NOERROR	sum.pjwstk.edu.pl
NOERROR	ms.pjwstk.edu.pl
NOERROR	www.praktyki.pjwstk.edu.pl
NOERROR	hml.pjwstk.edu.pl
NOERROR	www.index.pjwstk.edu.pl
NOERROR	eventum.pjwstk.edu.pl
NOERROR	funcam.pjwstk.edu.pl
NOERROR	lan199.pjwstk.edu.pl
NOERROR	scl.pjwstk.edu.pl
NOERROR	lan10k3.pjwstk.edu.pl
NOERROR	atc.pjwstk.edu.pl
NXDOMAIN	www.oi.pjwstk.edu.pl
NOERROR	telilax.pjwstk.edu.pl
NXDOMAIN	superminer.pjwstk.edu.pl
NXDOMAIN	iolab.pjwstk.edu.pl
NOERROR	launch.pjwstk.edu.pl
NOERROR	msh.pjwstk.edu.pl
NOERROR	suggest.pjwstk.edu.pl
NXDOMAIN	robotics.pjwstk.edu.pl
NOERROR	lab220.pjwstk.edu.pl
NOERROR	www.error501.pjwstk.edu.pl
NOERROR	www.parelec2002.pjwstk.edu.pl
NXDOMAIN	mail.pjwstk.edu.pl
NOERROR	konto.pjwstk.edu.pl
NOERROR	multimedia.pjwstk.edu.pl
NOERROR	interkadra.pjwstk.edu.pl
NOERROR	iccvg2012.pjwstk.edu.pl
NOERROR	nomad.pjwstk.edu.pl
NOERROR	idp.pjwstk.edu.pl
NOERROR	svn.pjwstk.edu.pl
NOERROR	idp1.pjwstk.edu.pl
NOERROR	www.kariera.pjwstk.edu.pl
NXDOMAIN	noqmail.pjwstk.edu.pl
NOERROR	azuredevops.pjwstk.edu.pl
NOERROR	adfs.pjwstk.edu.pl
NOERROR	users.pjwstk.edu.pl
NXDOMAIN	vlabs.pjwstk.edu.pl
NXDOMAIN	www.absolwent.pjwstk.edu.pl
NOERROR	www.telilax.pjwstk.edu.pl
NOERROR	www.int.pjwstk.edu.pl
NOERROR	epracownik.pjwstk.edu.pl
NOERROR	percepcja.pjwstk.edu.pl
NOERROR	www.vu2013.pjwstk.edu.pl
NXDOMAIN	absolwent.pjwstk.edu.pl
NOERROR	software.pjwstk.edu.pl
NXDOMAIN	vdm.pjwstk.edu.pl
NXDOMAIN	sekret.pjwstk.edu.pl
NXDOMAIN	med.pjwstk.edu.pl
NOERROR	www.pm.pjwstk.edu.pl
NXDOMAIN	www.ait.pjwstk.edu.pl
NOERROR	acs-linux.pjwstk.edu.pl
NXDOMAIN	www.dkw.pjwstk.edu.pl
NOERROR	dziekanat.pjwstk.edu.pl
NXDOMAIN	gatekeeper.pjwstk.edu.pl
NOERROR	jap.pjwstk.edu.pl
NOERROR	www.launch.pjwstk.edu.pl
NOERROR	vpns.pjwstk.edu.pl
NOERROR	sklep.pjwstk.edu.pl
NXDOMAIN	intranet.pjwstk.edu.pl
NXDOMAIN	www.crossfire.pjwstk.edu.pl
NOERROR	www.grafika.bytom.pjwstk.edu.pl
NOERROR	win-dc01.pjwstk.edu.pl
NXDOMAIN	vmtb-vc7.pjwstk.edu.pl
NOERROR	www.si.pjwstk.edu.pl
NOERROR	www.biurokarier.pjwstk.edu.pl
NOERROR	www.acs-database.pjwstk.edu.pl
NOERROR	gnu.pjwstk.edu.pl
NOERROR	bibl.pjwstk.edu.pl
NOERROR	lap.pjwstk.edu.pl
NOERROR	www.syntezamowy.pjwstk.edu.pl
NOERROR	winci.bytom.pjwstk.edu.pl
NXDOMAIN	www.ucsc01.pjwstk.edu.pl
NOERROR	reconcile.pjwstk.edu.pl
NOERROR	pilecki.pjwstk.edu.pl
NOERROR	jaap.pjwstk.edu.pl
NXDOMAIN	www.vmtb-hp10.pjwstk.edu.pl
NOERROR	www.otro.pjwstk.edu.pl
NOERROR	db-appz.pjwstk.edu.pl
NOERROR	googleblog.pjwstk.edu.pl
NOERROR	vpn.pjwstk.edu.pl
NOERROR	crawling.pjwstk.edu.pl
NXDOMAIN	dkw.pjwstk.edu.pl
NXDOMAIN	www.wikijap.pjwstk.edu.pl
NXDOMAIN	quak.pjwstk.edu.pl
NXDOMAIN	peki.pjwstk.edu.pl
NXDOMAIN	www.gatekeeper.pjwstk.edu.pl
NOERROR	lan10k2.pjwstk.edu.pl
NXDOMAIN	kadry-api.pjwstk.edu.pl
NOERROR	ai.pjwstk.edu.pl
NOERROR	mariuszklec.pjwstk.edu.pl
NXDOMAIN	freenas.pjwstk.edu.pl
NXDOMAIN	io.pjwstk.edu.pl
NXDOMAIN	jira.pjwstk.edu.pl
NOERROR	edu.pjwstk.edu.pl
NOERROR	szkolenia.pjwstk.edu.pl
NOERROR	www.studenci.pjwstk.edu.pl
NOERROR	samorzad.pjwstk.edu.pl
NOERROR	sso.pjwstk.edu.pl
NOERROR	radio.pjwstk.edu.pl
NOERROR	lab224.pjwstk.edu.pl
NOERROR	budd.pjwstk.edu.pl
NOERROR	motyf-ftp.pjwstk.edu.pl
NXDOMAIN	jajc.pjwstk.edu.pl
NOERROR	mushelka.pjwstk.edu.pl
NOERROR	npa.pjwstk.edu.pl
NOERROR	www.jl.pjwstk.edu.pl
NOERROR	kursy.pjwstk.edu.pl
NOERROR	lab131.pjwstk.edu.pl
NXDOMAIN	www.hcs80.pjwstk.edu.pl
NOERROR	www.vue.pjwstk.edu.pl
NOERROR	www.software.pjwstk.edu.pl
NOERROR	haslo.pjwstk.edu.pl
NOERROR	sieci.pjwstk.edu.pl
NOERROR	skype.pjwstk.edu.pl
NXDOMAIN	nano.pjwstk.edu.pl
NOERROR	tenis.pjwstk.edu.pl
NOERROR	lab116c.pjwstk.edu.pl
NOERROR	ects-dss.pjwstk.edu.pl
NOERROR	www.kensei.pjwstk.edu.pl
NXDOMAIN	ucsc01.pjwstk.edu.pl
NOERROR	www.scl.pjwstk.edu.pl
NOERROR	liceum.pjwstk.edu.pl
NXDOMAIN	www.stypendia-test.pjwstk.edu.pl
NOERROR	stat.pjwstk.edu.pl
NOERROR	lab013.pjwstk.edu.pl
NXDOMAIN	caic.pjwstk.edu.pl
NOERROR	tivc.pjwstk.edu.pl
NOERROR	sum-tech.pjwstk.edu.pl
NOERROR	www.sklep.pjwstk.edu.pl
NXDOMAIN	www.synteza.pjwstk.edu.pl
NXDOMAIN	www.kadry-api.pjwstk.edu.pl
NOERROR	vlab.pjwstk.edu.pl
NOERROR	kissel.pjwstk.edu.pl
NOERROR	www.search.pjwstk.edu.pl
NXDOMAIN	win-scanner.pjwstk.edu.pl
NOERROR	midi.pjwstk.edu.pl
NOERROR	podania.pjwstk.edu.pl
NOERROR	www.wzi.pjwstk.edu.pl
NOERROR	pja-vc01.pjwstk.edu.pl
NOERROR	www.kansei.pjwstk.edu.pl
NXDOMAIN	ucsc02.pjwstk.edu.pl
NXDOMAIN	inkubator.pjwstk.edu.pl
NOERROR	ccsq.pjwstk.edu.pl
NOERROR	lan10k1.pjwstk.edu.pl
NOERROR	szuflandia.pjwstk.edu.pl
NOERROR	bbb2.pjwstk.edu.pl
NOERROR	mroczek.pjwstk.edu.pl
NOERROR	rekrutacja3.pjwstk.edu.pl
NOERROR	www.stat.pjwstk.edu.pl
NOERROR	streaming.pjwstk.edu.pl
NXDOMAIN	kadry.pjwstk.edu.pl
NOERROR	mul-obliczenia.pjwstk.edu.pl
NOERROR	mteam.pjwstk.edu.pl
NOERROR	lab232.pjwstk.edu.pl
NOERROR	nomad3.pjwstk.edu.pl
NOERROR	acs-microsoft.pjwstk.edu.pl
NOERROR	abk.pjwstk.edu.pl
NXDOMAIN	nexor.pjwstk.edu.pl
NOERROR	fotografia360.pjwstk.edu.pl
NOERROR	uc.cbr.pjwstk.edu.pl
NOERROR	www.hci.pjwstk.edu.pl
NOERROR	www.users.pjwstk.edu.pl
NOERROR	sr-front.pjwstk.edu.pl
NOERROR	lan200.pjwstk.edu.pl
NOERROR	www.eventum.pjwstk.edu.pl
NOERROR	cnap.pjwstk.edu.pl
NOERROR	www.motyf.pjwstk.edu.pl
NOERROR	lab018.pjwstk.edu.pl
NOERROR	www.podania.pjwstk.edu.pl
NXDOMAIN	w7.pjwstk.edu.pl
NXDOMAIN	www.vfreenas01.pjwstk.edu.pl
NXDOMAIN	3rdcopro.pjwstk.edu.pl
NOERROR	praktyki.pjwstk.edu.pl
NOERROR	pozo.pjwstk.edu.pl
NXDOMAIN	dbatest.pjwstk.edu.pl
NOERROR	www.kis.pjwstk.edu.pl
NXDOMAIN	prolog.ai.pjwstk.edu.pl
NXDOMAIN	paintball.pjwstk.edu.pl
NOERROR	jlpt.pjwstk.edu.pl
NOERROR	lab130.pjwstk.edu.pl
NOERROR	antresola.pjwstk.edu.pl
NOERROR	syntezamowy.pjwstk.edu.pl
NOERROR	socinfo.pjwstk.edu.pl
NOERROR	pm.pjwstk.edu.pl
NOERROR	warsztaty.pjwstk.edu.pl
NOERROR	www.pjwstk.edu.pl
NOERROR	www.courses.pjwstk.edu.pl
NOERROR	opsview.pjwstk.edu.pl
NOERROR	lan198.pjwstk.edu.pl
NOERROR	rekrutacja.pjwstk.edu.pl
NXDOMAIN	vista.pjwstk.edu.pl
NOERROR	www.alias.pjwstk.edu.pl
NOERROR	obieralne.pjwstk.edu.pl
NOERROR	lin-wwwvirt.pjwstk.edu.pl
NOERROR	japonski.pjwstk.edu.pl
NOERROR	cisco.pjwstk.edu.pl
NOERROR	www.cisco.bytom.pjwstk.edu.pl
NOERROR	hci.pjwstk.edu.pl
NOERROR	hmkb.pjwstk.edu.pl
NXDOMAIN	www.aibio.pjwstk.edu.pl
NXDOMAIN	vmcl.pjwstk.edu.pl
NOERROR	lab231.pjwstk.edu.pl
NOERROR	google49bd7cf54f5524aa.pjwstk.edu.pl
NXDOMAIN	www.tts.pjwstk.edu.pl
NXDOMAIN	www.voyda.pjwstk.edu.pl
NOERROR	aule.pjwstk.edu.pl
NOERROR	hgmd.pjwstk.edu.pl
NXDOMAIN	www.sen.pjwstk.edu.pl
NXDOMAIN	www.nexor.pjwstk.edu.pl
NXDOMAIN	www.vu2009.pjwstk.edu.pl
NOERROR	iolan.pjwstk.edu.pl
NOERROR	lab-s05.pjwstk.edu.pl
NOERROR	lab117.pjwstk.edu.pl
NOERROR	iccvg.pjwstk.edu.pl
NOERROR	www.reconcile.pjwstk.edu.pl
NOERROR	gmail.pjwstk.edu.pl
NOERROR	studenci.pjwstk.edu.pl
NXDOMAIN	www.freenas.pjwstk.edu.pl
NOERROR	cudak.pjwstk.edu.pl
NOERROR	lab114.pjwstk.edu.pl
NXDOMAIN	ufo.pjwstk.edu.pl
NOERROR	www.google.pjwstk.edu.pl
NXDOMAIN	pja-psc01.pjwstk.edu.pl
NXDOMAIN	www.cbr.pjwstk.edu.pl
NOERROR	otro.pjwstk.edu.pl
NXDOMAIN	dziekanat-stary.pjwstk.edu.pl
NOERROR	view.pjwstk.edu.pl
NOERROR	gda-www.pjwstk.edu.pl
NOERROR	int.pjwstk.edu.pl
NOERROR	lab112.pjwstk.edu.pl
NOERROR	www.binarny.pjwstk.edu.pl
NOERROR	biurokarier.pjwstk.edu.pl
NOERROR	www.hml.pjwstk.edu.pl
NXDOMAIN	www.forum.pjwstk.edu.pl
NXDOMAIN	www.icinga.pjwstk.edu.pl
NOERROR	yoshinobu.pjwstk.edu.pl
NXDOMAIN	dotcore.pjwstk.edu.pl
NXDOMAIN	www.bd.pjwstk.edu.pl
NXDOMAIN	devel.pjwstk.edu.pl
NOERROR	lemon.pjwstk.edu.pl
NOERROR	biblioprojekt.pjwstk.edu.pl
NXDOMAIN	zabbix.pjwstk.edu.pl
NOERROR	teamhub.pjwstk.edu.pl
NOERROR	www.interkadra.pjwstk.edu.pl
NOERROR	win-dc02.pjwstk.edu.pl
NOERROR	www.tivc.pjwstk.edu.pl
NOERROR	sp1.pjwstk.edu.pl
NOERROR	www.jap.pjwstk.edu.pl
NOERROR	dojo.pjwstk.edu.pl
NOERROR	auth.pjwstk.edu.pl
NOERROR	ns1.pjwstk.edu.pl
NOERROR	biblioteka.pjwstk.edu.pl
NOERROR	www.japonski.pjwstk.edu.pl
NOERROR	kwestura.pjwstk.edu.pl
NOERROR	www.tenis.pjwstk.edu.pl
NXDOMAIN	www.encode.pjwstk.edu.pl
NXDOMAIN	hcs80.pjwstk.edu.pl
NXDOMAIN	www.paintball.pjwstk.edu.pl
NOERROR	asmyktest.pjwstk.edu.pl
NXDOMAIN	kmkt.pjwstk.edu.pl
NOERROR	repin.pjwstk.edu.pl
NOERROR	lab009.pjwstk.edu.pl
NOERROR	lab118.pjwstk.edu.pl
NOERROR	www.acs.pjwstk.edu.pl
NOERROR	www.iccvg2010.pjwstk.edu.pl
NXDOMAIN	www.opsview.pjwstk.edu.pl
NXDOMAIN	mgr.pjwstk.edu.pl
NOERROR	lab003.pjwstk.edu.pl
NOERROR	sftp.pjwstk.edu.pl
NXDOMAIN	www.kuchnia.pjwstk.edu.pl
NOERROR	www.lemon.pjwstk.edu.pl
NOERROR	www.aikido.pjwstk.edu.pl
NXDOMAIN	n.pjwstk.edu.pl
