NOERROR	edocente.uaa.edu.py
NOERROR	uaa.edu.py
NOERROR	pagos.uaa.edu.py
NXDOMAIN	tutorias.uaa.edu.py
NOERROR	mail.uaa.edu.py
NOERROR	www.jit-cita.uaa.edu.py
NXDOMAIN	ecampus2.uaa.edu.py
NOERROR	ecampus.uaa.edu.py
NOERROR	postgrado.uaa.edu.py
NOERROR	cacti.uaa.edu.py
NXDOMAIN	tajy.uaa.edu.py
NOERROR	blog.uaa.edu.py
NXDOMAIN	w.uaa.edu.py
NXDOMAIN	www.e.uaa.edu.py
NOERROR	e.uaa.edu.py
NOERROR	e2.uaa.edu.py
NOERROR	app.uaa.edu.py
NOERROR	uaalcue.uaa.edu.py
NOERROR	service.uaa.edu.py
NOERROR	www.uaa.edu.py
NXDOMAIN	mailserver.uaa.edu.py
NOERROR	cel.uaa.edu.py
NXDOMAIN	web1.uaa.edu.py
NOERROR	biblioteca.uaa.edu.py
NOERROR	yvapovo.uaa.edu.py
NOERROR	etrabajo.uaa.edu.py
NOERROR	intranet2.uaa.edu.py
NOERROR	ajedrez.uaa.edu.py
NOERROR	revistacientifica.uaa.edu.py
NOERROR	intranet.uaa.edu.py
