NXDOMAIN	webmail.ucsa.edu.py
NXDOMAIN	webdisk.ucsa.edu.py
NOERROR	av.ucsa.edu.py
NOERROR	apps.ucsa.edu.py
NXDOMAIN	cpanel.ucsa.edu.py
NOERROR	ucsa.edu.py
NOERROR	mail.ucsa.edu.py
NOERROR	www.ucsa.edu.py
NOERROR	autodiscover.ucsa.edu.py
NXDOMAIN	gudurix.ucsa.edu.py
