NXDOMAIN	nat39-38.nat.ucy.ac.cy
NOERROR	nat38-191.nat.ucy.ac.cy
NOERROR	nat5-4.nat.ucy.ac.cy
NOERROR	wn201.grid.ucy.ac.cy
NOERROR	nat37-54.nat.ucy.ac.cy
NOERROR	nat37-224.nat.ucy.ac.cy
NXDOMAIN	nat39-113.nat.ucy.ac.cy
NOERROR	kiosapps.ucy.ac.cy
NOERROR	helpdesk.cs.ucy.ac.cy
NXDOMAIN	ermisweb2.ucy.ac.cy
NXDOMAIN	www2.ece.ucy.ac.cy
NOERROR	nat5-249.nat.ucy.ac.cy
NOERROR	nat36-117.nat.ucy.ac.cy
NOERROR	wn110.grid.ucy.ac.cy
NOERROR	theodoros.mas.ucy.ac.cy
NOERROR	nat30-229.nat.ucy.ac.cy
NXDOMAIN	www.adjectiveatlas.ucy.ac.cy
NOERROR	ssoportal.ucy.ac.cy
NOERROR	nat38-74.nat.ucy.ac.cy
NOERROR	nat38-16.nat.ucy.ac.cy
NOERROR	idp.ucy.ac.cy
NXDOMAIN	mail.edbticdt2021.cs.ucy.ac.cy
NOERROR	www.oceanography.ucy.ac.cy
NXDOMAIN	nat39-172.nat.ucy.ac.cy
NOERROR	nat35-36.nat.ucy.ac.cy
NOERROR	nat37-177.nat.ucy.ac.cy
NXDOMAIN	nat39-176.nat.ucy.ac.cy
NOERROR	indicosrv.phy.ucy.ac.cy
NOERROR	nat35-219.nat.ucy.ac.cy
NOERROR	nat35-243.nat.ucy.ac.cy
NOERROR	www5.cs.ucy.ac.cy
NOERROR	innofuncy.cs.ucy.ac.cy
NOERROR	webboard.cc.ucy.ac.cy
NOERROR	nat5-67.nat.ucy.ac.cy
NOERROR	nat5-95.nat.ucy.ac.cy
NOERROR	nat36-139.nat.ucy.ac.cy
NXDOMAIN	nat39-157.nat.ucy.ac.cy
NOERROR	nat37-134.nat.ucy.ac.cy
NOERROR	nat36-250.nat.ucy.ac.cy
NOERROR	nat37-45.nat.ucy.ac.cy
NOERROR	aambrosios.cs.ucy.ac.cy
NOERROR	nat35-69.nat.ucy.ac.cy
NOERROR	zweb.lib.ucy.ac.cy
NOERROR	nat37-116.nat.ucy.ac.cy
NOERROR	nat36-153.nat.ucy.ac.cy
NOERROR	nat30-242.nat.ucy.ac.cy
NOERROR	bdii201.grid.ucy.ac.cy
NOERROR	nat37-213.nat.ucy.ac.cy
NOERROR	papers.econ.ucy.ac.cy
NOERROR	www.prytanikes.ucy.ac.cy
NXDOMAIN	www.damon.cs.ucy.ac.cy
NOERROR	nat36-129.nat.ucy.ac.cy
NXDOMAIN	nat39-214.nat.ucy.ac.cy
NOERROR	ucyportal.ucy.ac.cy
NXDOMAIN	nat39-248.nat.ucy.ac.cy
NOERROR	nat30-204.nat.ucy.ac.cy
NOERROR	www.dmsl.cs.ucy.ac.cy
NOERROR	nat5-195.nat.ucy.ac.cy
NOERROR	ermis.lib.ucy.ac.cy
NOERROR	nat30-93.nat.ucy.ac.cy
NOERROR	wn119.grid.ucy.ac.cy
NOERROR	nat5-210.nat.ucy.ac.cy
NOERROR	ip9.vega1.ucy.ac.cy
NOERROR	nat5-246.nat.ucy.ac.cy
NOERROR	nat30-185.nat.ucy.ac.cy
NOERROR	nat30-126.nat.ucy.ac.cy
NOERROR	nat5-27.nat.ucy.ac.cy
NOERROR	portal.cs.ucy.ac.cy
NXDOMAIN	www.services.ucy.ac.cy
NXDOMAIN	nat39-78.nat.ucy.ac.cy
NOERROR	nat38-137.nat.ucy.ac.cy
NXDOMAIN	ldap1.csrv.ucy.ac.cy
NOERROR	nat30-71.nat.ucy.ac.cy
NXDOMAIN	www.iam.ucy.ac.cy
NOERROR	ucy.ac.cy
NOERROR	nat30-122.nat.ucy.ac.cy
NOERROR	mbnet.cc.ucy.ac.cy
NOERROR	nat5-232.nat.ucy.ac.cy
NOERROR	nat38-206.nat.ucy.ac.cy
NXDOMAIN	integration.ucy.ac.cy
NOERROR	nat30-241.nat.ucy.ac.cy
NOERROR	nat36-27.nat.ucy.ac.cy
NOERROR	nat35-194.nat.ucy.ac.cy
NOERROR	nat30-42.nat.ucy.ac.cy
NOERROR	nat30-139.nat.ucy.ac.cy
NOERROR	rb101.grid.ucy.ac.cy
NOERROR	altiris.cc.ucy.ac.cy
NOERROR	nat36-231.nat.ucy.ac.cy
NOERROR	nat35-114.nat.ucy.ac.cy
NOERROR	nat38-162.nat.ucy.ac.cy
NOERROR	webboard-old.cc.ucy.ac.cy
NOERROR	wn124.grid.ucy.ac.cy
NXDOMAIN	ariadni.in.cs.ucy.ac.cy
NOERROR	nat38-219.nat.ucy.ac.cy
NOERROR	nat38-243.nat.ucy.ac.cy
NXDOMAIN	nat39-33.nat.ucy.ac.cy
NOERROR	nat35-68.nat.ucy.ac.cy
NOERROR	valert.cs.ucy.ac.cy
NOERROR	sso.ucy.ac.cy
NOERROR	www7.cs.ucy.ac.cy
NXDOMAIN	webmail.edbt2021.cs.ucy.ac.cy
NXDOMAIN	oats-testing.in.cs.ucy.ac.cy
NOERROR	nat30-226.nat.ucy.ac.cy
NOERROR	nat35-106.nat.ucy.ac.cy
NOERROR	nat35-122.nat.ucy.ac.cy
NOERROR	ucynews.ucy.ac.cy
NOERROR	nat38-166.nat.ucy.ac.cy
NOERROR	nat35-205.nat.ucy.ac.cy
NOERROR	nat194.cs.ucy.ac.cy
NOERROR	wn135.grid.ucy.ac.cy
NXDOMAIN	www.mirror.library.ucy.ac.cy
NOERROR	nat36-165.nat.ucy.ac.cy
NOERROR	nat30-2.nat.ucy.ac.cy
NOERROR	nat36-209.nat.ucy.ac.cy
NOERROR	sirius.polytech.ucy.ac.cy
NOERROR	nat30-209.nat.ucy.ac.cy
NOERROR	nat30-217.nat.ucy.ac.cy
NXDOMAIN	www.gnosis.library.ucy.ac.cy
NOERROR	nat35-252.nat.ucy.ac.cy
NOERROR	nat35-49.nat.ucy.ac.cy
NOERROR	nat30-17.nat.ucy.ac.cy
NOERROR	nat38-75.nat.ucy.ac.cy
NOERROR	filesender.ucy.ac.cy
NOERROR	lavoisier.chem.ucy.ac.cy
NOERROR	nat36-182.nat.ucy.ac.cy
NOERROR	nat5-120.nat.ucy.ac.cy
NOERROR	nat36-92.nat.ucy.ac.cy
NOERROR	annfass-srv.cs.ucy.ac.cy
NOERROR	nat30-88.nat.ucy.ac.cy
NOERROR	nat36-145.nat.ucy.ac.cy
NOERROR	nat35-75.nat.ucy.ac.cy
NOERROR	nat37-233.nat.ucy.ac.cy
NXDOMAIN	srvvoice.ucy.ac.cy
NOERROR	nat35-33.nat.ucy.ac.cy
NOERROR	mysite.ucy.ac.cy
NOERROR	nat38-18.nat.ucy.ac.cy
NOERROR	nat36-232.nat.ucy.ac.cy
NXDOMAIN	nat39-125.nat.ucy.ac.cy
NXDOMAIN	nat39-32.nat.ucy.ac.cy
NOERROR	nat5-248.nat.ucy.ac.cy
NOERROR	streamgenie.cc.ucy.ac.cy
NOERROR	webct.cc.ucy.ac.cy
NOERROR	dancedb.cs.ucy.ac.cy
NOERROR	crowdcast.cs.ucy.ac.cy
NOERROR	ap3.cs.ucy.ac.cy
NOERROR	nat30-91.nat.ucy.ac.cy
NOERROR	nat35-220.nat.ucy.ac.cy
NXDOMAIN	nat39-196.nat.ucy.ac.cy
NOERROR	nat35-64.nat.ucy.ac.cy
NOERROR	nat37-227.nat.ucy.ac.cy
NOERROR	nat5-185.nat.ucy.ac.cy
NOERROR	nat38-171.nat.ucy.ac.cy
NOERROR	nat30-208.nat.ucy.ac.cy
NXDOMAIN	av.ucy.ac.cy
NOERROR	nat38-58.nat.ucy.ac.cy
NOERROR	nat37-219.nat.ucy.ac.cy
NXDOMAIN	nat39-187.nat.ucy.ac.cy
NOERROR	nat37-192.nat.ucy.ac.cy
NOERROR	nat35-98.nat.ucy.ac.cy
NOERROR	nat30-159.nat.ucy.ac.cy
NXDOMAIN	nat39-57.nat.ucy.ac.cy
NOERROR	nat35-37.nat.ucy.ac.cy
NOERROR	nagios101.grid.ucy.ac.cy
NOERROR	nat37-153.nat.ucy.ac.cy
NOERROR	nat37-166.nat.ucy.ac.cy
NOERROR	ec2-2013.ucy.ac.cy
NOERROR	nat5-234.nat.ucy.ac.cy
NOERROR	nat36-211.nat.ucy.ac.cy
NXDOMAIN	nat39-62.nat.ucy.ac.cy
NOERROR	nat5-92.nat.ucy.ac.cy
NOERROR	nat35-101.nat.ucy.ac.cy
NOERROR	nat37-198.nat.ucy.ac.cy
NXDOMAIN	nat39-40.nat.ucy.ac.cy
NOERROR	nat5-57.nat.ucy.ac.cy
NOERROR	gr-sunlab.sunlabgp.ucy.ac.cy
NOERROR	nat37-26.nat.ucy.ac.cy
NOERROR	nat36-157.nat.ucy.ac.cy
NOERROR	nat5-167.nat.ucy.ac.cy
NOERROR	nat5-96.nat.ucy.ac.cy
NOERROR	nat35-181.nat.ucy.ac.cy
NOERROR	nat36-72.nat.ucy.ac.cy
NOERROR	nat35-229.nat.ucy.ac.cy
NOERROR	nat37-106.nat.ucy.ac.cy
NOERROR	nat36-142.nat.ucy.ac.cy
NXDOMAIN	edbt2021.cs.ucy.ac.cy
NOERROR	saprouter01.csrv.ucy.ac.cy
NOERROR	nat30-142.nat.ucy.ac.cy
NOERROR	nat30-225.nat.ucy.ac.cy
NOERROR	trikomo.mas.ucy.ac.cy
NXDOMAIN	uofcyprusnet00.ucy.ac.cy
NOERROR	nat37-105.nat.ucy.ac.cy
NOERROR	nwepprod01.ucy.ac.cy
NXDOMAIN	cpcontacts.fm2016.cs.ucy.ac.cy
NOERROR	vconf3.vconf.ucy.ac.cy
NOERROR	nat30-117.nat.ucy.ac.cy
NOERROR	nat36-80.nat.ucy.ac.cy
NOERROR	vconf1.vconf.ucy.ac.cy
NXDOMAIN	nat39-29.nat.ucy.ac.cy
NXDOMAIN	ermis.ucy.ac.cy
NXDOMAIN	nat39-229.nat.ucy.ac.cy
NOERROR	nat38-13.nat.ucy.ac.cy
NOERROR	nat5-26.nat.ucy.ac.cy
NXDOMAIN	nat39-161.nat.ucy.ac.cy
NXDOMAIN	ns3.cs.ucy.ac.cy
NOERROR	nat5-145.nat.ucy.ac.cy
NOERROR	wn114.grid.ucy.ac.cy
NXDOMAIN	webmail.ccgrid2019.ucy.ac.cy
NXDOMAIN	expressc.srvvoice.ucy.ac.cy
NOERROR	ifolder.cc.ucy.ac.cy
NXDOMAIN	testing.cs.ucy.ac.cy
NXDOMAIN	ermisweb2.csrv.ucy.ac.cy
NOERROR	nat37-71.nat.ucy.ac.cy
NXDOMAIN	www.mesarchcollections.ucy.ac.cy
NOERROR	nat30-236.nat.ucy.ac.cy
NXDOMAIN	ppp-201.dialup.ucy.ac.cy
NOERROR	nat5-162.nat.ucy.ac.cy
NOERROR	sstest.ucy.ac.cy
NOERROR	nat37-13.nat.ucy.ac.cy
NOERROR	nat5-172.nat.ucy.ac.cy
NOERROR	nat37-243.nat.ucy.ac.cy
NOERROR	nat35-25.nat.ucy.ac.cy
NOERROR	nat30-33.nat.ucy.ac.cy
NOERROR	nat37-102.nat.ucy.ac.cy
NOERROR	wn101.grid.ucy.ac.cy
NOERROR	nat5-7.nat.ucy.ac.cy
NXDOMAIN	nat39-7.nat.ucy.ac.cy
NXDOMAIN	webdisk.etsd.ucy.ac.cy
NOERROR	kioswebsvr3.ucy.ac.cy
NOERROR	nat5-126.nat.ucy.ac.cy
NOERROR	nat37-69.nat.ucy.ac.cy
NXDOMAIN	nat39-237.nat.ucy.ac.cy
NOERROR	nat35-125.nat.ucy.ac.cy
NOERROR	hep.phy.ucy.ac.cy
NOERROR	nat35-87.nat.ucy.ac.cy
NOERROR	nat38-127.nat.ucy.ac.cy
NOERROR	gauss.mas.ucy.ac.cy
NOERROR	nat35-7.nat.ucy.ac.cy
NOERROR	dbint.lib.ucy.ac.cy
NOERROR	www.foss.ucy.ac.cy
NXDOMAIN	www.radisu01.ucy.ac.cy
NOERROR	nat36-44.nat.ucy.ac.cy
NOERROR	nat37-20.nat.ucy.ac.cy
NXDOMAIN	nat39-154.nat.ucy.ac.cy
NOERROR	mail1.cs.ucy.ac.cy
NOERROR	nat38-113.nat.ucy.ac.cy
NOERROR	nat38-210.nat.ucy.ac.cy
NOERROR	nat38-228.nat.ucy.ac.cy
NOERROR	nat37-43.nat.ucy.ac.cy
NOERROR	nat30-86.nat.ucy.ac.cy
NOERROR	nat37-186.nat.ucy.ac.cy
NOERROR	nat35-16.nat.ucy.ac.cy
NOERROR	scrat.cs.ucy.ac.cy
NXDOMAIN	nat39-146.nat.ucy.ac.cy
NOERROR	neognos1.mas.ucy.ac.cy
NOERROR	thales.ece.ucy.ac.cy
NOERROR	nat30-41.nat.ucy.ac.cy
NOERROR	iasonas.mas.ucy.ac.cy
NOERROR	nat5-1.nat.ucy.ac.cy
NOERROR	pol232.polytech.ucy.ac.cy
NOERROR	nat36-33.nat.ucy.ac.cy
NOERROR	nat37-240.nat.ucy.ac.cy
NOERROR	nat5-15.nat.ucy.ac.cy
NXDOMAIN	ds.cs.ucy.ac.cy
NXDOMAIN	www.ucyweb.ucy.ac.cy
NOERROR	heptaur.ucy.ac.cy
NOERROR	nat35-58.nat.ucy.ac.cy
NOERROR	vconf4.vconf.ucy.ac.cy
NXDOMAIN	nireas.cs.ucy.ac.cy
NOERROR	nat5-50.nat.ucy.ac.cy
NOERROR	nat35-47.nat.ucy.ac.cy
NOERROR	libcats.library.ucy.ac.cy
NOERROR	nat37-56.nat.ucy.ac.cy
NXDOMAIN	nat39-163.nat.ucy.ac.cy
NOERROR	nat30-206.nat.ucy.ac.cy
NOERROR	www.texnopleysi.ucy.ac.cy
NOERROR	nat35-28.nat.ucy.ac.cy
NOERROR	biotextquest.ucy.ac.cy
NOERROR	nat36-154.nat.ucy.ac.cy
NXDOMAIN	www.kiosop.ucy.ac.cy
NXDOMAIN	nat39-167.nat.ucy.ac.cy
NOERROR	nat35-238.nat.ucy.ac.cy
NOERROR	theano.cs.ucy.ac.cy
NOERROR	nat36-173.nat.ucy.ac.cy
NOERROR	diogenes.sharks.ucy.ac.cy
NOERROR	services.ucy.ac.cy
NXDOMAIN	research.ucy.ac.cy
NOERROR	profes2013.cs.ucy.ac.cy
NOERROR	nat38-26.nat.ucy.ac.cy
NOERROR	nat38-222.nat.ucy.ac.cy
NOERROR	nat37-28.nat.ucy.ac.cy
NOERROR	orionas.cs.ucy.ac.cy
NXDOMAIN	nagios.csrv.ucy.ac.cy
NOERROR	politistiko.cc.ucy.ac.cy
NOERROR	nat38-153.nat.ucy.ac.cy
NXDOMAIN	nat39-207.nat.ucy.ac.cy
NOERROR	nat36-217.nat.ucy.ac.cy
NOERROR	nat35-163.nat.ucy.ac.cy
NOERROR	nat30-175.nat.ucy.ac.cy
NOERROR	nat5-241.nat.ucy.ac.cy
NXDOMAIN	nat39-243.nat.ucy.ac.cy
NOERROR	zeusvoting.csrv.ucy.ac.cy
NXDOMAIN	nat39-98.nat.ucy.ac.cy
NOERROR	nat36-81.nat.ucy.ac.cy
NXDOMAIN	nat39-221.nat.ucy.ac.cy
NOERROR	nat5-52.nat.ucy.ac.cy
NXDOMAIN	nat39-11.nat.ucy.ac.cy
NOERROR	nat35-191.nat.ucy.ac.cy
NOERROR	mcu.cc.ucy.ac.cy
NXDOMAIN	nat39-182.nat.ucy.ac.cy
NOERROR	nat5-121.nat.ucy.ac.cy
NOERROR	nat36-228.nat.ucy.ac.cy
NOERROR	cronos.cs.ucy.ac.cy
NOERROR	nat38-5.nat.ucy.ac.cy
NOERROR	nat5-178.nat.ucy.ac.cy
NOERROR	nat5-70.nat.ucy.ac.cy
NOERROR	nat30-171.nat.ucy.ac.cy
NOERROR	2018.mba.ucy.ac.cy
NOERROR	vega-gw1.vega1.ucy.ac.cy
NOERROR	nat37-215.nat.ucy.ac.cy
NOERROR	nat5-72.nat.ucy.ac.cy
NOERROR	nat36-21.nat.ucy.ac.cy
NOERROR	ui201.grid.ucy.ac.cy
NOERROR	nat30-25.nat.ucy.ac.cy
NOERROR	nat35-55.nat.ucy.ac.cy
NOERROR	status.library.ucy.ac.cy
NOERROR	nat5-32.nat.ucy.ac.cy
NOERROR	www.cee.ucy.ac.cy
NOERROR	nat37-122.nat.ucy.ac.cy
NXDOMAIN	nat39-112.nat.ucy.ac.cy
NOERROR	nat37-125.nat.ucy.ac.cy
NOERROR	ip10.vega2.ucy.ac.cy
NOERROR	nat35-23.nat.ucy.ac.cy
NXDOMAIN	zmlb00.csrv.ucy.ac.cy
NOERROR	nat211.cs.ucy.ac.cy
NOERROR	intns2.dns.ucy.ac.cy
NOERROR	svn.cs.ucy.ac.cy
NOERROR	nat37-183.nat.ucy.ac.cy
NXDOMAIN	www.ess.ucy.ac.cy
NOERROR	dsd-seaa2016.cs.ucy.ac.cy
NXDOMAIN	nat39-41.nat.ucy.ac.cy
NOERROR	pol55.polytech.ucy.ac.cy
NXDOMAIN	bannersstest.ucy.ac.cy
NOERROR	nat36-170.nat.ucy.ac.cy
NOERROR	www.multical.ece.ucy.ac.cy
NOERROR	nat38-123.nat.ucy.ac.cy
NOERROR	nat5-245.nat.ucy.ac.cy
NOERROR	nat35-34.nat.ucy.ac.cy
NOERROR	nat38-145.nat.ucy.ac.cy
NOERROR	nat5-84.nat.ucy.ac.cy
NOERROR	nat38-133.nat.ucy.ac.cy
NOERROR	nat5-192.nat.ucy.ac.cy
NOERROR	nat5-31.nat.ucy.ac.cy
NOERROR	nat5-20.nat.ucy.ac.cy
NOERROR	nat30-85.nat.ucy.ac.cy
NOERROR	nat30-1.nat.ucy.ac.cy
NXDOMAIN	nat39-253.nat.ucy.ac.cy
NOERROR	nat35-3.nat.ucy.ac.cy
NOERROR	nat30-29.nat.ucy.ac.cy
NOERROR	www.econ.ucy.ac.cy
NOERROR	www.icsoc2011.cs.ucy.ac.cy
NXDOMAIN	nat39-15.nat.ucy.ac.cy
NOERROR	nat38-57.nat.ucy.ac.cy
NOERROR	nat37-83.nat.ucy.ac.cy
NXDOMAIN	itiswiki.csrv.ucy.ac.cy
NOERROR	nat30-134.nat.ucy.ac.cy
NOERROR	nat5-115.nat.ucy.ac.cy
NOERROR	troodos.biol.ucy.ac.cy
NOERROR	nat5-166.nat.ucy.ac.cy
NOERROR	nat36-30.nat.ucy.ac.cy
NXDOMAIN	ldap2.csrv.ucy.ac.cy
NOERROR	ada.cs.ucy.ac.cy
NOERROR	fidias.cs.ucy.ac.cy
NOERROR	nat30-153.nat.ucy.ac.cy
NOERROR	nat36-53.nat.ucy.ac.cy
NOERROR	ieeesb.ucy.ac.cy
NXDOMAIN	www.ermis.ucy.ac.cy
NXDOMAIN	nat39-174.nat.ucy.ac.cy
NOERROR	cloudstorage.ucy.ac.cy
NOERROR	nat37-251.nat.ucy.ac.cy
NOERROR	nat36-86.nat.ucy.ac.cy
NOERROR	nat5-224.nat.ucy.ac.cy
NOERROR	nat37-70.nat.ucy.ac.cy
NXDOMAIN	nat39-200.nat.ucy.ac.cy
NOERROR	nat37-62.nat.ucy.ac.cy
NOERROR	nat30-38.nat.ucy.ac.cy
NXDOMAIN	www.banssbdev.aasw-servers.ucy.ac.cy
NXDOMAIN	idm04.ucy.ac.cy
NOERROR	nat5-147.nat.ucy.ac.cy
NOERROR	zodia.cc.ucy.ac.cy
NXDOMAIN	mail.etsd.ucy.ac.cy
NOERROR	pol17.polytech.ucy.ac.cy
NOERROR	fw-out.vega1.ucy.ac.cy
NOERROR	wn121.grid.ucy.ac.cy
NOERROR	nat35-224.nat.ucy.ac.cy
NOERROR	bdii101.grid.ucy.ac.cy
NOERROR	genesis.cs.ucy.ac.cy
NOERROR	nat37-23.nat.ucy.ac.cy
NXDOMAIN	www.testracktables.ucy.ac.cy
NOERROR	nat38-161.nat.ucy.ac.cy
NOERROR	nat38-216.nat.ucy.ac.cy
NOERROR	nat38-152.nat.ucy.ac.cy
NOERROR	nat35-208.nat.ucy.ac.cy
NOERROR	nat36-58.nat.ucy.ac.cy
NOERROR	clio.cs.ucy.ac.cy
NOERROR	nat36-14.nat.ucy.ac.cy
NOERROR	imap.cs.ucy.ac.cy
NXDOMAIN	nat39-95.nat.ucy.ac.cy
NXDOMAIN	nat39-21.nat.ucy.ac.cy
NOERROR	redcap.ucy.ac.cy
NOERROR	nat5-201.nat.ucy.ac.cy
NOERROR	www.sitisi.ucy.ac.cy
NOERROR	vp.med.ucy.ac.cy
NXDOMAIN	www.etsd.ucy.ac.cy
NOERROR	nat37-67.nat.ucy.ac.cy
NOERROR	nat5-118.nat.ucy.ac.cy
NXDOMAIN	uofcyprusnet16.cs.ucy.ac.cy
NOERROR	nat30-82.nat.ucy.ac.cy
NOERROR	nat38-187.nat.ucy.ac.cy
NOERROR	nat38-102.nat.ucy.ac.cy
NOERROR	nat30-18.nat.ucy.ac.cy
NOERROR	nat38-185.nat.ucy.ac.cy
NOERROR	humocomp15.cs.ucy.ac.cy
NOERROR	nat5-66.nat.ucy.ac.cy
NOERROR	dms.cs.ucy.ac.cy
NOERROR	videoc.polytech.ucy.ac.cy
NOERROR	nat35-2.nat.ucy.ac.cy
NOERROR	nat38-170.nat.ucy.ac.cy
NOERROR	nat37-50.nat.ucy.ac.cy
NOERROR	nat37-111.nat.ucy.ac.cy
NXDOMAIN	www.librarybeta.ucy.ac.cy
NOERROR	nat37-64.nat.ucy.ac.cy
NOERROR	nat5-129.nat.ucy.ac.cy
NOERROR	nat35-204.nat.ucy.ac.cy
NOERROR	nat38-67.nat.ucy.ac.cy
NOERROR	nat35-166.nat.ucy.ac.cy
NOERROR	cain.cs.ucy.ac.cy
NOERROR	cihs-virtualbox.cs.ucy.ac.cy
NOERROR	nat5-56.nat.ucy.ac.cy
NOERROR	nat38-45.nat.ucy.ac.cy
NOERROR	paracelsus.chem.ucy.ac.cy
NOERROR	nat38-21.nat.ucy.ac.cy
NOERROR	nat36-75.nat.ucy.ac.cy
NOERROR	nat5-197.nat.ucy.ac.cy
NOERROR	livestream.cs.ucy.ac.cy
NOERROR	nat37-100.nat.ucy.ac.cy
NOERROR	lisis.cs.ucy.ac.cy
NXDOMAIN	m.appintbeta.lib.ucy.ac.cy
NXDOMAIN	ariadne.cs.ucy.ac.cy
NOERROR	nat35-46.nat.ucy.ac.cy
NXDOMAIN	nat39-81.nat.ucy.ac.cy
NXDOMAIN	ermisweb3.ucy.ac.cy
NXDOMAIN	nat39-19.nat.ucy.ac.cy
NOERROR	nat37-35.nat.ucy.ac.cy
NOERROR	nat37-14.nat.ucy.ac.cy
NOERROR	www.lexecon.ucy.ac.cy
NOERROR	cp.ucy.ac.cy
NOERROR	internal.cc.ucy.ac.cy
NOERROR	linc.ucy.ac.cy
NOERROR	nat5-59.nat.ucy.ac.cy
NOERROR	www.indico.phy.ucy.ac.cy
NOERROR	nat30-237.nat.ucy.ac.cy
NOERROR	nat35-202.nat.ucy.ac.cy
NXDOMAIN	integration.dev.ucy.ac.cy
NXDOMAIN	cpcontacts.edbt2021.cs.ucy.ac.cy
NXDOMAIN	www.app01.ucy.ac.cy
NOERROR	nat5-61.nat.ucy.ac.cy
NOERROR	nat37-187.nat.ucy.ac.cy
NOERROR	nat30-230.nat.ucy.ac.cy
NOERROR	nat5-114.nat.ucy.ac.cy
NOERROR	nat36-101.nat.ucy.ac.cy
NOERROR	nat30-137.nat.ucy.ac.cy
NOERROR	dmsl.cs.ucy.ac.cy
NOERROR	nat30-95.nat.ucy.ac.cy
NOERROR	nat36-32.nat.ucy.ac.cy
NOERROR	kythreas.polytech.ucy.ac.cy
NOERROR	nat35-149.nat.ucy.ac.cy
NXDOMAIN	www.ucysso.ucy.ac.cy
NOERROR	engwbs03.polytech.ucy.ac.cy
NOERROR	nat37-184.nat.ucy.ac.cy
NOERROR	wn115.grid.ucy.ac.cy
NOERROR	nat36-180.nat.ucy.ac.cy
NOERROR	nat35-26.nat.ucy.ac.cy
NOERROR	nat30-24.nat.ucy.ac.cy
NOERROR	ucitserasmusip2012.ucy.ac.cy
NOERROR	qcd.cc.ucy.ac.cy
NOERROR	dsd2016.cs.ucy.ac.cy
NXDOMAIN	nat39-71.nat.ucy.ac.cy
NXDOMAIN	aias.cs.ucy.ac.cy
NOERROR	nat30-165.nat.ucy.ac.cy
NOERROR	nat38-60.nat.ucy.ac.cy
NOERROR	nat36-134.nat.ucy.ac.cy
NOERROR	nat36-254.nat.ucy.ac.cy
NOERROR	nat36-219.nat.ucy.ac.cy
NOERROR	nat36-39.nat.ucy.ac.cy
NXDOMAIN	www.pwdgis.ucy.ac.cy
NOERROR	nat5-37.nat.ucy.ac.cy
NOERROR	nat36-52.nat.ucy.ac.cy
NOERROR	electrospin.ucy.ac.cy
NXDOMAIN	vcenter6.ucy.ac.cy
NOERROR	nat37-92.nat.ucy.ac.cy
NOERROR	sapeinvoices.ucy.ac.cy
NOERROR	nat5-35.nat.ucy.ac.cy
NOERROR	nat30-253.nat.ucy.ac.cy
NOERROR	nat36-11.nat.ucy.ac.cy
NOERROR	nat38-254.nat.ucy.ac.cy
NXDOMAIN	cscsrv13.cs.ucy.ac.cy
NOERROR	logipaignion.cs.ucy.ac.cy
NOERROR	findosslicense2.cs.ucy.ac.cy
NOERROR	nat38-25.nat.ucy.ac.cy
NOERROR	nat35-71.nat.ucy.ac.cy
NOERROR	cyoceanr1.ocean.ucy.ac.cy
NOERROR	nat30-182.nat.ucy.ac.cy
NXDOMAIN	nat39-158.nat.ucy.ac.cy
NOERROR	nat38-118.nat.ucy.ac.cy
NXDOMAIN	nat39-231.nat.ucy.ac.cy
NOERROR	nat30-98.nat.ucy.ac.cy
NOERROR	sbdii.grid.ucy.ac.cy
NOERROR	www.psychol.ucy.ac.cy
NOERROR	nat37-221.nat.ucy.ac.cy
NOERROR	nat38-20.nat.ucy.ac.cy
NOERROR	mepc81.polytech.ucy.ac.cy
NOERROR	nat35-165.nat.ucy.ac.cy
NXDOMAIN	nat39-215.nat.ucy.ac.cy
NOERROR	athina.cs.ucy.ac.cy
NOERROR	nat5-214.nat.ucy.ac.cy
NOERROR	nat30-136.nat.ucy.ac.cy
NOERROR	nat30-218.nat.ucy.ac.cy
NXDOMAIN	www.itisdb.csrv.ucy.ac.cy
NOERROR	nat38-223.nat.ucy.ac.cy
NOERROR	websrv.cc.ucy.ac.cy
NOERROR	nat36-158.nat.ucy.ac.cy
NXDOMAIN	idm02.csrv.ucy.ac.cy
NOERROR	wn132.grid.ucy.ac.cy
NXDOMAIN	nat39-220.nat.ucy.ac.cy
NOERROR	nat36-23.nat.ucy.ac.cy
NXDOMAIN	nat39-6.nat.ucy.ac.cy
NOERROR	nat30-80.nat.ucy.ac.cy
NOERROR	nat35-43.nat.ucy.ac.cy
NXDOMAIN	www.bannerint.ucy.ac.cy
NOERROR	nat30-26.nat.ucy.ac.cy
NXDOMAIN	hector.cs.ucy.ac.cy
NOERROR	nat36-190.nat.ucy.ac.cy
NOERROR	nat36-55.nat.ucy.ac.cy
NOERROR	itis.ucy.ac.cy
NOERROR	nat38-124.nat.ucy.ac.cy
NOERROR	nat5-55.nat.ucy.ac.cy
NOERROR	csfsprof.cs.ucy.ac.cy
NOERROR	nat35-8.nat.ucy.ac.cy
NOERROR	nat35-84.nat.ucy.ac.cy
NOERROR	nat5-14.nat.ucy.ac.cy
NXDOMAIN	nat39-209.nat.ucy.ac.cy
NOERROR	ap-db1.cs.ucy.ac.cy
NOERROR	nat38-131.nat.ucy.ac.cy
NXDOMAIN	www.master.ucyweb.ucy.ac.cy
NOERROR	sxolikes.library.ucy.ac.cy
NOERROR	nat5-103.nat.ucy.ac.cy
NOERROR	nat38-144.nat.ucy.ac.cy
NOERROR	nat36-94.nat.ucy.ac.cy
NXDOMAIN	wiki.ucy.ac.cy
NXDOMAIN	nat39-36.nat.ucy.ac.cy
NXDOMAIN	nat39-162.nat.ucy.ac.cy
NOERROR	nat30-207.nat.ucy.ac.cy
NXDOMAIN	www.redcap.ucy.ac.cy
NOERROR	nat36-46.nat.ucy.ac.cy
NOERROR	nat5-158.nat.ucy.ac.cy
NOERROR	ce101.grid.ucy.ac.cy
NOERROR	ucytc.cc.ucy.ac.cy
NOERROR	nat5-152.nat.ucy.ac.cy
NOERROR	nat30-11.nat.ucy.ac.cy
NOERROR	nat37-99.nat.ucy.ac.cy
NOERROR	nat37-182.nat.ucy.ac.cy
NOERROR	nat30-223.nat.ucy.ac.cy
NOERROR	bannerss.ucy.ac.cy
NXDOMAIN	bannerinttest.ucy.ac.cy
NOERROR	nat30-120.nat.ucy.ac.cy
NOERROR	nat30-90.nat.ucy.ac.cy
NXDOMAIN	dione.in.cs.ucy.ac.cy
NOERROR	medi2014.cs.ucy.ac.cy
NOERROR	jupiter.cc.ucy.ac.cy
NOERROR	nat37-124.nat.ucy.ac.cy
NOERROR	nat30-212.nat.ucy.ac.cy
NOERROR	pvapps.photovoltaic.ucy.ac.cy
NOERROR	eumedis-cy.cc.ucy.ac.cy
NOERROR	nat35-35.nat.ucy.ac.cy
NXDOMAIN	nat39-39.nat.ucy.ac.cy
NOERROR	www.ecmp.ucy.ac.cy
NOERROR	wn103.grid.ucy.ac.cy
NOERROR	nat35-113.nat.ucy.ac.cy
NOERROR	nat35-81.nat.ucy.ac.cy
NOERROR	nat38-227.nat.ucy.ac.cy
NOERROR	nat38-236.nat.ucy.ac.cy
NOERROR	nat35-155.nat.ucy.ac.cy
NOERROR	leda.sharks.ucy.ac.cy
NXDOMAIN	nat39-189.nat.ucy.ac.cy
NOERROR	nat35-9.nat.ucy.ac.cy
NOERROR	nat5-237.nat.ucy.ac.cy
NOERROR	wn131.grid.ucy.ac.cy
NXDOMAIN	baneisdev.aasw-servers.ucy.ac.cy
NXDOMAIN	melpomene.cs.ucy.ac.cy
NOERROR	nat38-129.nat.ucy.ac.cy
NXDOMAIN	nat39-52.nat.ucy.ac.cy
NXDOMAIN	nat39-219.nat.ucy.ac.cy
NOERROR	langce.ucy.ac.cy
NOERROR	expressedge.ucy.ac.cy
NOERROR	nat37-84.nat.ucy.ac.cy
NOERROR	nat36-50.nat.ucy.ac.cy
NXDOMAIN	nat39-90.nat.ucy.ac.cy
NOERROR	nat37-172.nat.ucy.ac.cy
NOERROR	nat30-79.nat.ucy.ac.cy
NOERROR	newsletters.ucy.ac.cy
NOERROR	nat36-56.nat.ucy.ac.cy
NOERROR	vgate.cs.ucy.ac.cy
NXDOMAIN	www.mybackup.ucy.ac.cy
NOERROR	nat37-36.nat.ucy.ac.cy
NOERROR	gb-adonis.vega1.ucy.ac.cy
NOERROR	melco.cs.ucy.ac.cy
NXDOMAIN	webmail.ucy.ac.cy
NOERROR	nat5-251.nat.ucy.ac.cy
NOERROR	nat35-171.nat.ucy.ac.cy
NOERROR	newdev.ucy.ac.cy
NOERROR	nat36-168.nat.ucy.ac.cy
NOERROR	efollowme.cs.ucy.ac.cy
NOERROR	www.emf.ucy.ac.cy
NOERROR	nat5-104.nat.ucy.ac.cy
NOERROR	www.nrg.ucy.ac.cy
NOERROR	nat5-131.nat.ucy.ac.cy
NOERROR	nat30-89.nat.ucy.ac.cy
NOERROR	nat37-52.nat.ucy.ac.cy
NOERROR	sitisi.ucy.ac.cy
NOERROR	nat37-162.nat.ucy.ac.cy
NOERROR	fedra.lib.ucy.ac.cy
NXDOMAIN	nat39-136.nat.ucy.ac.cy
NXDOMAIN	www.ermisweb1.ucy.ac.cy
NOERROR	ekonomia.cc.ucy.ac.cy
NOERROR	nat30-146.nat.ucy.ac.cy
NOERROR	nat38-226.nat.ucy.ac.cy
NOERROR	is-reporter.ucy.ac.cy
NOERROR	nat36-213.nat.ucy.ac.cy
NOERROR	pol53.polytech.ucy.ac.cy
NOERROR	nat5-110.nat.ucy.ac.cy
NOERROR	blackboard.ucy.ac.cy
NXDOMAIN	nat39-212.nat.ucy.ac.cy
NOERROR	nselene.cs.ucy.ac.cy
NXDOMAIN	www.libcats.library.ucy.ac.cy
NOERROR	nat35-103.nat.ucy.ac.cy
NOERROR	streamingsrv.vconf.ucy.ac.cy
NOERROR	nat36-89.nat.ucy.ac.cy
NOERROR	wn139.grid.ucy.ac.cy
NOERROR	plethon.grid.ucy.ac.cy
NOERROR	nat37-110.nat.ucy.ac.cy
NOERROR	nat38-172.nat.ucy.ac.cy
NOERROR	biodiversitylab.ucy.ac.cy
NOERROR	nat36-68.nat.ucy.ac.cy
NXDOMAIN	nat39-89.nat.ucy.ac.cy
NOERROR	nat38-181.nat.ucy.ac.cy
NOERROR	nat36-215.nat.ucy.ac.cy
NXDOMAIN	radisu01.ucy.ac.cy
NOERROR	ip13.vega1.ucy.ac.cy
NXDOMAIN	itisdb.csrv.ucy.ac.cy
NOERROR	nat30-121.nat.ucy.ac.cy
NOERROR	nat5-91.nat.ucy.ac.cy
NOERROR	ns1.ucy.ac.cy
NOERROR	nat36-54.nat.ucy.ac.cy
NOERROR	mail.cc.ucy.ac.cy
NOERROR	nat35-162.nat.ucy.ac.cy
NOERROR	nat35-178.nat.ucy.ac.cy
NOERROR	lexecon.ucy.ac.cy
NOERROR	planetlab-2.cs.ucy.ac.cy
NOERROR	nat30-108.nat.ucy.ac.cy
NOERROR	nat30-177.nat.ucy.ac.cy
NXDOMAIN	nas2.lib.ucy.ac.cy
NOERROR	nat5-223.nat.ucy.ac.cy
NOERROR	nat37-9.nat.ucy.ac.cy
NOERROR	nat37-104.nat.ucy.ac.cy
NOERROR	nat30-198.nat.ucy.ac.cy
NOERROR	nat38-217.nat.ucy.ac.cy
NXDOMAIN	nat39-50.nat.ucy.ac.cy
NXDOMAIN	prv-gw.prv.ucy.ac.cy
NOERROR	nat36-9.nat.ucy.ac.cy
NOERROR	feswitch1.cc.ucy.ac.cy
NOERROR	nat38-19.nat.ucy.ac.cy
NXDOMAIN	nat39-54.nat.ucy.ac.cy
NOERROR	nat37-58.nat.ucy.ac.cy
NXDOMAIN	nat39-218.nat.ucy.ac.cy
NOERROR	nat38-46.nat.ucy.ac.cy
NOERROR	nat30-112.nat.ucy.ac.cy
NOERROR	homer.cs.ucy.ac.cy
NOERROR	nat36-147.nat.ucy.ac.cy
NOERROR	nat30-45.nat.ucy.ac.cy
NOERROR	its.cs.ucy.ac.cy
NOERROR	amga101.grid.ucy.ac.cy
NOERROR	nat36-185.nat.ucy.ac.cy
NOERROR	tbd.cs.ucy.ac.cy
NOERROR	thetis.sharks.ucy.ac.cy
NOERROR	nat36-16.nat.ucy.ac.cy
NOERROR	nat37-41.nat.ucy.ac.cy
NOERROR	nat206.cs.ucy.ac.cy
NXDOMAIN	ssointbeta2.lib.ucy.ac.cy
NOERROR	nat36-10.nat.ucy.ac.cy
NXDOMAIN	www.dev.ucy-web-server-test.ucy.ac.cy
NOERROR	nat36-93.nat.ucy.ac.cy
NOERROR	smartcampus.ucy.ac.cy
NOERROR	vpnholisticlab.ucy.ac.cy
NOERROR	isd2008.cs.ucy.ac.cy
NOERROR	atropos.cc.ucy.ac.cy
NXDOMAIN	nat39-225.nat.ucy.ac.cy
NXDOMAIN	zmbox01.csrv.ucy.ac.cy
NOERROR	nat38-44.nat.ucy.ac.cy
NOERROR	nat37-97.nat.ucy.ac.cy
NXDOMAIN	zmbox03.csrv.ucy.ac.cy
NOERROR	nat5-226.nat.ucy.ac.cy
NOERROR	ucyvoicelive.ucy.ac.cy
NXDOMAIN	nat39-13.nat.ucy.ac.cy
NOERROR	nat30-5.nat.ucy.ac.cy
NOERROR	www.ecsa2008.cs.ucy.ac.cy
NOERROR	wmslb101.grid.ucy.ac.cy
NOERROR	nat5-18.nat.ucy.ac.cy
NOERROR	pol51.polytech.ucy.ac.cy
NOERROR	nat5-254.nat.ucy.ac.cy
NOERROR	nat37-230.nat.ucy.ac.cy
NOERROR	nat198.cs.ucy.ac.cy
NOERROR	nat5-5.nat.ucy.ac.cy
NXDOMAIN	dev.ucy-web-server-test.ucy.ac.cy
NXDOMAIN	nat39-73.nat.ucy.ac.cy
NXDOMAIN	nat39-185.nat.ucy.ac.cy
NOERROR	nat35-20.nat.ucy.ac.cy
NXDOMAIN	racktables.csrv.ucy.ac.cy
NOERROR	nat38-151.nat.ucy.ac.cy
NOERROR	acs.prv.ucy.ac.cy
NOERROR	m.webint.lib.ucy.ac.cy
NOERROR	csiot.cs.ucy.ac.cy
NOERROR	mediaserver.cs.ucy.ac.cy
NOERROR	nat37-76.nat.ucy.ac.cy
NOERROR	nat38-29.nat.ucy.ac.cy
NOERROR	nat38-40.nat.ucy.ac.cy
NXDOMAIN	cpanel.edbt2021.cs.ucy.ac.cy
NOERROR	kioswebsvr1.ucy.ac.cy
NOERROR	nat36-34.nat.ucy.ac.cy
NOERROR	ip12.vega1.ucy.ac.cy
NOERROR	nat30-162.nat.ucy.ac.cy
NXDOMAIN	nat39-9.nat.ucy.ac.cy
NXDOMAIN	msdnaa.cs.ucy.ac.cy
NOERROR	xeno.biol.ucy.ac.cy
NOERROR	nat35-214.nat.ucy.ac.cy
NOERROR	media.ucy.ac.cy
NOERROR	engwbs02.polytech.ucy.ac.cy
NOERROR	nat5-140.nat.ucy.ac.cy
NOERROR	teras.cc.ucy.ac.cy
NXDOMAIN	nat39-159.nat.ucy.ac.cy
NOERROR	nat30-132.nat.ucy.ac.cy
NOERROR	nat36-159.nat.ucy.ac.cy
NXDOMAIN	antispam.cc.ucy.ac.cy
NOERROR	nat36-61.nat.ucy.ac.cy
NOERROR	nat212.cs.ucy.ac.cy
NOERROR	danae.polytech.ucy.ac.cy
NXDOMAIN	nat39-236.nat.ucy.ac.cy
NOERROR	smartpark.cs.ucy.ac.cy
NOERROR	www.pr.ucy.ac.cy
NOERROR	lekythos.library.ucy.ac.cy
NOERROR	nat5-97.nat.ucy.ac.cy
NOERROR	prometheus.grid.ucy.ac.cy
NOERROR	nat37-238.nat.ucy.ac.cy
NOERROR	nat36-45.nat.ucy.ac.cy
NOERROR	hermes.csrv.ucy.ac.cy
NOERROR	karavas.polytech.ucy.ac.cy
NOERROR	biophys.cc.ucy.ac.cy
NOERROR	kronos.ucy.ac.cy
NXDOMAIN	baninb.ucy.ac.cy
NXDOMAIN	ldap.csrv.ucy.ac.cy
NOERROR	webmail.cs.ucy.ac.cy
NOERROR	nat30-13.nat.ucy.ac.cy
NXDOMAIN	uofcyprusnet17.cs.ucy.ac.cy
NOERROR	fol.ucy.ac.cy
NOERROR	nat36-106.nat.ucy.ac.cy
NOERROR	wn122.grid.ucy.ac.cy
NXDOMAIN	www.testredcap.ucy.ac.cy
NOERROR	nat37-246.nat.ucy.ac.cy
NOERROR	nat37-16.nat.ucy.ac.cy
NOERROR	nat35-210.nat.ucy.ac.cy
NXDOMAIN	smtpint2.csrv.ucy.ac.cy
NOERROR	rayzit.cs.ucy.ac.cy
NOERROR	nat30-8.nat.ucy.ac.cy
NOERROR	nat36-214.nat.ucy.ac.cy
NXDOMAIN	nat39-14.nat.ucy.ac.cy
NOERROR	ucyweb.ucy.ac.cy
NOERROR	nat37-193.nat.ucy.ac.cy
NOERROR	wn106.grid.ucy.ac.cy
NOERROR	nat36-41.nat.ucy.ac.cy
NOERROR	nat35-10.nat.ucy.ac.cy
NOERROR	nat36-63.nat.ucy.ac.cy
NXDOMAIN	nat39-67.nat.ucy.ac.cy
NOERROR	nat38-59.nat.ucy.ac.cy
NOERROR	nat38-202.nat.ucy.ac.cy
NOERROR	foodscanner.cs.ucy.ac.cy
NOERROR	nat38-84.nat.ucy.ac.cy
NOERROR	nat37-131.nat.ucy.ac.cy
NOERROR	tvm.cs.ucy.ac.cy
NOERROR	entercy.cs.ucy.ac.cy
NXDOMAIN	www.dcim-srv.dcim.ucy.ac.cy
NXDOMAIN	baninbdev.aasw-servers.ucy.ac.cy
NXDOMAIN	nat39-8.nat.ucy.ac.cy
NOERROR	nat5-22.nat.ucy.ac.cy
NOERROR	nat30-23.nat.ucy.ac.cy
NOERROR	www.melco.cs.ucy.ac.cy
NOERROR	library.ucy.ac.cy
NOERROR	eceherlfilesvr.ece.ucy.ac.cy
NXDOMAIN	ldap.ucy.ac.cy
NXDOMAIN	mail.live.ucy-web-server.ucy.ac.cy
NXDOMAIN	nat39-228.nat.ucy.ac.cy
NXDOMAIN	galileo.ccs.ucy.ac.cy
NXDOMAIN	nat39-107.nat.ucy.ac.cy
NXDOMAIN	it.lib.ucy.ac.cy
NOERROR	nat30-163.nat.ucy.ac.cy
NOERROR	nat30-30.nat.ucy.ac.cy
NOERROR	nat38-212.nat.ucy.ac.cy
NOERROR	covid19.ucy.ac.cy
NOERROR	nat38-196.nat.ucy.ac.cy
NOERROR	nat36-99.nat.ucy.ac.cy
NOERROR	nat38-176.nat.ucy.ac.cy
NOERROR	nat35-251.nat.ucy.ac.cy
NXDOMAIN	www.print.ucy.ac.cy
NOERROR	cvs.polytech.ucy.ac.cy
NOERROR	nat35-141.nat.ucy.ac.cy
NOERROR	nat5-181.nat.ucy.ac.cy
NOERROR	nat38-6.nat.ucy.ac.cy
NOERROR	nat35-127.nat.ucy.ac.cy
NXDOMAIN	nat39-17.nat.ucy.ac.cy
NOERROR	nat5-219.nat.ucy.ac.cy
NOERROR	sunjes.cc.ucy.ac.cy
NOERROR	nat36-238.nat.ucy.ac.cy
NOERROR	nat38-231.nat.ucy.ac.cy
NOERROR	zdb.lib.ucy.ac.cy
NOERROR	nat37-159.nat.ucy.ac.cy
NXDOMAIN	www.edbticdt2021.cs.ucy.ac.cy
NOERROR	nat30-14.nat.ucy.ac.cy
NXDOMAIN	nat39-53.nat.ucy.ac.cy
NOERROR	imap.ucy.ac.cy
NOERROR	nat5-135.nat.ucy.ac.cy
NOERROR	ucy-web-server-test.ucy.ac.cy
NXDOMAIN	nat39-170.nat.ucy.ac.cy
NXDOMAIN	nat39-75.nat.ucy.ac.cy
NOERROR	nat37-196.nat.ucy.ac.cy
NXDOMAIN	nat39-138.nat.ucy.ac.cy
NOERROR	nat36-197.nat.ucy.ac.cy
NXDOMAIN	www.research.ucy.ac.cy
NOERROR	nat35-41.nat.ucy.ac.cy
NXDOMAIN	www-oty.in.cs.ucy.ac.cy
NOERROR	atlas.mas.ucy.ac.cy
NXDOMAIN	www.ucy-web-server-test.ucy.ac.cy
NOERROR	nat5-33.nat.ucy.ac.cy
NXDOMAIN	nat39-192.nat.ucy.ac.cy
NOERROR	nat30-94.nat.ucy.ac.cy
NXDOMAIN	smtp.ucy.ac.cy
NOERROR	nat30-192.nat.ucy.ac.cy
NOERROR	nat38-7.nat.ucy.ac.cy
NOERROR	nat35-123.nat.ucy.ac.cy
NOERROR	nat30-156.nat.ucy.ac.cy
NXDOMAIN	ntp1.csrv.ucy.ac.cy
NXDOMAIN	nat39-77.nat.ucy.ac.cy
NOERROR	nat38-3.nat.ucy.ac.cy
NOERROR	nat30-60.nat.ucy.ac.cy
NXDOMAIN	testing.in.cs.ucy.ac.cy
NOERROR	nat36-172.nat.ucy.ac.cy
NOERROR	nat35-174.nat.ucy.ac.cy
NOERROR	nat36-189.nat.ucy.ac.cy
NOERROR	www8.cs.ucy.ac.cy
NOERROR	nat36-67.nat.ucy.ac.cy
NOERROR	nat37-168.nat.ucy.ac.cy
NOERROR	nat38-23.nat.ucy.ac.cy
NOERROR	nat5-8.nat.ucy.ac.cy
NXDOMAIN	nat39-123.nat.ucy.ac.cy
NOERROR	nat5-24.nat.ucy.ac.cy
NOERROR	nat5-244.nat.ucy.ac.cy
NXDOMAIN	www.library.ucy.ac.cy
NXDOMAIN	www.bannerinttest.ucy.ac.cy
NOERROR	epum.cs.ucy.ac.cy
NOERROR	endorse.cs.ucy.ac.cy
NOERROR	nat36-114.nat.ucy.ac.cy
NOERROR	biol-gw.biol.ucy.ac.cy
NOERROR	nat5-117.nat.ucy.ac.cy
NOERROR	sfil038.ucy.ac.cy
NOERROR	nat38-79.nat.ucy.ac.cy
NOERROR	nat30-244.nat.ucy.ac.cy
NXDOMAIN	athina.ece.ucy.ac.cy
NXDOMAIN	www.itis.ucy.ac.cy
NOERROR	nat5-36.nat.ucy.ac.cy
NOERROR	multical.polytech.ucy.ac.cy
NOERROR	nat30-16.nat.ucy.ac.cy
NOERROR	nat36-76.nat.ucy.ac.cy
NOERROR	nat30-19.nat.ucy.ac.cy
NOERROR	nat38-215.nat.ucy.ac.cy
NOERROR	nat37-49.nat.ucy.ac.cy
NOERROR	polysemwebsvr2.polytech.ucy.ac.cy
NXDOMAIN	nat39-109.nat.ucy.ac.cy
NOERROR	www.intellicis.ucy.ac.cy
NOERROR	ceeprn01.polytech.ucy.ac.cy
NXDOMAIN	nat39-241.nat.ucy.ac.cy
NOERROR	nat35-30.nat.ucy.ac.cy
NOERROR	nat36-111.nat.ucy.ac.cy
NOERROR	nat37-244.nat.ucy.ac.cy
NOERROR	nat5-102.nat.ucy.ac.cy
NOERROR	pol14.polytech.ucy.ac.cy
NOERROR	nat35-45.nat.ucy.ac.cy
NOERROR	aswebtest.ucy.ac.cy
NOERROR	nat35-192.nat.ucy.ac.cy
NOERROR	wn105.grid.ucy.ac.cy
NOERROR	nat38-66.nat.ucy.ac.cy
NXDOMAIN	faxsrvnew1.ucy.ac.cy
NOERROR	mahallae.ucy.ac.cy
NOERROR	nat37-252.nat.ucy.ac.cy
NOERROR	www3.cs.ucy.ac.cy
NXDOMAIN	www.filesender.ucy.ac.cy
NXDOMAIN	proxy.cs.ucy.ac.cy
NOERROR	nat5-163.nat.ucy.ac.cy
NOERROR	nat35-160.nat.ucy.ac.cy
NOERROR	nat35-212.nat.ucy.ac.cy
NOERROR	nat30-12.nat.ucy.ac.cy
NXDOMAIN	voicemail.srvvoice.ucy.ac.cy
NOERROR	cw2000.cc.ucy.ac.cy
NXDOMAIN	faxsrvnew2.ucy.ac.cy
NOERROR	nat5-161.nat.ucy.ac.cy
NOERROR	nat5-40.nat.ucy.ac.cy
NOERROR	ns3.ucy.ac.cy
NOERROR	ccgrid2019.ucy.ac.cy
NOERROR	nat30-243.nat.ucy.ac.cy
NXDOMAIN	integration.qa.ucy.ac.cy
NOERROR	mobiwis2013.cs.ucy.ac.cy
NOERROR	nat5-157.nat.ucy.ac.cy
NXDOMAIN	nat39-195.nat.ucy.ac.cy
NOERROR	nat201.cs.ucy.ac.cy
NOERROR	nat30-46.nat.ucy.ac.cy
NOERROR	physics.phy.ucy.ac.cy
NOERROR	nat37-226.nat.ucy.ac.cy
NOERROR	nat30-128.nat.ucy.ac.cy
NXDOMAIN	ldap01.csrv.ucy.ac.cy
NXDOMAIN	webdisk.edbticdt2021.cs.ucy.ac.cy
NOERROR	nat200.cs.ucy.ac.cy
NOERROR	nat38-108.nat.ucy.ac.cy
NOERROR	nat38-122.nat.ucy.ac.cy
NOERROR	nat37-123.nat.ucy.ac.cy
NOERROR	nat36-149.nat.ucy.ac.cy
NOERROR	nat30-245.nat.ucy.ac.cy
NXDOMAIN	nat39-148.nat.ucy.ac.cy
NOERROR	adfswp01.ucy.ac.cy
NOERROR	nat35-168.nat.ucy.ac.cy
NOERROR	live.ucy.ac.cy
NOERROR	nat36-95.nat.ucy.ac.cy
NOERROR	nat35-144.nat.ucy.ac.cy
NOERROR	serums.cs.ucy.ac.cy
NOERROR	nat5-105.nat.ucy.ac.cy
NOERROR	nat30-190.nat.ucy.ac.cy
NOERROR	nat38-112.nat.ucy.ac.cy
NOERROR	nat5-151.nat.ucy.ac.cy
NOERROR	nat36-200.nat.ucy.ac.cy
NOERROR	proteins.biol.ucy.ac.cy
NOERROR	nat38-182.nat.ucy.ac.cy
NOERROR	nat37-130.nat.ucy.ac.cy
NOERROR	hub.lib.ucy.ac.cy
NOERROR	nat5-99.nat.ucy.ac.cy
NXDOMAIN	nat39-155.nat.ucy.ac.cy
NOERROR	zmlb01.csrv.ucy.ac.cy
NXDOMAIN	nat39-16.nat.ucy.ac.cy
NXDOMAIN	nat39-204.nat.ucy.ac.cy
NOERROR	www.emphasis.ucy.ac.cy
NOERROR	nat5-9.nat.ucy.ac.cy
NOERROR	nat38-91.nat.ucy.ac.cy
NXDOMAIN	ultrafast.cc.ucy.ac.cy
NOERROR	nat38-197.nat.ucy.ac.cy
NXDOMAIN	vcenter6.vi.ucy.ac.cy
NOERROR	estia.phy.ucy.ac.cy
NOERROR	salamina.polytech.ucy.ac.cy
NOERROR	nat36-105.nat.ucy.ac.cy
NXDOMAIN	zmbox02.csrv.ucy.ac.cy
NOERROR	nat36-82.nat.ucy.ac.cy
NXDOMAIN	nat39-119.nat.ucy.ac.cy
NXDOMAIN	nat39-3.nat.ucy.ac.cy
NOERROR	nat5-17.nat.ucy.ac.cy
NOERROR	www.hermes.ucy.ac.cy
NOERROR	nat36-245.nat.ucy.ac.cy
NOERROR	nat38-179.nat.ucy.ac.cy
NOERROR	gp-polytech.polytech.ucy.ac.cy
NOERROR	egrie2016.ucy.ac.cy
NOERROR	lexecon-experiments.ucy.ac.cy
NOERROR	wn107.grid.ucy.ac.cy
NXDOMAIN	www.ldap1.csrv.ucy.ac.cy
NOERROR	ip4.vega1.ucy.ac.cy
NXDOMAIN	portalsso.qa.ucy.ac.cy
NOERROR	nat37-139.nat.ucy.ac.cy
NOERROR	nat38-49.nat.ucy.ac.cy
NOERROR	cytld.cc.ucy.ac.cy
NOERROR	nat5-236.nat.ucy.ac.cy
NXDOMAIN	nat39-44.nat.ucy.ac.cy
NOERROR	nat37-216.nat.ucy.ac.cy
NOERROR	nat30-170.nat.ucy.ac.cy
NOERROR	nat35-116.nat.ucy.ac.cy
NXDOMAIN	usercheck.ucy.ac.cy
NOERROR	nat37-108.nat.ucy.ac.cy
NOERROR	library2.ucy.ac.cy
NXDOMAIN	www.ldap2.csrv.ucy.ac.cy
NOERROR	fmpriv2016.cs.ucy.ac.cy
NOERROR	ipal.cs.ucy.ac.cy
NOERROR	lekythos.lib.ucy.ac.cy
NOERROR	nat30-173.nat.ucy.ac.cy
NOERROR	nat36-79.nat.ucy.ac.cy
NXDOMAIN	nat39-152.nat.ucy.ac.cy
NOERROR	nat35-15.nat.ucy.ac.cy
NXDOMAIN	nat39-249.nat.ucy.ac.cy
NOERROR	www.its.cs.ucy.ac.cy
NOERROR	medhocnet2012.cs.ucy.ac.cy
NOERROR	nat30-21.nat.ucy.ac.cy
NXDOMAIN	dssweb1.csrv.ucy.ac.cy
NOERROR	www.careersys.ucy.ac.cy
NOERROR	xenopus.biol.ucy.ac.cy
NOERROR	nat37-89.nat.ucy.ac.cy
NOERROR	nat37-210.nat.ucy.ac.cy
NXDOMAIN	www.cronos.cs.ucy.ac.cy
NOERROR	www.leisurescapesarchive.ucy.ac.cy
NOERROR	nat30-222.nat.ucy.ac.cy
NOERROR	nat35-94.nat.ucy.ac.cy
NOERROR	nat35-206.nat.ucy.ac.cy
NOERROR	nat5-30.nat.ucy.ac.cy
NOERROR	nat35-179.nat.ucy.ac.cy
NOERROR	nat37-163.nat.ucy.ac.cy
NOERROR	iloportal.ucy.ac.cy
NOERROR	nat38-82.nat.ucy.ac.cy
NOERROR	nat36-224.nat.ucy.ac.cy
NXDOMAIN	cpcalendars.etsd.ucy.ac.cy
NXDOMAIN	www.kiosapps.ucy.ac.cy
NXDOMAIN	symantec.ucy.ac.cy
NOERROR	commed.ucy.ac.cy
NOERROR	nat36-37.nat.ucy.ac.cy
NXDOMAIN	nat39-213.nat.ucy.ac.cy
NXDOMAIN	afroditi.in.cs.ucy.ac.cy
NOERROR	nat35-121.nat.ucy.ac.cy
NXDOMAIN	zeus.cc.ucy.ac.cy
NOERROR	nat38-250.nat.ucy.ac.cy
NXDOMAIN	nat39-169.nat.ucy.ac.cy
NXDOMAIN	iro.cc.ucy.ac.cy
NOERROR	nat36-193.nat.ucy.ac.cy
NOERROR	nat35-231.nat.ucy.ac.cy
NOERROR	nat38-56.nat.ucy.ac.cy
NOERROR	nat30-172.nat.ucy.ac.cy
NOERROR	nat36-90.nat.ucy.ac.cy
NOERROR	nat30-9.nat.ucy.ac.cy
NOERROR	nat30-7.nat.ucy.ac.cy
NOERROR	nat5-171.nat.ucy.ac.cy
NOERROR	www.leisurescapes.ucy.ac.cy
NXDOMAIN	smtpint.ucy.ac.cy
NXDOMAIN	www.live.ucy-web-server.ucy.ac.cy
NOERROR	ap.cs.ucy.ac.cy
NXDOMAIN	nat39-122.nat.ucy.ac.cy
NOERROR	nat36-125.nat.ucy.ac.cy
NXDOMAIN	zmbox04.csrv.ucy.ac.cy
NOERROR	cyoceans.ocean.ucy.ac.cy
NOERROR	mon201.grid.ucy.ac.cy
NOERROR	nat5-71.nat.ucy.ac.cy
NOERROR	nat37-142.nat.ucy.ac.cy
NOERROR	apps.cs.ucy.ac.cy
NOERROR	nat35-57.nat.ucy.ac.cy
NOERROR	rssis.cs.ucy.ac.cy
NOERROR	arion.cs.ucy.ac.cy
NOERROR	nat35-31.nat.ucy.ac.cy
NOERROR	nat5-205.nat.ucy.ac.cy
NOERROR	nat5-44.nat.ucy.ac.cy
NOERROR	zenix.cs.ucy.ac.cy
NOERROR	nat36-184.nat.ucy.ac.cy
NOERROR	nat37-96.nat.ucy.ac.cy
NOERROR	nat37-248.nat.ucy.ac.cy
NOERROR	nat35-14.nat.ucy.ac.cy
NOERROR	nat35-22.nat.ucy.ac.cy
NOERROR	nat35-239.nat.ucy.ac.cy
NOERROR	nat37-48.nat.ucy.ac.cy
NOERROR	can.ucy.ac.cy
NOERROR	nat35-183.nat.ucy.ac.cy
NXDOMAIN	nat39-97.nat.ucy.ac.cy
NXDOMAIN	nat39-68.nat.ucy.ac.cy
NOERROR	nat5-94.nat.ucy.ac.cy
NXDOMAIN	nat39-66.nat.ucy.ac.cy
NXDOMAIN	nat39-18.nat.ucy.ac.cy
NXDOMAIN	theodora.in.cs.ucy.ac.cy
NOERROR	appcoupons.ucy.ac.cy
NOERROR	photovoltaic.sharks.ucy.ac.cy
NOERROR	webmail2.cc.ucy.ac.cy
NOERROR	oats.cs.ucy.ac.cy
NOERROR	e-learning.ucy.ac.cy
NOERROR	odin.grid.ucy.ac.cy
NOERROR	new.ucy.ac.cy
NOERROR	nat38-150.nat.ucy.ac.cy
NOERROR	nat38-174.nat.ucy.ac.cy
NXDOMAIN	ciscoworks.prv.ucy.ac.cy
NOERROR	nat30-44.nat.ucy.ac.cy
NOERROR	ip7.vega1.ucy.ac.cy
NOERROR	nat5-239.nat.ucy.ac.cy
NOERROR	nat35-112.nat.ucy.ac.cy
NXDOMAIN	www.ucy-web-server.ucy.ac.cy
NOERROR	handoop.grid.ucy.ac.cy
NOERROR	noticeboard.cc.ucy.ac.cy
NOERROR	nat5-175.nat.ucy.ac.cy
NXDOMAIN	www.radius02.ucy.ac.cy
NXDOMAIN	nat39-34.nat.ucy.ac.cy
NOERROR	prntpol.polytech.ucy.ac.cy
NOERROR	nat5-28.nat.ucy.ac.cy
NOERROR	kioslorasvr.ucy.ac.cy
NOERROR	nat36-140.nat.ucy.ac.cy
NOERROR	nat5-133.nat.ucy.ac.cy
NOERROR	nat30-59.nat.ucy.ac.cy
NOERROR	vcgateway.cc.ucy.ac.cy
NOERROR	nat38-207.nat.ucy.ac.cy
NOERROR	nat36-251.nat.ucy.ac.cy
NOERROR	nat30-246.nat.ucy.ac.cy
NOERROR	nat35-13.nat.ucy.ac.cy
NOERROR	nat5-76.nat.ucy.ac.cy
NXDOMAIN	lekythoslocal.lib.ucy.ac.cy
NOERROR	nat38-239.nat.ucy.ac.cy
NOERROR	nat35-18.nat.ucy.ac.cy
NOERROR	nat30-215.nat.ucy.ac.cy
NOERROR	nat36-243.nat.ucy.ac.cy
NXDOMAIN	openspecimen.ucy.ac.cy
NOERROR	nat38-107.nat.ucy.ac.cy
NOERROR	nat215.cs.ucy.ac.cy
NXDOMAIN	portal.dev.ucy.ac.cy
NOERROR	nat5-218.nat.ucy.ac.cy
NOERROR	nat37-249.nat.ucy.ac.cy
NXDOMAIN	baninbdev.ucy.ac.cy
NXDOMAIN	print.ucy.ac.cy
NOERROR	nat5-229.nat.ucy.ac.cy
NOERROR	nat30-130.nat.ucy.ac.cy
NXDOMAIN	www.covid19.ucy.ac.cy
NOERROR	nat38-14.nat.ucy.ac.cy
NOERROR	nat36-120.nat.ucy.ac.cy
NOERROR	nat35-120.nat.ucy.ac.cy
NOERROR	nat36-227.nat.ucy.ac.cy
NOERROR	nat5-39.nat.ucy.ac.cy
NOERROR	nat30-140.nat.ucy.ac.cy
NOERROR	nat35-248.nat.ucy.ac.cy
NOERROR	ap2.cs.ucy.ac.cy
NOERROR	eshop.ucy.ac.cy
NOERROR	haapie.cs.ucy.ac.cy
NOERROR	nat37-208.nat.ucy.ac.cy
NOERROR	nat5-180.nat.ucy.ac.cy
NOERROR	kicss2014.cs.ucy.ac.cy
NOERROR	nat30-114.nat.ucy.ac.cy
NOERROR	nat38-253.nat.ucy.ac.cy
NOERROR	ftp.cs.ucy.ac.cy
NXDOMAIN	nat39-55.nat.ucy.ac.cy
NOERROR	efw2.cc.ucy.ac.cy
NOERROR	nat5-132.nat.ucy.ac.cy
NOERROR	nat5-252.nat.ucy.ac.cy
NXDOMAIN	senatesrv.ucy.ac.cy
NOERROR	nat5-62.nat.ucy.ac.cy
NOERROR	fed.ucy.ac.cy
NOERROR	www.hum.ucy.ac.cy
NOERROR	nat36-97.nat.ucy.ac.cy
NOERROR	nat38-205.nat.ucy.ac.cy
NOERROR	nat30-72.nat.ucy.ac.cy
NOERROR	ditis.cc.ucy.ac.cy
NOERROR	nat37-8.nat.ucy.ac.cy
NXDOMAIN	nat39-144.nat.ucy.ac.cy
NOERROR	nat5-174.nat.ucy.ac.cy
NOERROR	ceecpy03.polytech.ucy.ac.cy
NOERROR	mail2.cs.ucy.ac.cy
NOERROR	nat36-176.nat.ucy.ac.cy
NOERROR	nat38-78.nat.ucy.ac.cy
NXDOMAIN	nemesis.in.cs.ucy.ac.cy
NOERROR	nat5-25.nat.ucy.ac.cy
NOERROR	foodmuseum.cs.ucy.ac.cy
NOERROR	www.annfass-srv.cs.ucy.ac.cy
NOERROR	mailrelay.cc.ucy.ac.cy
NOERROR	nat5-188.nat.ucy.ac.cy
NXDOMAIN	nat39-245.nat.ucy.ac.cy
NOERROR	nat30-65.nat.ucy.ac.cy
NOERROR	orion.polytech.ucy.ac.cy
NOERROR	nat38-103.nat.ucy.ac.cy
NOERROR	nat35-167.nat.ucy.ac.cy
NXDOMAIN	phpmyadmin.in.cs.ucy.ac.cy
NOERROR	nat30-180.nat.ucy.ac.cy
NXDOMAIN	erasmia.in.cs.ucy.ac.cy
NOERROR	nat30-249.nat.ucy.ac.cy
NOERROR	mmenas01.polytech.ucy.ac.cy
NOERROR	nat38-68.nat.ucy.ac.cy
NOERROR	nat30-152.nat.ucy.ac.cy
NOERROR	adjectiveatlas.ucy.ac.cy
NXDOMAIN	nat39-37.nat.ucy.ac.cy
NXDOMAIN	www.bioscience.ucy.ac.cy
NOERROR	nat37-149.nat.ucy.ac.cy
NOERROR	nat38-157.nat.ucy.ac.cy
NOERROR	mmekirasvr.polytech.ucy.ac.cy
NXDOMAIN	radius01.ucy.ac.cy
NOERROR	nat5-176.nat.ucy.ac.cy
NOERROR	nat38-77.nat.ucy.ac.cy
NXDOMAIN	faxsrvnew.ucy.ac.cy
NOERROR	nat196.cs.ucy.ac.cy
NXDOMAIN	ermisweb1.ucy.ac.cy
NOERROR	wn128.grid.ucy.ac.cy
NOERROR	nat30-123.nat.ucy.ac.cy
NOERROR	seit3.cs.ucy.ac.cy
NOERROR	sapssoproxy.csrv.ucy.ac.cy
NOERROR	nat35-53.nat.ucy.ac.cy
NXDOMAIN	nat39-137.nat.ucy.ac.cy
NOERROR	nat35-78.nat.ucy.ac.cy
NXDOMAIN	webmail.edbticdt2021.cs.ucy.ac.cy
NOERROR	nat38-221.nat.ucy.ac.cy
NOERROR	nat36-84.nat.ucy.ac.cy
NOERROR	nat36-22.nat.ucy.ac.cy
NOERROR	nat30-57.nat.ucy.ac.cy
NOERROR	nat35-59.nat.ucy.ac.cy
NXDOMAIN	webdisk.live.ucy-web-server.ucy.ac.cy
NOERROR	nat37-169.nat.ucy.ac.cy
NOERROR	nat38-11.nat.ucy.ac.cy
NOERROR	vals-soc.cs.ucy.ac.cy
NOERROR	nat37-223.nat.ucy.ac.cy
NOERROR	nat5-11.nat.ucy.ac.cy
NOERROR	medica.cs.ucy.ac.cy
NOERROR	seaa2016.cs.ucy.ac.cy
NOERROR	nat36-132.nat.ucy.ac.cy
NOERROR	nat37-90.nat.ucy.ac.cy
NOERROR	survey.ucy.ac.cy
NOERROR	nat5-173.nat.ucy.ac.cy
NOERROR	nat5-106.nat.ucy.ac.cy
NOERROR	citards.cs.ucy.ac.cy
NOERROR	nat37-253.nat.ucy.ac.cy
NOERROR	nat30-194.nat.ucy.ac.cy
NXDOMAIN	cpanel.edbticdt2021.cs.ucy.ac.cy
NOERROR	nat38-81.nat.ucy.ac.cy
NOERROR	nat36-198.nat.ucy.ac.cy
NOERROR	nat38-54.nat.ucy.ac.cy
NOERROR	ucyvpn.ucy.ac.cy
NOERROR	pol52.polytech.ucy.ac.cy
NOERROR	nat30-107.nat.ucy.ac.cy
NOERROR	kiosiotdevsvr.ucy.ac.cy
NOERROR	nat35-5.nat.ucy.ac.cy
NXDOMAIN	idm03.ucy.ac.cy
NXDOMAIN	nat39-96.nat.ucy.ac.cy
NOERROR	nat37-231.nat.ucy.ac.cy
NOERROR	nat35-156.nat.ucy.ac.cy
NOERROR	elia.lib.ucy.ac.cy
NOERROR	nat5-179.nat.ucy.ac.cy
NOERROR	nat35-207.nat.ucy.ac.cy
NOERROR	nat30-234.nat.ucy.ac.cy
NOERROR	nat5-51.nat.ucy.ac.cy
NOERROR	webapps.leventis.ucy.ac.cy
NOERROR	ultrafast.ucy.ac.cy
NOERROR	ssoint.lib.ucy.ac.cy
NOERROR	rayzit1.cs.ucy.ac.cy
NXDOMAIN	websun.cc.ucy.ac.cy
NOERROR	www.mba.ucy.ac.cy
NXDOMAIN	mirto.cs.ucy.ac.cy
NOERROR	nat38-73.nat.ucy.ac.cy
NOERROR	nat36-226.nat.ucy.ac.cy
NOERROR	nat5-242.nat.ucy.ac.cy
NOERROR	kios.ucy.ac.cy
NXDOMAIN	www.afroditi.in.cs.ucy.ac.cy
NXDOMAIN	www.portalsso.ucy.ac.cy
NOERROR	nat38-192.nat.ucy.ac.cy
NOERROR	nat36-127.nat.ucy.ac.cy
NOERROR	filesender2.ucy.ac.cy
NXDOMAIN	nat39-12.nat.ucy.ac.cy
NOERROR	nat37-138.nat.ucy.ac.cy
NOERROR	nat5-86.nat.ucy.ac.cy
NOERROR	pythagoras.mas.ucy.ac.cy
NOERROR	wn116.grid.ucy.ac.cy
NOERROR	privacyanalyzer.cs.ucy.ac.cy
NOERROR	nat36-6.nat.ucy.ac.cy
NOERROR	nat38-136.nat.ucy.ac.cy
NOERROR	nat35-185.nat.ucy.ac.cy
NXDOMAIN	nat39-70.nat.ucy.ac.cy
NXDOMAIN	nat39-115.nat.ucy.ac.cy
NOERROR	nat35-1.nat.ucy.ac.cy
NOERROR	nat36-221.nat.ucy.ac.cy
NOERROR	nat35-133.nat.ucy.ac.cy
NOERROR	nat38-63.nat.ucy.ac.cy
NXDOMAIN	live.ucy-web-server.ucy.ac.cy
NOERROR	engpcnav.polytech.ucy.ac.cy
NOERROR	nat5-127.nat.ucy.ac.cy
NXDOMAIN	nat39-171.nat.ucy.ac.cy
NOERROR	nat30-187.nat.ucy.ac.cy
NOERROR	nat30-191.nat.ucy.ac.cy
NXDOMAIN	nat39-94.nat.ucy.ac.cy
NXDOMAIN	nat39-59.nat.ucy.ac.cy
NOERROR	nat30-52.nat.ucy.ac.cy
NOERROR	nat38-225.nat.ucy.ac.cy
NOERROR	indico.phy.ucy.ac.cy
NOERROR	nat5-230.nat.ucy.ac.cy
NOERROR	nat37-242.nat.ucy.ac.cy
NOERROR	nat37-53.nat.ucy.ac.cy
NOERROR	ip10.vega1.ucy.ac.cy
NOERROR	nat5-16.nat.ucy.ac.cy
NOERROR	nat38-132.nat.ucy.ac.cy
NXDOMAIN	nat39-20.nat.ucy.ac.cy
NXDOMAIN	nat39-5.nat.ucy.ac.cy
NXDOMAIN	www.ccgrid2019.ucy.ac.cy
NOERROR	nat36-122.nat.ucy.ac.cy
NOERROR	wn104.grid.ucy.ac.cy
NXDOMAIN	nat39-128.nat.ucy.ac.cy
NXDOMAIN	nat39-120.nat.ucy.ac.cy
NOERROR	nat5-196.nat.ucy.ac.cy
NOERROR	release.ucy.ac.cy
NXDOMAIN	forum.lib.ucy.ac.cy
NOERROR	nat5-81.nat.ucy.ac.cy
NOERROR	nat38-99.nat.ucy.ac.cy
NOERROR	nat35-29.nat.ucy.ac.cy
NOERROR	nat35-190.nat.ucy.ac.cy
NOERROR	iridacentre.ucy.ac.cy
NXDOMAIN	nat39-45.nat.ucy.ac.cy
NXDOMAIN	vgate2.cs.ucy.ac.cy
NOERROR	nat5-240.nat.ucy.ac.cy
NOERROR	nat37-98.nat.ucy.ac.cy
NOERROR	nat38-183.nat.ucy.ac.cy
NOERROR	cluster.cs.ucy.ac.cy
NOERROR	nat5-247.nat.ucy.ac.cy
NOERROR	nat30-129.nat.ucy.ac.cy
NOERROR	stheereservations.cs.ucy.ac.cy
NOERROR	ektoras.cs.ucy.ac.cy
NOERROR	hum.cc.ucy.ac.cy
NOERROR	wn125.grid.ucy.ac.cy
NOERROR	nat36-138.nat.ucy.ac.cy
NXDOMAIN	nat39-210.nat.ucy.ac.cy
NOERROR	vconf-gw.vconf.ucy.ac.cy
NOERROR	nat36-195.nat.ucy.ac.cy
NXDOMAIN	www.usercheck.ucy.ac.cy
NOERROR	www.grid.ucy.ac.cy
NOERROR	nat5-23.nat.ucy.ac.cy
NOERROR	nat38-163.nat.ucy.ac.cy
NOERROR	nat35-19.nat.ucy.ac.cy
NOERROR	nat202.cs.ucy.ac.cy
NXDOMAIN	nat39-178.nat.ucy.ac.cy
NOERROR	nat37-32.nat.ucy.ac.cy
NOERROR	nat38-139.nat.ucy.ac.cy
NOERROR	nat5-184.nat.ucy.ac.cy
NOERROR	nat36-96.nat.ucy.ac.cy
NOERROR	museum.cs.ucy.ac.cy
NOERROR	leisurescapesarchive.ucy.ac.cy
NOERROR	nat37-133.nat.ucy.ac.cy
NOERROR	smarttrace.cs.ucy.ac.cy
NOERROR	nat38-119.nat.ucy.ac.cy
NOERROR	kiosextapps.ucy.ac.cy
NOERROR	nat35-232.nat.ucy.ac.cy
NOERROR	vpn.ucy.ac.cy
NOERROR	ocean-gw.ocean.ucy.ac.cy
NOERROR	nat36-31.nat.ucy.ac.cy
NOERROR	nat30-68.nat.ucy.ac.cy
NOERROR	emcvideoz.cs.ucy.ac.cy
NOERROR	nat37-94.nat.ucy.ac.cy
NOERROR	gb-aphrodite.vega2.ucy.ac.cy
NOERROR	careersys.ucy.ac.cy
NOERROR	nat30-239.nat.ucy.ac.cy
NOERROR	nat35-247.nat.ucy.ac.cy
NOERROR	nat37-74.nat.ucy.ac.cy
NOERROR	nat38-55.nat.ucy.ac.cy
NOERROR	nat35-147.nat.ucy.ac.cy
NOERROR	nat30-110.nat.ucy.ac.cy
NOERROR	covid19-wiki.ehealthlab.cs.ucy.ac.cy
NOERROR	nat37-175.nat.ucy.ac.cy
NOERROR	nat30-145.nat.ucy.ac.cy
NOERROR	nat37-79.nat.ucy.ac.cy
NXDOMAIN	www.cristobal.cc.ucy.ac.cy
NOERROR	ap1.cs.ucy.ac.cy
NXDOMAIN	nat39-87.nat.ucy.ac.cy
NOERROR	nat37-5.nat.ucy.ac.cy
NOERROR	nat37-2.nat.ucy.ac.cy
NOERROR	nat210.cs.ucy.ac.cy
NOERROR	nat30-250.nat.ucy.ac.cy
NXDOMAIN	cpcontacts.ccgrid2019.ucy.ac.cy
NOERROR	video1.polytech.ucy.ac.cy
NOERROR	nat30-100.nat.ucy.ac.cy
NOERROR	webboard.ucy.ac.cy
NOERROR	nat38-244.nat.ucy.ac.cy
NOERROR	nat37-205.nat.ucy.ac.cy
NOERROR	nat36-26.nat.ucy.ac.cy
NOERROR	nat5-204.nat.ucy.ac.cy
NXDOMAIN	webdisk.ccgrid2019.ucy.ac.cy
NOERROR	nat36-241.nat.ucy.ac.cy
NOERROR	nat35-136.nat.ucy.ac.cy
NOERROR	cyocean03.ocean.ucy.ac.cy
NOERROR	nat35-129.nat.ucy.ac.cy
NOERROR	nat35-131.nat.ucy.ac.cy
NOERROR	nat30-50.nat.ucy.ac.cy
NOERROR	vconf7.vconf.ucy.ac.cy
NOERROR	nat5-187.nat.ucy.ac.cy
NOERROR	nat35-143.nat.ucy.ac.cy
NOERROR	nat35-240.nat.ucy.ac.cy
NXDOMAIN	titan.lib.ucy.ac.cy
NOERROR	nat30-70.nat.ucy.ac.cy
NOERROR	nat30-161.nat.ucy.ac.cy
NXDOMAIN	wiki.lib.ucy.ac.cy
NOERROR	nat37-31.nat.ucy.ac.cy
NOERROR	nat30-53.nat.ucy.ac.cy
NOERROR	nat35-124.nat.ucy.ac.cy
NXDOMAIN	dcim-srv.dcim.ucy.ac.cy
NXDOMAIN	nat39-134.nat.ucy.ac.cy
NOERROR	wn129.grid.ucy.ac.cy
NOERROR	nat30-141.nat.ucy.ac.cy
NXDOMAIN	nat39-26.nat.ucy.ac.cy
NOERROR	nat35-6.nat.ucy.ac.cy
NOERROR	nat37-136.nat.ucy.ac.cy
NOERROR	nat30-125.nat.ucy.ac.cy
NOERROR	nat35-38.nat.ucy.ac.cy
NOERROR	nat37-127.nat.ucy.ac.cy
NOERROR	datacenters.cc.ucy.ac.cy
NXDOMAIN	nat39-252.nat.ucy.ac.cy
NOERROR	nat38-111.nat.ucy.ac.cy
NOERROR	fpas27.chem.ucy.ac.cy
NOERROR	nat30-150.nat.ucy.ac.cy
NXDOMAIN	nat39-142.nat.ucy.ac.cy
NXDOMAIN	www.voicemail.srvvoice.ucy.ac.cy
NXDOMAIN	mysite.dev.ucy.ac.cy
NOERROR	nat37-173.nat.ucy.ac.cy
NXDOMAIN	nat39-247.nat.ucy.ac.cy
NXDOMAIN	nat39-69.nat.ucy.ac.cy
NOERROR	nat36-169.nat.ucy.ac.cy
NOERROR	nat36-51.nat.ucy.ac.cy
NOERROR	nat35-61.nat.ucy.ac.cy
NOERROR	nat35-11.nat.ucy.ac.cy
NOERROR	nat37-204.nat.ucy.ac.cy
NOERROR	www2.cs.ucy.ac.cy
NOERROR	ccp.ucy.ac.cy
NOERROR	biophys.ucy.ac.cy
NOERROR	nat36-199.nat.ucy.ac.cy
NXDOMAIN	www.cronus.ucy.ac.cy
NOERROR	nat38-126.nat.ucy.ac.cy
NOERROR	cp02.csrv.ucy.ac.cy
NOERROR	nat38-24.nat.ucy.ac.cy
NXDOMAIN	www.theodora.in.cs.ucy.ac.cy
NOERROR	nat38-76.nat.ucy.ac.cy
NOERROR	nat30-247.nat.ucy.ac.cy
NOERROR	www.newdev.ucy.ac.cy
NOERROR	nat37-247.nat.ucy.ac.cy
NOERROR	nat35-145.nat.ucy.ac.cy
NOERROR	ip5.vega2.ucy.ac.cy
NOERROR	etsd.ucy.ac.cy
NOERROR	repeat.biol.ucy.ac.cy
NXDOMAIN	nat39-76.nat.ucy.ac.cy
NOERROR	nat36-161.nat.ucy.ac.cy
NOERROR	nat38-37.nat.ucy.ac.cy
NXDOMAIN	nat39-42.nat.ucy.ac.cy
NOERROR	nat38-251.nat.ucy.ac.cy
NOERROR	cristobal.cc.ucy.ac.cy
NOERROR	nat36-70.nat.ucy.ac.cy
NOERROR	ap-db3.cs.ucy.ac.cy
NOERROR	nat35-70.nat.ucy.ac.cy
NOERROR	cs.ucy.ac.cy
NOERROR	nat36-135.nat.ucy.ac.cy
NOERROR	nat37-154.nat.ucy.ac.cy
NOERROR	nat5-146.nat.ucy.ac.cy
NOERROR	nat36-128.nat.ucy.ac.cy
NOERROR	nat37-22.nat.ucy.ac.cy
NXDOMAIN	www.aris.in.cs.ucy.ac.cy
NOERROR	nat5-101.nat.ucy.ac.cy
NOERROR	amga202.grid.ucy.ac.cy
NOERROR	nat5-80.nat.ucy.ac.cy
NOERROR	nat5-2.nat.ucy.ac.cy
NOERROR	telerehabilitation.cs.ucy.ac.cy
NXDOMAIN	nat39-177.nat.ucy.ac.cy
NXDOMAIN	idm01.ucy.ac.cy
NOERROR	nat5-165.nat.ucy.ac.cy
NOERROR	ap-db2.cs.ucy.ac.cy
NOERROR	nat30-54.nat.ucy.ac.cy
NOERROR	nat37-170.nat.ucy.ac.cy
NOERROR	nat35-222.nat.ucy.ac.cy
NOERROR	nat37-113.nat.ucy.ac.cy
NOERROR	nat5-29.nat.ucy.ac.cy
NOERROR	wn140.grid.ucy.ac.cy
NOERROR	nat36-19.nat.ucy.ac.cy
NXDOMAIN	testracktables.ucy.ac.cy
NOERROR	nat36-2.nat.ucy.ac.cy
NOERROR	nat30-176.nat.ucy.ac.cy
NOERROR	ectel2013.cs.ucy.ac.cy
NOERROR	uofcyprusnet01.cc.ucy.ac.cy
NOERROR	nat30-119.nat.ucy.ac.cy
NOERROR	nat35-199.nat.ucy.ac.cy
NXDOMAIN	nat39-108.nat.ucy.ac.cy
NOERROR	nat38-95.nat.ucy.ac.cy
NOERROR	nat38-12.nat.ucy.ac.cy
NOERROR	nat30-147.nat.ucy.ac.cy
NOERROR	ucy-web-server.ucy.ac.cy
NOERROR	nat35-32.nat.ucy.ac.cy
NOERROR	nat38-242.nat.ucy.ac.cy
NOERROR	wn202.grid.ucy.ac.cy
NOERROR	dalida.cc.ucy.ac.cy
NOERROR	nat5-107.nat.ucy.ac.cy
NOERROR	nat36-59.nat.ucy.ac.cy
NOERROR	nat36-119.nat.ucy.ac.cy
NOERROR	qcd.ucy.ac.cy
NOERROR	beta.lib.ucy.ac.cy
NOERROR	nat30-164.nat.ucy.ac.cy
NOERROR	nat35-203.nat.ucy.ac.cy
NOERROR	nat35-173.nat.ucy.ac.cy
NOERROR	smtpout01.ucy.ac.cy
NOERROR	nat38-92.nat.ucy.ac.cy
NOERROR	nat30-252.nat.ucy.ac.cy
NOERROR	feswitch0.cc.ucy.ac.cy
NOERROR	nat36-239.nat.ucy.ac.cy
NXDOMAIN	nat39-61.nat.ucy.ac.cy
NXDOMAIN	nat39-101.nat.ucy.ac.cy
NXDOMAIN	nat39-184.nat.ucy.ac.cy
NXDOMAIN	www.titan.lib.ucy.ac.cy
NXDOMAIN	www.testsurvey.ucy.ac.cy
NOERROR	ip3.vega2.ucy.ac.cy
NXDOMAIN	ipam14.cs.ucy.ac.cy
NOERROR	nat38-17.nat.ucy.ac.cy
NOERROR	nat35-86.nat.ucy.ac.cy
NOERROR	nat37-87.nat.ucy.ac.cy
NOERROR	www.hep.ucy.ac.cy
NOERROR	wn138.grid.ucy.ac.cy
NXDOMAIN	nat39-153.nat.ucy.ac.cy
NOERROR	diog.polytech.ucy.ac.cy
NOERROR	nat36-88.nat.ucy.ac.cy
NXDOMAIN	jaguar.lib.ucy.ac.cy
NOERROR	nat38-240.nat.ucy.ac.cy
NXDOMAIN	nat39-240.nat.ucy.ac.cy
NOERROR	nat5-189.nat.ucy.ac.cy
NOERROR	nat37-75.nat.ucy.ac.cy
NOERROR	nat38-184.nat.ucy.ac.cy
NOERROR	artemis-out.cs.ucy.ac.cy
NOERROR	nat5-228.nat.ucy.ac.cy
NXDOMAIN	nat39-239.nat.ucy.ac.cy
NOERROR	nat37-220.nat.ucy.ac.cy
NOERROR	apollo.ucy.ac.cy
NOERROR	nat36-171.nat.ucy.ac.cy
NOERROR	nat5-134.nat.ucy.ac.cy
NOERROR	nat35-225.nat.ucy.ac.cy
NOERROR	nat5-182.nat.ucy.ac.cy
NOERROR	nat37-93.nat.ucy.ac.cy
NXDOMAIN	nat39-180.nat.ucy.ac.cy
NXDOMAIN	nat39-51.nat.ucy.ac.cy
NOERROR	nat36-222.nat.ucy.ac.cy
NOERROR	nat5-49.nat.ucy.ac.cy
NOERROR	nat38-165.nat.ucy.ac.cy
NOERROR	nat30-196.nat.ucy.ac.cy
NXDOMAIN	themis.cs.ucy.ac.cy
NOERROR	nat5-113.nat.ucy.ac.cy
NOERROR	nat5-243.nat.ucy.ac.cy
NOERROR	arodes.mas.ucy.ac.cy
NOERROR	nat38-43.nat.ucy.ac.cy
NOERROR	nat30-83.nat.ucy.ac.cy
NOERROR	nat5-253.nat.ucy.ac.cy
NOERROR	nat35-52.nat.ucy.ac.cy
NOERROR	nat36-137.nat.ucy.ac.cy
NOERROR	nat36-188.nat.ucy.ac.cy
NOERROR	nat5-6.nat.ucy.ac.cy
NOERROR	portal.ucy.ac.cy
NOERROR	nat37-158.nat.ucy.ac.cy
NOERROR	nat37-151.nat.ucy.ac.cy
NOERROR	nat36-100.nat.ucy.ac.cy
NOERROR	imap1.cs.ucy.ac.cy
NOERROR	selene.cs.ucy.ac.cy
NOERROR	nat36-85.nat.ucy.ac.cy
NOERROR	nat37-17.nat.ucy.ac.cy
NOERROR	ecoop08.cs.ucy.ac.cy
NXDOMAIN	nat39-201.nat.ucy.ac.cy
NOERROR	nat35-17.nat.ucy.ac.cy
NOERROR	nat36-206.nat.ucy.ac.cy
NOERROR	kentucytool.ucy.ac.cy
NOERROR	nat36-38.nat.ucy.ac.cy
NOERROR	nat36-164.nat.ucy.ac.cy
NOERROR	nat30-144.nat.ucy.ac.cy
NOERROR	abel.cs.ucy.ac.cy
NOERROR	prtlweb03.csrv.ucy.ac.cy
NOERROR	nat38-28.nat.ucy.ac.cy
NOERROR	nat5-47.nat.ucy.ac.cy
NOERROR	inform.cs.ucy.ac.cy
NOERROR	nat37-10.nat.ucy.ac.cy
NOERROR	polysemwebsvr.polytech.ucy.ac.cy
NOERROR	platonas.lib.ucy.ac.cy
NOERROR	nat35-241.nat.ucy.ac.cy
NOERROR	nat5-199.nat.ucy.ac.cy
NOERROR	nat30-15.nat.ucy.ac.cy
NXDOMAIN	presence.srvvoice.ucy.ac.cy
NOERROR	nat38-135.nat.ucy.ac.cy
NOERROR	cwspi.cs.ucy.ac.cy
NOERROR	nat5-153.nat.ucy.ac.cy
NOERROR	ucyssoportal.ucy.ac.cy
NOERROR	nat38-35.nat.ucy.ac.cy
NXDOMAIN	nas.lib.ucy.ac.cy
NOERROR	nat38-85.nat.ucy.ac.cy
NOERROR	www.psm.ucy.ac.cy
NOERROR	nat37-88.nat.ucy.ac.cy
NOERROR	nat30-219.nat.ucy.ac.cy
NOERROR	nat36-1.nat.ucy.ac.cy
NOERROR	nat30-220.nat.ucy.ac.cy
NXDOMAIN	evterpi.cs.ucy.ac.cy
NOERROR	grid.ucy.ac.cy
NOERROR	nat38-159.nat.ucy.ac.cy
NOERROR	senatesrv.leventis.ucy.ac.cy
NOERROR	nat37-180.nat.ucy.ac.cy
NOERROR	librarybeta.ucy.ac.cy
NXDOMAIN	cpcontacts.etsd.ucy.ac.cy
NXDOMAIN	ipam.cs.ucy.ac.cy
NOERROR	exams.cs.ucy.ac.cy
NOERROR	events.ucy.ac.cy
NOERROR	nat37-47.nat.ucy.ac.cy
NOERROR	www2.ucy.ac.cy
NOERROR	nat5-109.nat.ucy.ac.cy
NOERROR	applications.ucy.ac.cy
NOERROR	nat36-233.nat.ucy.ac.cy
NOERROR	wiki.cs.ucy.ac.cy
NOERROR	api.ucy.ac.cy
NOERROR	nat38-39.nat.ucy.ac.cy
NOERROR	nat30-99.nat.ucy.ac.cy
NOERROR	nat38-211.nat.ucy.ac.cy
NXDOMAIN	nat39-250.nat.ucy.ac.cy
NOERROR	nat5-159.nat.ucy.ac.cy
NOERROR	adaptiveweb.cs.ucy.ac.cy
NOERROR	nat30-228.nat.ucy.ac.cy
NXDOMAIN	www.cc.ucy.ac.cy
NOERROR	ikaros.mas.ucy.ac.cy
NOERROR	nat37-190.nat.ucy.ac.cy
NOERROR	www.cs.ucy.ac.cy
NOERROR	nat30-135.nat.ucy.ac.cy
NXDOMAIN	www.openspecimen.ucy.ac.cy
NOERROR	nat30-81.nat.ucy.ac.cy
NOERROR	nat35-91.nat.ucy.ac.cy
NOERROR	nat38-32.nat.ucy.ac.cy
NOERROR	nat37-4.nat.ucy.ac.cy
NOERROR	nat38-175.nat.ucy.ac.cy
NOERROR	nat36-174.nat.ucy.ac.cy
NOERROR	nat35-184.nat.ucy.ac.cy
NOERROR	nat38-89.nat.ucy.ac.cy
NOERROR	nat35-242.nat.ucy.ac.cy
NOERROR	nat36-29.nat.ucy.ac.cy
NOERROR	nat37-181.nat.ucy.ac.cy
NOERROR	nat5-183.nat.ucy.ac.cy
NOERROR	structure.biol.ucy.ac.cy
NOERROR	www.mind2c.cs.ucy.ac.cy
NOERROR	nat30-35.nat.ucy.ac.cy
NOERROR	nat36-179.nat.ucy.ac.cy
NOERROR	nat35-250.nat.ucy.ac.cy
NOERROR	nat5-74.nat.ucy.ac.cy
NXDOMAIN	nicosia.ccs.ucy.ac.cy
NOERROR	leonardo.chem.ucy.ac.cy
NXDOMAIN	nat39-86.nat.ucy.ac.cy
NOERROR	wmslb103.grid.ucy.ac.cy
NOERROR	mirror.cs.ucy.ac.cy
NOERROR	prtlsso.csrv.ucy.ac.cy
NOERROR	sms-server-switch.cc.ucy.ac.cy
NOERROR	www.ucy.ac.cy
NOERROR	nat30-4.nat.ucy.ac.cy
NOERROR	nat35-244.nat.ucy.ac.cy
NOERROR	nat37-176.nat.ucy.ac.cy
NOERROR	nat36-25.nat.ucy.ac.cy
NOERROR	amga201.grid.ucy.ac.cy
NOERROR	nat37-147.nat.ucy.ac.cy
NOERROR	nat30-169.nat.ucy.ac.cy
NOERROR	www.ekonomia.ucy.ac.cy
NXDOMAIN	ermisweb4.csrv.ucy.ac.cy
NOERROR	nat36-151.nat.ucy.ac.cy
NOERROR	nat37-11.nat.ucy.ac.cy
NXDOMAIN	www.baneisdev.aasw-servers.ucy.ac.cy
NOERROR	nat36-216.nat.ucy.ac.cy
NOERROR	nat30-155.nat.ucy.ac.cy
NOERROR	nat36-24.nat.ucy.ac.cy
NXDOMAIN	surveys.ucy.ac.cy
NOERROR	intranet.sunlabgp.ucy.ac.cy
NOERROR	nat35-201.nat.ucy.ac.cy
NOERROR	nat37-38.nat.ucy.ac.cy
NOERROR	nat36-126.nat.ucy.ac.cy
NXDOMAIN	nas3.lib.ucy.ac.cy
NOERROR	noticeboard.ucy.ac.cy
NOERROR	nat5-89.nat.ucy.ac.cy
NOERROR	nat36-175.nat.ucy.ac.cy
NOERROR	nat35-109.nat.ucy.ac.cy
NOERROR	nat38-168.nat.ucy.ac.cy
NOERROR	nat36-62.nat.ucy.ac.cy
NOERROR	www.proy.ucy.ac.cy
NOERROR	kelvege.ucy.ac.cy
NOERROR	smtp2.cs.ucy.ac.cy
NOERROR	psm.ucy.ac.cy
NOERROR	baneis.ucy.ac.cy
NOERROR	cp01.csrv.ucy.ac.cy
NXDOMAIN	nat39-117.nat.ucy.ac.cy
NOERROR	nat38-96.nat.ucy.ac.cy
NOERROR	nat30-227.nat.ucy.ac.cy
NOERROR	socialenergy.cs.ucy.ac.cy
NOERROR	morfou.chem.ucy.ac.cy
NOERROR	nat36-143.nat.ucy.ac.cy
NOERROR	nat35-253.nat.ucy.ac.cy
NOERROR	nat30-3.nat.ucy.ac.cy
NOERROR	nat37-82.nat.ucy.ac.cy
NXDOMAIN	nat39-203.nat.ucy.ac.cy
NOERROR	ups.cc.ucy.ac.cy
NOERROR	nat5-207.nat.ucy.ac.cy
NOERROR	editor.annfass-srv.cs.ucy.ac.cy
NXDOMAIN	aquila.ucy.ac.cy
NXDOMAIN	www.senatesrv.ucy.ac.cy
NXDOMAIN	adqa01.ucy.ac.cy
NOERROR	firewatch.cs.ucy.ac.cy
NOERROR	iam.ucy.ac.cy
NOERROR	nat36-104.nat.ucy.ac.cy
NXDOMAIN	mysite.qa.ucy.ac.cy
NXDOMAIN	cpanel.etsd.ucy.ac.cy
NOERROR	nat38-71.nat.ucy.ac.cy
NOERROR	nat38-83.nat.ucy.ac.cy
NOERROR	nat35-180.nat.ucy.ac.cy
NOERROR	nat36-191.nat.ucy.ac.cy
NOERROR	nat37-143.nat.ucy.ac.cy
NOERROR	www.idc2009.cs.ucy.ac.cy
NXDOMAIN	portalsso.ucy.ac.cy
NXDOMAIN	www6.cs.ucy.ac.cy
NOERROR	nat37-150.nat.ucy.ac.cy
NOERROR	nat37-27.nat.ucy.ac.cy
NOERROR	nat37-165.nat.ucy.ac.cy
NOERROR	olympia.mas.ucy.ac.cy
NOERROR	sourcecorpus1.ucy.ac.cy
NOERROR	wn102.grid.ucy.ac.cy
NOERROR	pythia.cc.ucy.ac.cy
NOERROR	nat5-130.nat.ucy.ac.cy
NXDOMAIN	nat39-217.nat.ucy.ac.cy
NOERROR	nat35-249.nat.ucy.ac.cy
NOERROR	multical.ece.ucy.ac.cy
NOERROR	yum.cs.ucy.ac.cy
NOERROR	mesarch.ucy.ac.cy
NOERROR	nat30-167.nat.ucy.ac.cy
NXDOMAIN	nat39-22.nat.ucy.ac.cy
NXDOMAIN	www.baneistest.ucy.ac.cy
NOERROR	nat36-207.nat.ucy.ac.cy
NXDOMAIN	www.senatesrv.leventis.ucy.ac.cy
NOERROR	nat5-13.nat.ucy.ac.cy
NXDOMAIN	mail.edbt2021.cs.ucy.ac.cy
NOERROR	nat36-3.nat.ucy.ac.cy
NXDOMAIN	cpanel.ccgrid2019.ucy.ac.cy
NXDOMAIN	faxsrv.ucy.ac.cy
NOERROR	nat36-167.nat.ucy.ac.cy
NOERROR	clio2.cs.ucy.ac.cy
NOERROR	nat35-138.nat.ucy.ac.cy
NOERROR	nat35-172.nat.ucy.ac.cy
NOERROR	thalia.cs.ucy.ac.cy
NOERROR	nat37-33.nat.ucy.ac.cy
NOERROR	nat5-238.nat.ucy.ac.cy
NOERROR	nat35-218.nat.ucy.ac.cy
NOERROR	nemo.psychol.ucy.ac.cy
NOERROR	wn130.grid.ucy.ac.cy
NOERROR	nat37-57.nat.ucy.ac.cy
NOERROR	wn134.grid.ucy.ac.cy
NOERROR	ip13.vega2.ucy.ac.cy
NOERROR	nat35-215.nat.ucy.ac.cy
NOERROR	www.eng.ucy.ac.cy
NOERROR	nat37-117.nat.ucy.ac.cy
NOERROR	etna6.phy.ucy.ac.cy
NOERROR	eudoxos.mas.ucy.ac.cy
NXDOMAIN	nat39-88.nat.ucy.ac.cy
NXDOMAIN	idm01.csrv.ucy.ac.cy
NXDOMAIN	master.ucyweb.ucy.ac.cy
NOERROR	nat37-146.nat.ucy.ac.cy
NOERROR	nat35-146.nat.ucy.ac.cy
NOERROR	nat5-12.nat.ucy.ac.cy
NOERROR	nat37-191.nat.ucy.ac.cy
NXDOMAIN	nat39-179.nat.ucy.ac.cy
NOERROR	cefcy.cs.ucy.ac.cy
NOERROR	nat36-218.nat.ucy.ac.cy
NOERROR	nat5-42.nat.ucy.ac.cy
NOERROR	nat5-73.nat.ucy.ac.cy
NOERROR	elysso.cs.ucy.ac.cy
NOERROR	nat5-203.nat.ucy.ac.cy
NXDOMAIN	zmldap01.csrv.ucy.ac.cy
NOERROR	ecsa2008.cs.ucy.ac.cy
NXDOMAIN	main-firewall.ucy.ac.cy
NOERROR	nat37-229.nat.ucy.ac.cy
NXDOMAIN	nat39-190.nat.ucy.ac.cy
NOERROR	nat35-108.nat.ucy.ac.cy
NOERROR	nat37-207.nat.ucy.ac.cy
NOERROR	nat37-61.nat.ucy.ac.cy
NOERROR	nat5-142.nat.ucy.ac.cy
NOERROR	nat37-241.nat.ucy.ac.cy
NOERROR	zerosrv.sharks.ucy.ac.cy
NOERROR	nat5-3.nat.ucy.ac.cy
NXDOMAIN	soa.qa.ucy.ac.cy
NOERROR	nat30-149.nat.ucy.ac.cy
NOERROR	nat38-230.nat.ucy.ac.cy
NXDOMAIN	nat39-48.nat.ucy.ac.cy
NOERROR	www.cin.cs.ucy.ac.cy
NXDOMAIN	nat39-91.nat.ucy.ac.cy
NOERROR	nat38-134.nat.ucy.ac.cy
NXDOMAIN	nat39-100.nat.ucy.ac.cy
NOERROR	seacorn.cs.ucy.ac.cy
NXDOMAIN	www.symantec.ucy.ac.cy
NOERROR	www-np.ucy.ac.cy
NOERROR	nat38-121.nat.ucy.ac.cy
NOERROR	vega-gw2.vega2.ucy.ac.cy
NXDOMAIN	www.abacus.ucy.ac.cy
NOERROR	nat36-48.nat.ucy.ac.cy
NXDOMAIN	nat39-145.nat.ucy.ac.cy
NXDOMAIN	www.tourist-assistant.cs.ucy.ac.cy
NOERROR	nat38-98.nat.ucy.ac.cy
NXDOMAIN	www.fed.ucy.ac.cy
NXDOMAIN	bimstest.ucy.ac.cy
NOERROR	nat37-80.nat.ucy.ac.cy
NOERROR	intellicis.sharks.ucy.ac.cy
NOERROR	nrg.ucy.ac.cy
NOERROR	www.kios.ucy.ac.cy
NOERROR	nat5-41.nat.ucy.ac.cy
NOERROR	nat37-101.nat.ucy.ac.cy
NOERROR	nat36-155.nat.ucy.ac.cy
NOERROR	nat36-150.nat.ucy.ac.cy
NXDOMAIN	www.adqa01.ucy.ac.cy
NOERROR	nat30-127.nat.ucy.ac.cy
NOERROR	banssb.ucy.ac.cy
NOERROR	nat30-235.nat.ucy.ac.cy
NXDOMAIN	www.bannerss.ucy.ac.cy
NOERROR	ip11.vega2.ucy.ac.cy
NOERROR	nat37-141.nat.ucy.ac.cy
NOERROR	wn117.grid.ucy.ac.cy
NOERROR	upgrade-cn2011.cs.ucy.ac.cy
NXDOMAIN	nat39-232.nat.ucy.ac.cy
NOERROR	nat37-21.nat.ucy.ac.cy
NOERROR	www.mechanism.ucy.ac.cy
NOERROR	tmcm.cc.ucy.ac.cy
NXDOMAIN	abacus.ucy.ac.cy
NOERROR	nat207.cs.ucy.ac.cy
NOERROR	nat35-115.nat.ucy.ac.cy
NOERROR	vidape.cs.ucy.ac.cy
NOERROR	nat5-217.nat.ucy.ac.cy
NOERROR	www.coronatest.ucy.ac.cy
NOERROR	krikitos.phy.ucy.ac.cy
NOERROR	wn141.grid.ucy.ac.cy
NOERROR	nat37-200.nat.ucy.ac.cy
NOERROR	nat36-203.nat.ucy.ac.cy
NXDOMAIN	new.cc.ucy.ac.cy
NOERROR	nat36-204.nat.ucy.ac.cy
NXDOMAIN	lradius.in.cs.ucy.ac.cy
NOERROR	nat35-188.nat.ucy.ac.cy
NOERROR	foss.ucy.ac.cy
NOERROR	www.mesarch.ucy.ac.cy
NXDOMAIN	vgaten.cs.ucy.ac.cy
NOERROR	nat35-39.nat.ucy.ac.cy
NOERROR	api.annfass-srv.cs.ucy.ac.cy
NOERROR	atmail.sunlabgp.ucy.ac.cy
NOERROR	euclid.grid.ucy.ac.cy
NOERROR	nat38-237.nat.ucy.ac.cy
NXDOMAIN	www.newsletters.ucy.ac.cy
NOERROR	nat38-220.nat.ucy.ac.cy
NOERROR	nat5-208.nat.ucy.ac.cy
NOERROR	nat30-160.nat.ucy.ac.cy
NOERROR	nat38-180.nat.ucy.ac.cy
NOERROR	ip6.vega2.ucy.ac.cy
NOERROR	emm.ucy.ac.cy
NXDOMAIN	www.sslvpn.ucy.ac.cy
NOERROR	nat193.cs.ucy.ac.cy
NOERROR	wn108.grid.ucy.ac.cy
NXDOMAIN	www.edbt2021.cs.ucy.ac.cy
NOERROR	wn111.grid.ucy.ac.cy
NOERROR	nat37-225.nat.ucy.ac.cy
NOERROR	nat38-249.nat.ucy.ac.cy
NOERROR	mail-out.cs.ucy.ac.cy
NOERROR	nat37-128.nat.ucy.ac.cy
NXDOMAIN	cronus.ucy.ac.cy
NOERROR	lconline.ucy.ac.cy
NOERROR	nat5-206.nat.ucy.ac.cy
NOERROR	nat36-102.nat.ucy.ac.cy
NXDOMAIN	gorgo.in.cs.ucy.ac.cy
NOERROR	ditis.cs.ucy.ac.cy
NOERROR	nat30-31.nat.ucy.ac.cy
NOERROR	nat35-12.nat.ucy.ac.cy
NOERROR	nat5-93.nat.ucy.ac.cy
NOERROR	nat37-39.nat.ucy.ac.cy
NXDOMAIN	nat39-35.nat.ucy.ac.cy
NOERROR	nat38-30.nat.ucy.ac.cy
NOERROR	www.ieeesb.ucy.ac.cy
NOERROR	nat37-63.nat.ucy.ac.cy
NOERROR	nat36-115.nat.ucy.ac.cy
NOERROR	nat35-175.nat.ucy.ac.cy
NOERROR	nat37-218.nat.ucy.ac.cy
NOERROR	nat38-164.nat.ucy.ac.cy
NOERROR	nat36-152.nat.ucy.ac.cy
NOERROR	nat35-200.nat.ucy.ac.cy
NOERROR	wn127.grid.ucy.ac.cy
NOERROR	nat30-195.nat.ucy.ac.cy
NOERROR	lclinux.ucy.ac.cy
NOERROR	nat30-49.nat.ucy.ac.cy
NOERROR	nat35-66.nat.ucy.ac.cy
NOERROR	nat35-186.nat.ucy.ac.cy
NOERROR	nat36-98.nat.ucy.ac.cy
NOERROR	nat36-146.nat.ucy.ac.cy
NOERROR	nat38-214.nat.ucy.ac.cy
NOERROR	folitoffice.ucy.ac.cy
NXDOMAIN	nat39-47.nat.ucy.ac.cy
NOERROR	nat5-54.nat.ucy.ac.cy
NOERROR	nat37-214.nat.ucy.ac.cy
NOERROR	findosslicense.cs.ucy.ac.cy
NOERROR	musical16.cs.ucy.ac.cy
NOERROR	ip8.vega1.ucy.ac.cy
NOERROR	nat30-240.nat.ucy.ac.cy
NXDOMAIN	cpcalendars.edbt2021.cs.ucy.ac.cy
NOERROR	vconf6.vconf.ucy.ac.cy
NOERROR	pol13.polytech.ucy.ac.cy
NXDOMAIN	nat39-131.nat.ucy.ac.cy
NOERROR	nat37-103.nat.ucy.ac.cy
NOERROR	smartp2p.cs.ucy.ac.cy
NXDOMAIN	nat39-92.nat.ucy.ac.cy
NOERROR	nat30-103.nat.ucy.ac.cy
NOERROR	nat5-64.nat.ucy.ac.cy
NOERROR	ceeprn03.polytech.ucy.ac.cy
NXDOMAIN	www.fidias.cs.ucy.ac.cy
NOERROR	wn109.grid.ucy.ac.cy
NOERROR	nat35-85.nat.ucy.ac.cy
NOERROR	nat30-157.nat.ucy.ac.cy
NXDOMAIN	nat39-143.nat.ucy.ac.cy
NOERROR	nat30-131.nat.ucy.ac.cy
NOERROR	nat214.cs.ucy.ac.cy
NXDOMAIN	webmail.cc.ucy.ac.cy
NOERROR	nat5-90.nat.ucy.ac.cy
NOERROR	nat36-201.nat.ucy.ac.cy
NOERROR	nat5-202.nat.ucy.ac.cy
NXDOMAIN	smtpint1.csrv.ucy.ac.cy
NXDOMAIN	gorgo.cs.ucy.ac.cy
NOERROR	archimides.mas.ucy.ac.cy
NOERROR	nat37-65.nat.ucy.ac.cy
NOERROR	nat5-141.nat.ucy.ac.cy
NOERROR	dbintbeta.lib.ucy.ac.cy
NOERROR	nat30-101.nat.ucy.ac.cy
NXDOMAIN	banssbdev.aasw-servers.ucy.ac.cy
NOERROR	nat38-224.nat.ucy.ac.cy
NOERROR	nat35-216.nat.ucy.ac.cy
NOERROR	nat5-136.nat.ucy.ac.cy
NOERROR	lsg.ucy.ac.cy
NOERROR	nat36-71.nat.ucy.ac.cy
NOERROR	smtp1.cs.ucy.ac.cy
NOERROR	nat37-195.nat.ucy.ac.cy
NOERROR	idea.cs.ucy.ac.cy
NOERROR	acstaff.ucy.ac.cy
NOERROR	nat35-118.nat.ucy.ac.cy
NXDOMAIN	smtpint.csrv.ucy.ac.cy
NOERROR	nat37-112.nat.ucy.ac.cy
NXDOMAIN	nat39-183.nat.ucy.ac.cy
NXDOMAIN	proteus.cc.ucy.ac.cy
NOERROR	nat37-68.nat.ucy.ac.cy
NXDOMAIN	nat39-226.nat.ucy.ac.cy
NOERROR	nat37-145.nat.ucy.ac.cy
NOERROR	nat5-160.nat.ucy.ac.cy
NOERROR	nat35-209.nat.ucy.ac.cy
NOERROR	nat35-227.nat.ucy.ac.cy
NXDOMAIN	www.newvoip.srvvoice.ucy.ac.cy
NOERROR	nat35-228.nat.ucy.ac.cy
NOERROR	nat5-169.nat.ucy.ac.cy
NOERROR	nat35-93.nat.ucy.ac.cy
NOERROR	dionysos.chem.ucy.ac.cy
NOERROR	bibe2012.cs.ucy.ac.cy
NOERROR	nat37-171.nat.ucy.ac.cy
NOERROR	sam2012.ucy.ac.cy
NXDOMAIN	cpcalendars.ccgrid2019.ucy.ac.cy
NXDOMAIN	nat39-85.nat.ucy.ac.cy
NOERROR	wn118.grid.ucy.ac.cy
NOERROR	nat5-78.nat.ucy.ac.cy
NOERROR	tourist-assistant.cs.ucy.ac.cy
NOERROR	nat5-227.nat.ucy.ac.cy
NOERROR	nat5-250.nat.ucy.ac.cy
NOERROR	smartlab.cs.ucy.ac.cy
NOERROR	nat30-221.nat.ucy.ac.cy
NOERROR	nat38-97.nat.ucy.ac.cy
NOERROR	lcweb.ucy.ac.cy
NOERROR	nat5-168.nat.ucy.ac.cy
NOERROR	nat35-90.nat.ucy.ac.cy
NOERROR	nat37-164.nat.ucy.ac.cy
NXDOMAIN	nat39-79.nat.ucy.ac.cy
NOERROR	nat38-246.nat.ucy.ac.cy
NOERROR	rogs.realoptions.ucy.ac.cy
NOERROR	nat37-135.nat.ucy.ac.cy
NOERROR	nat37-235.nat.ucy.ac.cy
NOERROR	webint.lib.ucy.ac.cy
NOERROR	nat5-221.nat.ucy.ac.cy
NOERROR	nat35-130.nat.ucy.ac.cy
NOERROR	nat36-60.nat.ucy.ac.cy
NOERROR	nat37-237.nat.ucy.ac.cy
NOERROR	nat5-119.nat.ucy.ac.cy
NOERROR	nat30-214.nat.ucy.ac.cy
NOERROR	nat30-138.nat.ucy.ac.cy
NOERROR	nat5-123.nat.ucy.ac.cy
NOERROR	nat38-9.nat.ucy.ac.cy
NOERROR	mybackup.ucy.ac.cy
NOERROR	nat5-116.nat.ucy.ac.cy
NOERROR	sdserver.cc.ucy.ac.cy
NOERROR	nat5-38.nat.ucy.ac.cy
NOERROR	nat30-104.nat.ucy.ac.cy
NOERROR	nat35-21.nat.ucy.ac.cy
NOERROR	ess.ucy.ac.cy
NOERROR	nat38-234.nat.ucy.ac.cy
NXDOMAIN	nat39-223.nat.ucy.ac.cy
NOERROR	nat36-205.nat.ucy.ac.cy
NXDOMAIN	nat39-234.nat.ucy.ac.cy
NOERROR	nat38-142.nat.ucy.ac.cy
NOERROR	nat36-202.nat.ucy.ac.cy
NXDOMAIN	opnsense2.csrv.ucy.ac.cy
NXDOMAIN	nat39-118.nat.ucy.ac.cy
NOERROR	nat35-117.nat.ucy.ac.cy
NXDOMAIN	www.itasweb.ucy.ac.cy
NOERROR	nat30-40.nat.ucy.ac.cy
NXDOMAIN	nat39-28.nat.ucy.ac.cy
NOERROR	nat38-229.nat.ucy.ac.cy
NOERROR	nat5-170.nat.ucy.ac.cy
NOERROR	nat195.cs.ucy.ac.cy
NXDOMAIN	www.covid19-wiki.ehealthlab.cs.ucy.ac.cy
NOERROR	nat30-238.nat.ucy.ac.cy
NOERROR	nat35-246.nat.ucy.ac.cy
NOERROR	nat5-191.nat.ucy.ac.cy
NXDOMAIN	nat39-84.nat.ucy.ac.cy
NOERROR	thales.grid.ucy.ac.cy
NOERROR	nat38-51.nat.ucy.ac.cy
NOERROR	nat37-3.nat.ucy.ac.cy
NXDOMAIN	zmldap02.csrv.ucy.ac.cy
NOERROR	nat5-60.nat.ucy.ac.cy
NXDOMAIN	zmproxy02.csrv.ucy.ac.cy
NOERROR	nat35-151.nat.ucy.ac.cy
NOERROR	ino.mas.ucy.ac.cy
NOERROR	nat35-107.nat.ucy.ac.cy
NOERROR	listserv.cs.ucy.ac.cy
NOERROR	nat37-81.nat.ucy.ac.cy
NOERROR	nat35-158.nat.ucy.ac.cy
NOERROR	webapps.ucy.ac.cy
NOERROR	nat38-149.nat.ucy.ac.cy
NOERROR	pvlabmaps.sharks.ucy.ac.cy
NOERROR	ap-lb.cs.ucy.ac.cy
NOERROR	prtlweb02.csrv.ucy.ac.cy
NOERROR	nat36-242.nat.ucy.ac.cy
NOERROR	nat37-25.nat.ucy.ac.cy
NOERROR	nat35-233.nat.ucy.ac.cy
NOERROR	nat37-18.nat.ucy.ac.cy
NOERROR	iceird2014.cs.ucy.ac.cy
NOERROR	nat5-43.nat.ucy.ac.cy
NXDOMAIN	nat39-251.nat.ucy.ac.cy
NOERROR	nat35-79.nat.ucy.ac.cy
NOERROR	wmslb201.grid.ucy.ac.cy
NXDOMAIN	newvoip.srvvoice.ucy.ac.cy
NOERROR	c19bot.ucy.ac.cy
NOERROR	nat37-140.nat.ucy.ac.cy
NOERROR	mmeilo02.polytech.ucy.ac.cy
NOERROR	lms.ucy.ac.cy
NOERROR	nat5-75.nat.ucy.ac.cy
NOERROR	nat35-195.nat.ucy.ac.cy
NOERROR	nat38-38.nat.ucy.ac.cy
NXDOMAIN	www.ssoportal.ucy.ac.cy
NOERROR	nat30-69.nat.ucy.ac.cy
NOERROR	nat5-231.nat.ucy.ac.cy
NOERROR	itasweb.ucy.ac.cy
NOERROR	ecscw2013.cs.ucy.ac.cy
NXDOMAIN	nat39-173.nat.ucy.ac.cy
NOERROR	ui101.grid.ucy.ac.cy
NXDOMAIN	nat39-31.nat.ucy.ac.cy
NOERROR	orwell.grid.ucy.ac.cy
NOERROR	nat36-235.nat.ucy.ac.cy
NOERROR	vm103.grid.ucy.ac.cy
NOERROR	nat36-116.nat.ucy.ac.cy
NOERROR	nat38-47.nat.ucy.ac.cy
NOERROR	smartlib.cs.ucy.ac.cy
NOERROR	nat38-104.nat.ucy.ac.cy
NOERROR	nat37-239.nat.ucy.ac.cy
NOERROR	nat30-231.nat.ucy.ac.cy
NOERROR	nat36-28.nat.ucy.ac.cy
NOERROR	gria101.grid.ucy.ac.cy
NOERROR	nat37-144.nat.ucy.ac.cy
NOERROR	nat30-224.nat.ucy.ac.cy
NOERROR	sapeccprod01.ucy.ac.cy
NOERROR	pleiades.cc.ucy.ac.cy
NOERROR	nat5-177.nat.ucy.ac.cy
NOERROR	fw-in.vega2.ucy.ac.cy
NOERROR	webintbeta.lib.ucy.ac.cy
NOERROR	nat30-197.nat.ucy.ac.cy
NXDOMAIN	admin.soa.ucy.ac.cy
NOERROR	damon.cs.ucy.ac.cy
NOERROR	nat37-72.nat.ucy.ac.cy
NOERROR	ucysis.ucy.ac.cy
NOERROR	nat35-128.nat.ucy.ac.cy
NOERROR	nat5-155.nat.ucy.ac.cy
NOERROR	nat35-193.nat.ucy.ac.cy
NXDOMAIN	zmproxy03.csrv.ucy.ac.cy
NOERROR	nat197.cs.ucy.ac.cy
NOERROR	www1.cs.ucy.ac.cy
NOERROR	nat37-60.nat.ucy.ac.cy
NOERROR	anyplace.cs.ucy.ac.cy
NOERROR	nat35-105.nat.ucy.ac.cy
NOERROR	ns2.cs.ucy.ac.cy
NXDOMAIN	adam.in.cs.ucy.ac.cy
NOERROR	nat30-189.nat.ucy.ac.cy
NOERROR	nat30-154.nat.ucy.ac.cy
NOERROR	nat30-181.nat.ucy.ac.cy
NOERROR	hermes-mba.cc.ucy.ac.cy
NXDOMAIN	www.portal.dev.ucy.ac.cy
NOERROR	nat5-137.nat.ucy.ac.cy
NOERROR	streamingsrvoc.vconf.ucy.ac.cy
NOERROR	nat38-141.nat.ucy.ac.cy
NOERROR	ce201.grid.ucy.ac.cy
NOERROR	erasmia.cs.ucy.ac.cy
NOERROR	nat38-61.nat.ucy.ac.cy
NOERROR	nat37-44.nat.ucy.ac.cy
NOERROR	nat38-203.nat.ucy.ac.cy
NOERROR	nat36-236.nat.ucy.ac.cy
NOERROR	hdms18.cs.ucy.ac.cy
NOERROR	developer.ucy.ac.cy
NOERROR	nat36-183.nat.ucy.ac.cy
NOERROR	nat38-15.nat.ucy.ac.cy
NOERROR	si2.cs.ucy.ac.cy
NOERROR	mirror.library.ucy.ac.cy
NOERROR	nat35-217.nat.ucy.ac.cy
NXDOMAIN	nat39-242.nat.ucy.ac.cy
NOERROR	nat36-252.nat.ucy.ac.cy
NOERROR	nat36-108.nat.ucy.ac.cy
NXDOMAIN	nat39-10.nat.ucy.ac.cy
NOERROR	nat5-193.nat.ucy.ac.cy
NXDOMAIN	webmail.etsd.ucy.ac.cy
NOERROR	nat38-213.nat.ucy.ac.cy
NOERROR	nat30-186.nat.ucy.ac.cy
NOERROR	nat5-48.nat.ucy.ac.cy
NOERROR	nat38-70.nat.ucy.ac.cy
NOERROR	storage.grid.ucy.ac.cy
NXDOMAIN	radius.ucy.ac.cy
NOERROR	nat5-220.nat.ucy.ac.cy
NXDOMAIN	nat39-24.nat.ucy.ac.cy
NOERROR	nat35-48.nat.ucy.ac.cy
NOERROR	m.ssoint.lib.ucy.ac.cy
NOERROR	www.netrl.ucy.ac.cy
NOERROR	ip12.vega2.ucy.ac.cy
NOERROR	nat38-233.nat.ucy.ac.cy
NOERROR	nat38-147.nat.ucy.ac.cy
NOERROR	nat5-58.nat.ucy.ac.cy
NOERROR	nat30-58.nat.ucy.ac.cy
NOERROR	orasun.cc.ucy.ac.cy
NXDOMAIN	dssweb2.csrv.ucy.ac.cy
NOERROR	fr2.grid.ucy.ac.cy
NOERROR	nat30-200.nat.ucy.ac.cy
NXDOMAIN	zmproxy01.csrv.ucy.ac.cy
NOERROR	www.ccp.ucy.ac.cy
NOERROR	nat30-32.nat.ucy.ac.cy
NOERROR	nat36-253.nat.ucy.ac.cy
NOERROR	nat36-42.nat.ucy.ac.cy
NOERROR	helios.cs.ucy.ac.cy
NXDOMAIN	nat39-116.nat.ucy.ac.cy
NOERROR	epa-web.soe.ucy.ac.cy
NOERROR	nat35-82.nat.ucy.ac.cy
NOERROR	www.mas.ucy.ac.cy
NXDOMAIN	testredcap.ucy.ac.cy
NXDOMAIN	nat39-74.nat.ucy.ac.cy
NOERROR	nat30-254.nat.ucy.ac.cy
NOERROR	www.commonsense2013.cs.ucy.ac.cy
NOERROR	nat35-73.nat.ucy.ac.cy
NOERROR	nat35-56.nat.ucy.ac.cy
NXDOMAIN	www.baneis.ucy.ac.cy
NOERROR	app01.ucy.ac.cy
NXDOMAIN	nat39-30.nat.ucy.ac.cy
NOERROR	polysemwebsvr1.polytech.ucy.ac.cy
NXDOMAIN	www.kostrikislab.ucy.ac.cy
NOERROR	argus.grid.ucy.ac.cy
NOERROR	owncloud.cc.ucy.ac.cy
NXDOMAIN	artemis.in.cs.ucy.ac.cy
NXDOMAIN	nat39-238.nat.ucy.ac.cy
NOERROR	mmeprn01.polytech.ucy.ac.cy
NOERROR	nat30-184.nat.ucy.ac.cy
NOERROR	nat37-107.nat.ucy.ac.cy
NOERROR	nat5-148.nat.ucy.ac.cy
NOERROR	nat37-109.nat.ucy.ac.cy
NOERROR	nat38-200.nat.ucy.ac.cy
NXDOMAIN	nat39-124.nat.ucy.ac.cy
NOERROR	www.battledim.ucy.ac.cy
NOERROR	nat30-106.nat.ucy.ac.cy
NOERROR	nat30-115.nat.ucy.ac.cy
NOERROR	csfs12.cs.ucy.ac.cy
NXDOMAIN	nat39-194.nat.ucy.ac.cy
NOERROR	nat36-36.nat.ucy.ac.cy
NOERROR	nat37-66.nat.ucy.ac.cy
NOERROR	nat38-146.nat.ucy.ac.cy
NOERROR	nat38-138.nat.ucy.ac.cy
NXDOMAIN	eris.cs.ucy.ac.cy
NXDOMAIN	otrs.cc.ucy.ac.cy
NXDOMAIN	nat39-149.nat.ucy.ac.cy
NXDOMAIN	nat39-110.nat.ucy.ac.cy
NOERROR	nat37-245.nat.ucy.ac.cy
NOERROR	prtlweb.csrv.ucy.ac.cy
NOERROR	nat38-90.nat.ucy.ac.cy
NOERROR	nat30-148.nat.ucy.ac.cy
NXDOMAIN	nat39-206.nat.ucy.ac.cy
NOERROR	cosmas.cs.ucy.ac.cy
NOERROR	nat38-218.nat.ucy.ac.cy
NOERROR	nat5-69.nat.ucy.ac.cy
NOERROR	www.discotec07.cs.ucy.ac.cy
NOERROR	spartakus.cc.ucy.ac.cy
NOERROR	nat36-248.nat.ucy.ac.cy
NXDOMAIN	nat39-193.nat.ucy.ac.cy
NOERROR	nat35-67.nat.ucy.ac.cy
NXDOMAIN	idm04.csrv.ucy.ac.cy
NXDOMAIN	nas4.lib.ucy.ac.cy
NOERROR	nat38-65.nat.ucy.ac.cy
NOERROR	nat37-206.nat.ucy.ac.cy
NOERROR	nat37-137.nat.ucy.ac.cy
NOERROR	ucysso.ucy.ac.cy
NOERROR	nat37-209.nat.ucy.ac.cy
NOERROR	nat38-189.nat.ucy.ac.cy
NXDOMAIN	nat39-4.nat.ucy.ac.cy
NOERROR	nat35-196.nat.ucy.ac.cy
NOERROR	nat38-22.nat.ucy.ac.cy
NOERROR	nat38-169.nat.ucy.ac.cy
NOERROR	nat35-111.nat.ucy.ac.cy
NOERROR	nat30-251.nat.ucy.ac.cy
NOERROR	www.medinfo.cs.ucy.ac.cy
NXDOMAIN	melpomene.in.cs.ucy.ac.cy
NXDOMAIN	nat39-139.nat.ucy.ac.cy
NOERROR	nat35-110.nat.ucy.ac.cy
NOERROR	mon101.grid.ucy.ac.cy
NOERROR	nat36-65.nat.ucy.ac.cy
NOERROR	mechanism.ucy.ac.cy
NOERROR	prtlweb01.csrv.ucy.ac.cy
NOERROR	nat36-113.nat.ucy.ac.cy
NOERROR	appintbeta.lib.ucy.ac.cy
NOERROR	nat36-40.nat.ucy.ac.cy
NOERROR	nat38-128.nat.ucy.ac.cy
NOERROR	nat37-115.nat.ucy.ac.cy
NOERROR	nat36-136.nat.ucy.ac.cy
NOERROR	nat36-131.nat.ucy.ac.cy
NOERROR	ictai2014.cs.ucy.ac.cy
NOERROR	nat5-235.nat.ucy.ac.cy
NOERROR	nat35-95.nat.ucy.ac.cy
NOERROR	nat38-208.nat.ucy.ac.cy
NOERROR	nat5-139.nat.ucy.ac.cy
NOERROR	nat30-232.nat.ucy.ac.cy
NOERROR	nat35-88.nat.ucy.ac.cy
NXDOMAIN	nat39-126.nat.ucy.ac.cy
NOERROR	nat36-156.nat.ucy.ac.cy
NXDOMAIN	cpanel.live.ucy-web-server.ucy.ac.cy
NOERROR	nat5-233.nat.ucy.ac.cy
NOERROR	nat5-124.nat.ucy.ac.cy
NOERROR	nat30-63.nat.ucy.ac.cy
NOERROR	pwdgis.ucy.ac.cy
NOERROR	nat37-254.nat.ucy.ac.cy
NOERROR	biotextquest.biol.ucy.ac.cy
NOERROR	nat37-51.nat.ucy.ac.cy
NOERROR	nat35-27.nat.ucy.ac.cy
NOERROR	nat38-42.nat.ucy.ac.cy
NOERROR	battledim.ucy.ac.cy
NOERROR	nat35-44.nat.ucy.ac.cy
NOERROR	nat5-215.nat.ucy.ac.cy
NOERROR	nat204.cs.ucy.ac.cy
NOERROR	sourcecorpus.ucy.ac.cy
NOERROR	lcweb.iacoveio.ucy.ac.cy
NOERROR	nat38-62.nat.ucy.ac.cy
NOERROR	nat37-148.nat.ucy.ac.cy
NXDOMAIN	aris.in.cs.ucy.ac.cy
NXDOMAIN	nat39-99.nat.ucy.ac.cy
NOERROR	nat36-123.nat.ucy.ac.cy
NOERROR	nat30-64.nat.ucy.ac.cy
NOERROR	nat35-187.nat.ucy.ac.cy
NOERROR	nat36-15.nat.ucy.ac.cy
NOERROR	nat36-78.nat.ucy.ac.cy
NOERROR	nat30-20.nat.ucy.ac.cy
NOERROR	nat5-79.nat.ucy.ac.cy
NOERROR	enewsletter.ucy.ac.cy
NOERROR	nat36-91.nat.ucy.ac.cy
NXDOMAIN	baneistest.ucy.ac.cy
NOERROR	nat30-216.nat.ucy.ac.cy
NOERROR	nat5-21.nat.ucy.ac.cy
NOERROR	nat30-37.nat.ucy.ac.cy
NOERROR	nat38-34.nat.ucy.ac.cy
NOERROR	lexcy.library.ucy.ac.cy
NXDOMAIN	nat39-224.nat.ucy.ac.cy
NOERROR	nat37-59.nat.ucy.ac.cy
NOERROR	nat37-85.nat.ucy.ac.cy
NOERROR	npserv1.phy.ucy.ac.cy
NOERROR	nat37-24.nat.ucy.ac.cy
NOERROR	mmeprn02.polytech.ucy.ac.cy
NOERROR	ip7.vega2.ucy.ac.cy
NOERROR	nat37-55.nat.ucy.ac.cy
NXDOMAIN	nat39-72.nat.ucy.ac.cy
NOERROR	vm101.grid.ucy.ac.cy
NOERROR	nat203.cs.ucy.ac.cy
NOERROR	nat30-96.nat.ucy.ac.cy
NOERROR	nat37-7.nat.ucy.ac.cy
NOERROR	nat5-156.nat.ucy.ac.cy
NOERROR	nat5-46.nat.ucy.ac.cy
NOERROR	nat5-53.nat.ucy.ac.cy
NOERROR	nat36-160.nat.ucy.ac.cy
NOERROR	nat199.cs.ucy.ac.cy
NOERROR	wn133.grid.ucy.ac.cy
NOERROR	nat36-5.nat.ucy.ac.cy
NOERROR	nat37-156.nat.ucy.ac.cy
NOERROR	vconf5.vconf.ucy.ac.cy
NOERROR	sapwebdis01.csrv.ucy.ac.cy
NXDOMAIN	www.banssb.ucy.ac.cy
NOERROR	nat35-96.nat.ucy.ac.cy
NOERROR	nat5-209.nat.ucy.ac.cy
NXDOMAIN	idm03.csrv.ucy.ac.cy
NOERROR	nat35-226.nat.ucy.ac.cy
NOERROR	nat5-65.nat.ucy.ac.cy
NOERROR	nat36-112.nat.ucy.ac.cy
NOERROR	nat5-45.nat.ucy.ac.cy
NOERROR	nat35-157.nat.ucy.ac.cy
NXDOMAIN	nat39-104.nat.ucy.ac.cy
NOERROR	nat38-178.nat.ucy.ac.cy
NOERROR	nat35-142.nat.ucy.ac.cy
NOERROR	www.physics.phy.ucy.ac.cy
NOERROR	nat30-28.nat.ucy.ac.cy
NOERROR	www.netrl.cs.ucy.ac.cy
NOERROR	nat35-77.nat.ucy.ac.cy
NOERROR	nat35-234.nat.ucy.ac.cy
NXDOMAIN	nat39-106.nat.ucy.ac.cy
NXDOMAIN	mirto.in.cs.ucy.ac.cy
NOERROR	nat30-178.nat.ucy.ac.cy
NOERROR	nat30-39.nat.ucy.ac.cy
NOERROR	nat36-66.nat.ucy.ac.cy
NOERROR	nat36-194.nat.ucy.ac.cy
NOERROR	nat36-77.nat.ucy.ac.cy
NOERROR	gk.ucy.ac.cy
NOERROR	nat35-60.nat.ucy.ac.cy
NXDOMAIN	zmbox06.csrv.ucy.ac.cy
NOERROR	nat36-177.nat.ucy.ac.cy
NOERROR	abekt.lib.ucy.ac.cy
NXDOMAIN	www.itiswiki.csrv.ucy.ac.cy
NOERROR	etaps10.cs.ucy.ac.cy
NOERROR	nat35-159.nat.ucy.ac.cy
NOERROR	nat35-223.nat.ucy.ac.cy
NOERROR	personaweb.cs.ucy.ac.cy
NXDOMAIN	testindico.phy.ucy.ac.cy
NOERROR	nat37-1.nat.ucy.ac.cy
NOERROR	nat37-236.nat.ucy.ac.cy
NOERROR	nat35-161.nat.ucy.ac.cy
NOERROR	vm104.grid.ucy.ac.cy
NXDOMAIN	www.bimstest.ucy.ac.cy
NOERROR	nat37-202.nat.ucy.ac.cy
NOERROR	nat37-197.nat.ucy.ac.cy
NOERROR	nat35-139.nat.ucy.ac.cy
NOERROR	nat35-50.nat.ucy.ac.cy
NOERROR	nat35-83.nat.ucy.ac.cy
NOERROR	nat37-228.nat.ucy.ac.cy
NOERROR	nat38-173.nat.ucy.ac.cy
NOERROR	nat30-102.nat.ucy.ac.cy
NOERROR	nat30-124.nat.ucy.ac.cy
NXDOMAIN	nat39-121.nat.ucy.ac.cy
NOERROR	ekonomia.ucy.ac.cy
NOERROR	wn112.grid.ucy.ac.cy
NOERROR	nat36-35.nat.ucy.ac.cy
NOERROR	nat35-72.nat.ucy.ac.cy
NOERROR	nat37-12.nat.ucy.ac.cy
NOERROR	nat35-62.nat.ucy.ac.cy
NOERROR	nat36-181.nat.ucy.ac.cy
NOERROR	nat36-166.nat.ucy.ac.cy
NOERROR	api01.ucy.ac.cy
NOERROR	nat36-130.nat.ucy.ac.cy
NOERROR	nat30-22.nat.ucy.ac.cy
NOERROR	nat5-108.nat.ucy.ac.cy
NXDOMAIN	nat39-186.nat.ucy.ac.cy
NOERROR	wn136.grid.ucy.ac.cy
NOERROR	coronatest.ucy.ac.cy
NOERROR	nat36-109.nat.ucy.ac.cy
NOERROR	wn123.grid.ucy.ac.cy
NOERROR	mmeprn03.polytech.ucy.ac.cy
NOERROR	folsrv.ucy.ac.cy
NOERROR	godigital.cs.ucy.ac.cy
NOERROR	nat37-250.nat.ucy.ac.cy
NOERROR	fm2016.cs.ucy.ac.cy
NOERROR	nat37-77.nat.ucy.ac.cy
NOERROR	nat30-75.nat.ucy.ac.cy
NOERROR	nat37-126.nat.ucy.ac.cy
NOERROR	nat38-109.nat.ucy.ac.cy
NOERROR	thrylos.mas.ucy.ac.cy
NOERROR	nat37-34.nat.ucy.ac.cy
NOERROR	nat205.cs.ucy.ac.cy
NOERROR	pvlabsimul-public.photovoltaic.ucy.ac.cy
NOERROR	nat5-222.nat.ucy.ac.cy
NXDOMAIN	www.lradius.in.cs.ucy.ac.cy
NOERROR	cybiobank.ucy.ac.cy
NOERROR	nat30-92.nat.ucy.ac.cy
NOERROR	nat5-88.nat.ucy.ac.cy
NOERROR	nat35-97.nat.ucy.ac.cy
NOERROR	nat37-211.nat.ucy.ac.cy
NOERROR	nat37-78.nat.ucy.ac.cy
NOERROR	sm-server.cc.ucy.ac.cy
NOERROR	ns2.ucy.ac.cy
NOERROR	nat35-92.nat.ucy.ac.cy
NOERROR	nat37-118.nat.ucy.ac.cy
NOERROR	nat37-155.nat.ucy.ac.cy
NXDOMAIN	nat39-27.nat.ucy.ac.cy
NOERROR	www.cyec.cs.ucy.ac.cy
NOERROR	nat30-210.nat.ucy.ac.cy
NOERROR	nat38-100.nat.ucy.ac.cy
NOERROR	nat38-194.nat.ucy.ac.cy
NOERROR	reservations.cs.ucy.ac.cy
NXDOMAIN	nat39-175.nat.ucy.ac.cy
NOERROR	arcwork.labpolytech.ucy.ac.cy
NOERROR	nat30-67.nat.ucy.ac.cy
NXDOMAIN	soa.ucy.ac.cy
NOERROR	nat37-95.nat.ucy.ac.cy
NOERROR	nat35-237.nat.ucy.ac.cy
NXDOMAIN	cpcontacts.edbticdt2021.cs.ucy.ac.cy
NOERROR	nat37-179.nat.ucy.ac.cy
NOERROR	nat35-63.nat.ucy.ac.cy
NOERROR	nat37-129.nat.ucy.ac.cy
NXDOMAIN	nat39-227.nat.ucy.ac.cy
NOERROR	nat38-140.nat.ucy.ac.cy
NOERROR	nat38-64.nat.ucy.ac.cy
NXDOMAIN	cpcalendars.fm2016.cs.ucy.ac.cy
NOERROR	nat30-87.nat.ucy.ac.cy
NOERROR	helpdesk.ucy.ac.cy
NOERROR	nat35-164.nat.ucy.ac.cy
NOERROR	nat38-110.nat.ucy.ac.cy
NOERROR	nat5-34.nat.ucy.ac.cy
NXDOMAIN	nat39-63.nat.ucy.ac.cy
NOERROR	nat37-174.nat.ucy.ac.cy
NOERROR	nat38-2.nat.ucy.ac.cy
NXDOMAIN	citycampus.ucy.ac.cy
NOERROR	kspot.cs.ucy.ac.cy
NXDOMAIN	baneisdev.ucy.ac.cy
NOERROR	nat35-169.nat.ucy.ac.cy
NXDOMAIN	pop.ucy.ac.cy
NOERROR	ip8.vega2.ucy.ac.cy
NOERROR	nat5-164.nat.ucy.ac.cy
NXDOMAIN	cpcontacts.live.ucy-web-server.ucy.ac.cy
NOERROR	nat30-51.nat.ucy.ac.cy
NOERROR	nat30-34.nat.ucy.ac.cy
NOERROR	nat5-68.nat.ucy.ac.cy
NOERROR	nat5-83.nat.ucy.ac.cy
NOERROR	nat36-210.nat.ucy.ac.cy
NOERROR	ourania.cs.ucy.ac.cy
NOERROR	fossae.ucy.ac.cy
NOERROR	nat30-248.nat.ucy.ac.cy
NXDOMAIN	nat39-168.nat.ucy.ac.cy
NOERROR	success.cs.ucy.ac.cy
NOERROR	nat38-154.nat.ucy.ac.cy
NOERROR	nat35-74.nat.ucy.ac.cy
NOERROR	edbticdt2021.cs.ucy.ac.cy
NOERROR	mani.ucy.ac.cy
NXDOMAIN	www.cm1.srvvoice.ucy.ac.cy
NOERROR	nat37-212.nat.ucy.ac.cy
NXDOMAIN	nat39-202.nat.ucy.ac.cy
NOERROR	nat38-155.nat.ucy.ac.cy
NOERROR	nat208.cs.ucy.ac.cy
NXDOMAIN	presence2.srvvoice.ucy.ac.cy
NOERROR	nat5-213.nat.ucy.ac.cy
NOERROR	kiosop.ucy.ac.cy
NOERROR	iolaos.cs.ucy.ac.cy
NOERROR	kostrikislab.ucy.ac.cy
NOERROR	athena.phy.ucy.ac.cy
NOERROR	nat30-6.nat.ucy.ac.cy
NOERROR	nat5-143.nat.ucy.ac.cy
NXDOMAIN	nat39-23.nat.ucy.ac.cy
NOERROR	nat38-115.nat.ucy.ac.cy
NOERROR	nat35-153.nat.ucy.ac.cy
NXDOMAIN	nat39-164.nat.ucy.ac.cy
NOERROR	nat30-105.nat.ucy.ac.cy
NOERROR	nat36-17.nat.ucy.ac.cy
NOERROR	nat37-120.nat.ucy.ac.cy
NOERROR	nat30-158.nat.ucy.ac.cy
NOERROR	nat30-62.nat.ucy.ac.cy
NXDOMAIN	gen1.tsmaint.ucy.ac.cy
NOERROR	nat35-235.nat.ucy.ac.cy
NOERROR	nat36-124.nat.ucy.ac.cy
NOERROR	nat35-126.nat.ucy.ac.cy
NXDOMAIN	www.events.ucy.ac.cy
NOERROR	nat38-204.nat.ucy.ac.cy
NOERROR	nat5-190.nat.ucy.ac.cy
NOERROR	athena.cc.ucy.ac.cy
NOERROR	student2.ucy.ac.cy
NOERROR	nat35-99.nat.ucy.ac.cy
NOERROR	nat5-10.nat.ucy.ac.cy
NOERROR	nat36-18.nat.ucy.ac.cy
NXDOMAIN	cpcalendars.live.ucy-web-server.ucy.ac.cy
NOERROR	nat5-154.nat.ucy.ac.cy
NXDOMAIN	nat39-49.nat.ucy.ac.cy
NOERROR	nat30-203.nat.ucy.ac.cy
NOERROR	nat35-177.nat.ucy.ac.cy
NOERROR	www.euc2012.cs.ucy.ac.cy
NOERROR	nat30-47.nat.ucy.ac.cy
NOERROR	nat36-49.nat.ucy.ac.cy
NOERROR	nat36-144.nat.ucy.ac.cy
NOERROR	zmlb02.csrv.ucy.ac.cy
NOERROR	nat38-235.nat.ucy.ac.cy
NOERROR	nat35-54.nat.ucy.ac.cy
NOERROR	nat5-198.nat.ucy.ac.cy
NOERROR	nat35-65.nat.ucy.ac.cy
NOERROR	nat37-6.nat.ucy.ac.cy
NXDOMAIN	nat39-2.nat.ucy.ac.cy
NOERROR	web.dss.ucy.ac.cy
NOERROR	nat35-211.nat.ucy.ac.cy
NOERROR	nat36-208.nat.ucy.ac.cy
NXDOMAIN	nat39-135.nat.ucy.ac.cy
NOERROR	www.physics.ucy.ac.cy
NXDOMAIN	vlan18.cs.ucy.ac.cy
NOERROR	www.pvtechnology.ucy.ac.cy
NXDOMAIN	mesarchcollections.ucy.ac.cy
NOERROR	nat37-40.nat.ucy.ac.cy
NOERROR	rayzit2.cs.ucy.ac.cy
NOERROR	nat38-117.nat.ucy.ac.cy
NOERROR	nat30-111.nat.ucy.ac.cy
NOERROR	nat35-40.nat.ucy.ac.cy
NXDOMAIN	2.ucy.ac.cy
NOERROR	nat36-20.nat.ucy.ac.cy
NOERROR	nat35-176.nat.ucy.ac.cy
NOERROR	nat38-52.nat.ucy.ac.cy
NOERROR	nat30-109.nat.ucy.ac.cy
NOERROR	asset2002.cc.ucy.ac.cy
NOERROR	nat38-167.nat.ucy.ac.cy
NOERROR	nat35-213.nat.ucy.ac.cy
NOERROR	nat209.cs.ucy.ac.cy
NOERROR	nat30-193.nat.ucy.ac.cy
NOERROR	nat38-248.nat.ucy.ac.cy
NOERROR	nat36-133.nat.ucy.ac.cy
NOERROR	nat37-119.nat.ucy.ac.cy
NOERROR	nat35-4.nat.ucy.ac.cy
NOERROR	nat37-46.nat.ucy.ac.cy
NXDOMAIN	www.srvvoice.ucy.ac.cy
NXDOMAIN	opnsense1.csrv.ucy.ac.cy
NOERROR	pvwebsvr.photovoltaic.ucy.ac.cy
NOERROR	cygrid-nagios.grid.ucy.ac.cy
NOERROR	nat30-56.nat.ucy.ac.cy
NXDOMAIN	mail3.cs.ucy.ac.cy
NXDOMAIN	nat39-191.nat.ucy.ac.cy
NOERROR	nat35-140.nat.ucy.ac.cy
NOERROR	heraclitus2.ucy.ac.cy
NOERROR	nat36-74.nat.ucy.ac.cy
NXDOMAIN	nat39-46.nat.ucy.ac.cy
NOERROR	cc-lan.cc.ucy.ac.cy
NOERROR	nat30-179.nat.ucy.ac.cy
NXDOMAIN	zmbox05.csrv.ucy.ac.cy
NOERROR	tor.grid.ucy.ac.cy
NOERROR	nat30-199.nat.ucy.ac.cy
NXDOMAIN	zmproxy04.csrv.ucy.ac.cy
NXDOMAIN	nat39-103.nat.ucy.ac.cy
NOERROR	ehealthlab.cs.ucy.ac.cy
NOERROR	reconlife.cs.ucy.ac.cy
NXDOMAIN	nat39-114.nat.ucy.ac.cy
NXDOMAIN	nat39-216.nat.ucy.ac.cy
NOERROR	nat30-36.nat.ucy.ac.cy
NOERROR	nat38-209.nat.ucy.ac.cy
NOERROR	nat30-113.nat.ucy.ac.cy
NOERROR	nat30-183.nat.ucy.ac.cy
NOERROR	nat38-93.nat.ucy.ac.cy
NOERROR	nat36-43.nat.ucy.ac.cy
NXDOMAIN	nat39-198.nat.ucy.ac.cy
NOERROR	www.ehealthlab.cs.ucy.ac.cy
NOERROR	www.msccis.ucy.ac.cy
NOERROR	ui102.grid.ucy.ac.cy
NOERROR	vm102.grid.ucy.ac.cy
NOERROR	www.biophys.ucy.ac.cy
NOERROR	nat37-42.nat.ucy.ac.cy
NOERROR	nat38-238.nat.ucy.ac.cy
NOERROR	nat30-116.nat.ucy.ac.cy
NXDOMAIN	nat39-82.nat.ucy.ac.cy
NOERROR	smartag.cs.ucy.ac.cy
NOERROR	ns4.ucy.ac.cy
NOERROR	nat35-221.nat.ucy.ac.cy
NOERROR	nat36-13.nat.ucy.ac.cy
NXDOMAIN	eva.in.cs.ucy.ac.cy
NOERROR	nat30-27.nat.ucy.ac.cy
NOERROR	testudo.ucy.ac.cy
NOERROR	nat30-61.nat.ucy.ac.cy
NOERROR	gnosis.library.ucy.ac.cy
NOERROR	nat35-76.nat.ucy.ac.cy
NXDOMAIN	ermisweb3.csrv.ucy.ac.cy
NOERROR	nat38-116.nat.ucy.ac.cy
NOERROR	m.appint.lib.ucy.ac.cy
NOERROR	nat38-241.nat.ucy.ac.cy
NOERROR	ypatis.cs.ucy.ac.cy
NOERROR	websrv.ucy.ac.cy
NOERROR	nat37-152.nat.ucy.ac.cy
NOERROR	nat36-141.nat.ucy.ac.cy
NOERROR	nat38-190.nat.ucy.ac.cy
NOERROR	nat5-125.nat.ucy.ac.cy
NOERROR	www.erc.ucy.ac.cy
NOERROR	ip4.vega2.ucy.ac.cy
NXDOMAIN	nat39-127.nat.ucy.ac.cy
NOERROR	edumath.ucy.ac.cy
NOERROR	ceeprn02.polytech.ucy.ac.cy
NOERROR	nat37-30.nat.ucy.ac.cy
NOERROR	nat37-91.nat.ucy.ac.cy
NOERROR	nat36-237.nat.ucy.ac.cy
NXDOMAIN	nat39-140.nat.ucy.ac.cy
NXDOMAIN	nat39-102.nat.ucy.ac.cy
NOERROR	nat36-12.nat.ucy.ac.cy
NXDOMAIN	nemesis.cs.ucy.ac.cy
NOERROR	nat35-51.nat.ucy.ac.cy
NOERROR	moodle.cs.ucy.ac.cy
NOERROR	nat37-86.nat.ucy.ac.cy
NOERROR	nat37-73.nat.ucy.ac.cy
NXDOMAIN	nat39-165.nat.ucy.ac.cy
NOERROR	nat37-194.nat.ucy.ac.cy
NOERROR	nat37-189.nat.ucy.ac.cy
NXDOMAIN	electra.ucy.ac.cy
NOERROR	nat5-149.nat.ucy.ac.cy
NOERROR	ssointbeta.lib.ucy.ac.cy
NOERROR	nat5-144.nat.ucy.ac.cy
NOERROR	nat30-151.nat.ucy.ac.cy
NOERROR	iss.vconf.ucy.ac.cy
NOERROR	nat36-225.nat.ucy.ac.cy
NOERROR	nat38-143.nat.ucy.ac.cy
NOERROR	nat30-10.nat.ucy.ac.cy
NOERROR	nat5-100.nat.ucy.ac.cy
NOERROR	asweb.ucy.ac.cy
NOERROR	wn100.grid.ucy.ac.cy
NXDOMAIN	nat39-65.nat.ucy.ac.cy
NOERROR	nat35-198.nat.ucy.ac.cy
NXDOMAIN	nat39-166.nat.ucy.ac.cy
NXDOMAIN	www.bannersstest.ucy.ac.cy
NOERROR	nat37-217.nat.ucy.ac.cy
NOERROR	ns1.cs.ucy.ac.cy
NOERROR	www.enal.ucy.ac.cy
NOERROR	nat36-186.nat.ucy.ac.cy
NOERROR	nat36-196.nat.ucy.ac.cy
NXDOMAIN	nat39-25.nat.ucy.ac.cy
NOERROR	ip11.vega1.ucy.ac.cy
NOERROR	nat30-84.nat.ucy.ac.cy
NXDOMAIN	nat39-60.nat.ucy.ac.cy
NOERROR	nat35-148.nat.ucy.ac.cy
NXDOMAIN	nat39-246.nat.ucy.ac.cy
NOERROR	nat5-225.nat.ucy.ac.cy
NXDOMAIN	nat39-160.nat.ucy.ac.cy
NOERROR	nat38-48.nat.ucy.ac.cy
NOERROR	nat38-72.nat.ucy.ac.cy
NOERROR	www.ece.ucy.ac.cy
NOERROR	nat38-31.nat.ucy.ac.cy
NOERROR	nat38-87.nat.ucy.ac.cy
NOERROR	ikaros.vega1.ucy.ac.cy
NOERROR	www.logipaignion.cs.ucy.ac.cy
NOERROR	ermis.phy.ucy.ac.cy
NOERROR	nat37-121.nat.ucy.ac.cy
NOERROR	nat36-244.nat.ucy.ac.cy
NOERROR	nat38-80.nat.ucy.ac.cy
NOERROR	nat5-200.nat.ucy.ac.cy
NXDOMAIN	old.cc.ucy.ac.cy
NOERROR	nat35-154.nat.ucy.ac.cy
NOERROR	allure.cc.ucy.ac.cy
NOERROR	victorhugo.ucy.ac.cy
NXDOMAIN	testsurvey.ucy.ac.cy
NOERROR	nat30-73.nat.ucy.ac.cy
NOERROR	www.arch.ucy.ac.cy
NOERROR	www.new.ucy.ac.cy
NOERROR	nat30-202.nat.ucy.ac.cy
NOERROR	neptune.cs.ucy.ac.cy
NOERROR	pygmalion.mas.ucy.ac.cy
NOERROR	culc.ucy.ac.cy
NOERROR	nat38-193.nat.ucy.ac.cy
NOERROR	openarchives.lib.ucy.ac.cy
NXDOMAIN	ipam.in.cs.ucy.ac.cy
NOERROR	nat37-203.nat.ucy.ac.cy
NOERROR	planetlab-3.cs.ucy.ac.cy
NOERROR	nat38-156.nat.ucy.ac.cy
NOERROR	clamav.cs.ucy.ac.cy
NXDOMAIN	nat39-147.nat.ucy.ac.cy
NOERROR	nat30-118.nat.ucy.ac.cy
NXDOMAIN	nat39-83.nat.ucy.ac.cy
NOERROR	nat36-4.nat.ucy.ac.cy
NXDOMAIN	nat39-58.nat.ucy.ac.cy
NXDOMAIN	bannerint.ucy.ac.cy
NOERROR	nat36-64.nat.ucy.ac.cy
NOERROR	nat38-10.nat.ucy.ac.cy
NXDOMAIN	oitapp01.ucy.ac.cy
NOERROR	nat37-29.nat.ucy.ac.cy
NOERROR	nat36-246.nat.ucy.ac.cy
NOERROR	nat37-232.nat.ucy.ac.cy
NOERROR	nat38-177.nat.ucy.ac.cy
NOERROR	planetlab-1.cs.ucy.ac.cy
NOERROR	nat35-150.nat.ucy.ac.cy
NOERROR	nat38-199.nat.ucy.ac.cy
NOERROR	nat36-121.nat.ucy.ac.cy
NOERROR	bioscience.ucy.ac.cy
NXDOMAIN	orw.lib.ucy.ac.cy
NOERROR	nat37-222.nat.ucy.ac.cy
NXDOMAIN	nat39-208.nat.ucy.ac.cy
NOERROR	nat36-192.nat.ucy.ac.cy
NOERROR	nat38-27.nat.ucy.ac.cy
NXDOMAIN	poseidon.cs.ucy.ac.cy
NOERROR	nat30-74.nat.ucy.ac.cy
NOERROR	physics.ucy.ac.cy
NXDOMAIN	streamingsrvoc.ucy.ac.cy
NXDOMAIN	nat39-56.nat.ucy.ac.cy
NXDOMAIN	nat39-199.nat.ucy.ac.cy
NOERROR	ip6.vega1.ucy.ac.cy
NOERROR	privacypolicybeautifier.cs.ucy.ac.cy
NOERROR	nat38-247.nat.ucy.ac.cy
NOERROR	nat35-89.nat.ucy.ac.cy
NOERROR	iotlab.cs.ucy.ac.cy
NOERROR	nat38-69.nat.ucy.ac.cy
NOERROR	nat213.cs.ucy.ac.cy
NXDOMAIN	nat39-105.nat.ucy.ac.cy
NXDOMAIN	nat39-80.nat.ucy.ac.cy
NOERROR	wn120.grid.ucy.ac.cy
NOERROR	nat37-37.nat.ucy.ac.cy
NOERROR	nat35-245.nat.ucy.ac.cy
NOERROR	cream201.grid.ucy.ac.cy
NOERROR	ip5.vega1.ucy.ac.cy
NOERROR	nat5-122.nat.ucy.ac.cy
NOERROR	nat38-106.nat.ucy.ac.cy
NOERROR	nat36-163.nat.ucy.ac.cy
NXDOMAIN	nat39-43.nat.ucy.ac.cy
NXDOMAIN	www.presence2.srvvoice.ucy.ac.cy
NOERROR	nat30-213.nat.ucy.ac.cy
NOERROR	nat35-236.nat.ucy.ac.cy
NOERROR	thales.mas.ucy.ac.cy
NXDOMAIN	www.asset2002.ucy.ac.cy
NOERROR	nat38-94.nat.ucy.ac.cy
NXDOMAIN	nat39-150.nat.ucy.ac.cy
NOERROR	nat5-98.nat.ucy.ac.cy
NOERROR	nat5-128.nat.ucy.ac.cy
NOERROR	nat38-198.nat.ucy.ac.cy
NOERROR	dmac.cs.ucy.ac.cy
NOERROR	nat36-220.nat.ucy.ac.cy
NOERROR	nat5-216.nat.ucy.ac.cy
NXDOMAIN	foh.ucy.ac.cy
NOERROR	nat35-100.nat.ucy.ac.cy
NOERROR	graphics.cs.ucy.ac.cy
NOERROR	nat36-83.nat.ucy.ac.cy
NXDOMAIN	nat39-156.nat.ucy.ac.cy
NOERROR	nat38-105.nat.ucy.ac.cy
NOERROR	canis.polytech.ucy.ac.cy
NOERROR	nat38-41.nat.ucy.ac.cy
NOERROR	nat37-132.nat.ucy.ac.cy
NXDOMAIN	nat39-1.nat.ucy.ac.cy
NXDOMAIN	portal.qa.ucy.ac.cy
NOERROR	nat30-174.nat.ucy.ac.cy
NOERROR	www.apollon.ucy.ac.cy
NOERROR	nat30-48.nat.ucy.ac.cy
NOERROR	nat37-201.nat.ucy.ac.cy
NXDOMAIN	nat39-205.nat.ucy.ac.cy
NXDOMAIN	repository.lib.ucy.ac.cy
NOERROR	nat35-182.nat.ucy.ac.cy
NOERROR	nat36-249.nat.ucy.ac.cy
NOERROR	mail.cs.ucy.ac.cy
NOERROR	nat35-254.nat.ucy.ac.cy
NOERROR	proxy.cc.ucy.ac.cy
NOERROR	nat38-1.nat.ucy.ac.cy
NOERROR	nat36-230.nat.ucy.ac.cy
NOERROR	nat36-247.nat.ucy.ac.cy
NOERROR	nat38-8.nat.ucy.ac.cy
NOERROR	nat36-162.nat.ucy.ac.cy
NOERROR	appint.lib.ucy.ac.cy
NOERROR	www.endiktis.cs.ucy.ac.cy
NOERROR	nat30-43.nat.ucy.ac.cy
NOERROR	nat37-161.nat.ucy.ac.cy
NOERROR	nat5-87.nat.ucy.ac.cy
NXDOMAIN	www.asweb.ucy.ac.cy
NOERROR	nat37-114.nat.ucy.ac.cy
NOERROR	2beconnected.ucy.ac.cy
NOERROR	nat37-15.nat.ucy.ac.cy
NXDOMAIN	ktree.cs.ucy.ac.cy
NOERROR	nat30-168.nat.ucy.ac.cy
NOERROR	nat36-148.nat.ucy.ac.cy
NOERROR	nat5-82.nat.ucy.ac.cy
NOERROR	nat35-42.nat.ucy.ac.cy
NOERROR	nat5-194.nat.ucy.ac.cy
NXDOMAIN	nat39-211.nat.ucy.ac.cy
NOERROR	nat5-211.nat.ucy.ac.cy
NXDOMAIN	nat39-235.nat.ucy.ac.cy
NOERROR	intns1.dns.ucy.ac.cy
NOERROR	nat36-57.nat.ucy.ac.cy
NXDOMAIN	nat39-151.nat.ucy.ac.cy
NOERROR	nat37-178.nat.ucy.ac.cy
NXDOMAIN	nat39-133.nat.ucy.ac.cy
NOERROR	nat36-212.nat.ucy.ac.cy
NOERROR	lexcy.lib.ucy.ac.cy
NOERROR	hrm360.leventis.ucy.ac.cy
NOERROR	nat36-240.nat.ucy.ac.cy
NXDOMAIN	idm02.ucy.ac.cy
NXDOMAIN	nat39-141.nat.ucy.ac.cy
NXDOMAIN	nat39-64.nat.ucy.ac.cy
NOERROR	nat36-178.nat.ucy.ac.cy
NOERROR	nat38-148.nat.ucy.ac.cy
NOERROR	nat5-150.nat.ucy.ac.cy
NOERROR	nat35-104.nat.ucy.ac.cy
NOERROR	nat5-138.nat.ucy.ac.cy
NOERROR	imap2.cs.ucy.ac.cy
NXDOMAIN	nat39-181.nat.ucy.ac.cy
NOERROR	merope.polytech.ucy.ac.cy
NOERROR	nat38-252.nat.ucy.ac.cy
NOERROR	nat30-233.nat.ucy.ac.cy
NXDOMAIN	cpcalendars.edbticdt2021.cs.ucy.ac.cy
NXDOMAIN	ermisweb4.ucy.ac.cy
NXDOMAIN	nat39-130.nat.ucy.ac.cy
NOERROR	nat38-245.nat.ucy.ac.cy
NOERROR	nat5-111.nat.ucy.ac.cy
NOERROR	nat5-19.nat.ucy.ac.cy
NOERROR	nat36-118.nat.ucy.ac.cy
NOERROR	nat37-160.nat.ucy.ac.cy
NXDOMAIN	mail.ccgrid2019.ucy.ac.cy
NOERROR	www.co2nor.ucy.ac.cy
NXDOMAIN	www.presence.srvvoice.ucy.ac.cy
NOERROR	nat38-232.nat.ucy.ac.cy
NOERROR	nat38-158.nat.ucy.ac.cy
NOERROR	nat35-80.nat.ucy.ac.cy
NOERROR	nat38-4.nat.ucy.ac.cy
NOERROR	wn137.grid.ucy.ac.cy
NOERROR	nat38-125.nat.ucy.ac.cy
NOERROR	nat30-133.nat.ucy.ac.cy
NXDOMAIN	webdisk.edbt2021.cs.ucy.ac.cy
NOERROR	cc-6509-ge-1-15.cc.ucy.ac.cy
NXDOMAIN	nat39-244.nat.ucy.ac.cy
NOERROR	msccis.ucy.ac.cy
NOERROR	icsoc2011.cs.ucy.ac.cy
NOERROR	icsob2014.cs.ucy.ac.cy
NOERROR	sunsrv.sunlabgp.ucy.ac.cy
NOERROR	www2.kios.ucy.ac.cy
NOERROR	nat30-205.nat.ucy.ac.cy
NOERROR	nat36-8.nat.ucy.ac.cy
NXDOMAIN	nat39-93.nat.ucy.ac.cy
NOERROR	nat35-132.nat.ucy.ac.cy
NOERROR	nat38-186.nat.ucy.ac.cy
NOERROR	nat38-86.nat.ucy.ac.cy
NOERROR	euclid.mas.ucy.ac.cy
NOERROR	ip9.vega2.ucy.ac.cy
NOERROR	ipmt.ucy.ac.cy
NXDOMAIN	nat39-233.nat.ucy.ac.cy
NOERROR	nat36-110.nat.ucy.ac.cy
NOERROR	nat30-77.nat.ucy.ac.cy
NOERROR	nat5-212.nat.ucy.ac.cy
NOERROR	nat38-188.nat.ucy.ac.cy
NOERROR	fcslab.cs.ucy.ac.cy
NOERROR	mandola.grid.ucy.ac.cy
NOERROR	nat38-201.nat.ucy.ac.cy
NXDOMAIN	nat39-111.nat.ucy.ac.cy
NOERROR	nat30-188.nat.ucy.ac.cy
NOERROR	nat30-55.nat.ucy.ac.cy
NXDOMAIN	nat39-222.nat.ucy.ac.cy
NOERROR	nat38-88.nat.ucy.ac.cy
NOERROR	nat37-234.nat.ucy.ac.cy
NOERROR	libblog.ucy.ac.cy
NOERROR	sslvpn.ucy.ac.cy
NOERROR	pvtechnology.ucy.ac.cy
NOERROR	nat5-186.nat.ucy.ac.cy
NXDOMAIN	webmail.live.ucy-web-server.ucy.ac.cy
NOERROR	nat5-77.nat.ucy.ac.cy
NOERROR	nat35-135.nat.ucy.ac.cy
NOERROR	ap-dev.cs.ucy.ac.cy
NOERROR	nat36-7.nat.ucy.ac.cy
NOERROR	nat30-97.nat.ucy.ac.cy
NOERROR	wordpressadmin.ucy.ac.cy
NOERROR	nat37-199.nat.ucy.ac.cy
NOERROR	nat36-73.nat.ucy.ac.cy
NOERROR	nat30-78.nat.ucy.ac.cy
NXDOMAIN	radius02.ucy.ac.cy
NOERROR	zerosrv2.sharks.ucy.ac.cy
NXDOMAIN	nat39-188.nat.ucy.ac.cy
NOERROR	nat38-53.nat.ucy.ac.cy
NOERROR	nat36-234.nat.ucy.ac.cy
NOERROR	nat35-189.nat.ucy.ac.cy
NOERROR	wn113.grid.ucy.ac.cy
NOERROR	lfc201.grid.ucy.ac.cy
NXDOMAIN	cm1.srvvoice.ucy.ac.cy
NXDOMAIN	soa.dev.ucy.ac.cy
NOERROR	nat38-120.nat.ucy.ac.cy
NOERROR	nat35-134.nat.ucy.ac.cy
NOERROR	www.wise2012.cs.ucy.ac.cy
NOERROR	videoserver.cc.ucy.ac.cy
NOERROR	nat37-185.nat.ucy.ac.cy
NOERROR	triton.ucy.ac.cy
NOERROR	effinet.ucy.ac.cy
NXDOMAIN	nat39-129.nat.ucy.ac.cy
NOERROR	nat38-114.nat.ucy.ac.cy
NOERROR	nat5-85.nat.ucy.ac.cy
NOERROR	nat36-87.nat.ucy.ac.cy
NOERROR	nat37-188.nat.ucy.ac.cy
NOERROR	www.pythagoras.mas.ucy.ac.cy
NOERROR	nat38-50.nat.ucy.ac.cy
NOERROR	se201.grid.ucy.ac.cy
NOERROR	epayments.csrv.ucy.ac.cy
NOERROR	nat38-130.nat.ucy.ac.cy
NXDOMAIN	nat39-230.nat.ucy.ac.cy
NOERROR	estia.cs.ucy.ac.cy
NOERROR	vsense.cs.ucy.ac.cy
NOERROR	www.cse2012.cs.ucy.ac.cy
NOERROR	nat38-33.nat.ucy.ac.cy
NXDOMAIN	nat39-197.nat.ucy.ac.cy
NOERROR	www.eumas09.cs.ucy.ac.cy
NOERROR	nat35-152.nat.ucy.ac.cy
NOERROR	nat5-112.nat.ucy.ac.cy
NOERROR	nat35-197.nat.ucy.ac.cy
NOERROR	nat5-63.nat.ucy.ac.cy
NOERROR	nat30-76.nat.ucy.ac.cy
NOERROR	nat38-195.nat.ucy.ac.cy
NOERROR	packages.ucy.ac.cy
NOERROR	nat30-166.nat.ucy.ac.cy
NXDOMAIN	in.cs.ucy.ac.cy
NOERROR	theodora.cs.ucy.ac.cy
NOERROR	nat35-119.nat.ucy.ac.cy
NOERROR	nat36-69.nat.ucy.ac.cy
NOERROR	nat30-211.nat.ucy.ac.cy
NOERROR	opensciencecy.ucy.ac.cy
NOERROR	nat38-160.nat.ucy.ac.cy
NOERROR	nat38-36.nat.ucy.ac.cy
NOERROR	smtp.cs.ucy.ac.cy
NOERROR	nat30-143.nat.ucy.ac.cy
NOERROR	nat36-47.nat.ucy.ac.cy
NOERROR	cihs.cs.ucy.ac.cy
NOERROR	nat37-19.nat.ucy.ac.cy
NOERROR	nat30-66.nat.ucy.ac.cy
NXDOMAIN	www.lavoisier.chem.ucy.ac.cy
NOERROR	nat30-201.nat.ucy.ac.cy
NOERROR	nat35-102.nat.ucy.ac.cy
NOERROR	nat36-223.nat.ucy.ac.cy
NOERROR	nat36-107.nat.ucy.ac.cy
NXDOMAIN	www.aquila.ucy.ac.cy
NOERROR	nat38-101.nat.ucy.ac.cy
