NXDOMAIN	www.nastani.uist.edu.mk
NXDOMAIN	sandbox.uist.edu.mk
NOERROR	cpanel.uist.edu.mk
NOERROR	mail.uist.edu.mk
NOERROR	uist.edu.mk
NOERROR	www.upisi.uist.edu.mk
NOERROR	www.ipp.uist.edu.mk
NOERROR	cns.uist.edu.mk
NOERROR	www.mihajlov.uist.edu.mk
NXDOMAIN	www.rkju.uist.edu.mk
NOERROR	cpcalendars.uist.edu.mk
NOERROR	www.ejist.uist.edu.mk
NOERROR	www.ciptt.uist.edu.mk
NOERROR	www.uist.edu.mk
NXDOMAIN	itsoc.uist.edu.mk
NXDOMAIN	accomodation.uist.edu.mk
NOERROR	mir.uist.edu.mk
NXDOMAIN	www.metalstilinzinering.uist.edu.mk
NOERROR	ami.uist.edu.mk
NOERROR	bioengineering.uist.edu.mk
NXDOMAIN	www.itsoc.uist.edu.mk
NOERROR	www.va-plast.uist.edu.mk
NOERROR	cse.uist.edu.mk
NOERROR	webmail.uist.edu.mk
NOERROR	ita.uist.edu.mk
NXDOMAIN	1000ideizapodobarohrid.uist.edu.mk
NXDOMAIN	www.msl.uist.edu.mk
NXDOMAIN	balkancrypt.uist.edu.mk
NXDOMAIN	cf.uist.edu.mk
NOERROR	www.ita.uist.edu.mk
NOERROR	upisi.uist.edu.mk
NXDOMAIN	gp.uist.edu.mk
NOERROR	ciptt.uist.edu.mk
NOERROR	act.uist.edu.mk
NOERROR	www.isvma.uist.edu.mk
NOERROR	cpcontacts.uist.edu.mk
NOERROR	www.mir.uist.edu.mk
NXDOMAIN	www.proba.uist.edu.mk
NOERROR	klibo.uist.edu.mk
NOERROR	webdisk.uist.edu.mk
NOERROR	www.ami.uist.edu.mk
NOERROR	tac.uist.edu.mk
NXDOMAIN	rkju.uist.edu.mk
NOERROR	isvma.uist.edu.mk
NOERROR	www.cns.uist.edu.mk
NOERROR	www.mmll.uist.edu.mk
NOERROR	moodle.uist.edu.mk
NOERROR	mmll.uist.edu.mk
NOERROR	mihajlov.uist.edu.mk
NXDOMAIN	proba.uist.edu.mk
NOERROR	autodiscover.uist.edu.mk
NOERROR	www.klibo.uist.edu.mk
NXDOMAIN	nastani.uist.edu.mk
NOERROR	www.upis.uist.edu.mk
NOERROR	upis.uist.edu.mk
NOERROR	ejist.uist.edu.mk
NOERROR	www.act.uist.edu.mk
NXDOMAIN	visitohrid.uist.edu.mk
NOERROR	va-plast.uist.edu.mk
NOERROR	www.bioengineering.uist.edu.mk
NOERROR	www.tac.uist.edu.mk
NOERROR	www.moodle.uist.edu.mk
NOERROR	ipp.uist.edu.mk
NXDOMAIN	metalstilinzinering.uist.edu.mk
NXDOMAIN	www.sandbox.uist.edu.mk
NOERROR	www.cse.uist.edu.mk
