#!/bin/sh

n=$(ls -1 subdomains/ | wc | awk '{print $1}')

i=1

while [ $i -le $n ]; do
	domain=$(ls -1 subdomains/ | sed "${i}q;d")
	j=1
	Mi=$(wc subdomains/$domain | awk '{print $1}')

	while [ $j -le $Mi ]; do
		links -dump $(sed "${j}q;d" subdomains/$domain) | wc -l >> status
		j=$((++j))
	done

	i=$((++i))
done
